#ifndef GUARD_LAB_JUNCTION_TILES_H
#define GUARD_LAB_JUNCTION_TILES_H

// Generated shared hub aliases; do not edit.
#define METATILE_LabJunction_Floor 0x000
#define METATILE_LabJunction_FloorShadow 0x001
#define METATILE_LabJunction_Void 0x002
#define METATILE_LabJunction_PillarCap 0x003
#define METATILE_LabJunction_PillarJoin 0x004
#define METATILE_LabJunction_Pillar 0x005
#define METATILE_LabJunction_PillarEnd 0x006
#define METATILE_LabJunction_Wall 0x008
#define METATILE_LabJunction_WallBase 0x009
#define METATILE_LabJunction_InnerJoin 0x00A
#define METATILE_LabJunction_InnerBase 0x00B
#define METATILE_LabJunction_InnerFoot 0x00C
#define METATILE_LabJunction_FrameTopLeft 0x00D
#define METATILE_LabJunction_FrameTop 0x00E
#define METATILE_LabJunction_FrameTopRight 0x00F
#define METATILE_LabJunction_FrameLeft 0x010
#define METATILE_LabJunction_FrameRight 0x011
#define METATILE_LabJunction_Door 0x03A
#define METATILE_LabJunction_SignTop 0x01E
#define METATILE_LabJunction_SignBase 0x01F
#define METATILE_LabJunction_SpecimenBank_0_0 0x018
#define METATILE_LabJunction_SpecimenBank_1_0 0x019
#define METATILE_LabJunction_SpecimenBank_0_1 0x01A
#define METATILE_LabJunction_SpecimenBank_1_1 0x01B
#define METATILE_LabJunction_SpecimenBank_0_2 0x01C
#define METATILE_LabJunction_SpecimenBank_1_2 0x01D
#define METATILE_LabJunction_ComputerBench_0_0 0x03B
#define METATILE_LabJunction_ComputerBench_1_0 0x03C
#define METATILE_LabJunction_ComputerBench_0_1 0x03D
#define METATILE_LabJunction_ComputerBench_1_1 0x03E
#define METATILE_LabJunction_ApproachLeft 0x023
#define METATILE_LabJunction_ApproachRight 0x024
#define METATILE_LabJunction_FloorFadeWest 0x025
#define METATILE_LabJunction_FloorFadeEast 0x026
#define METATILE_LabJunction_FloorDim40 0x027
#define METATILE_LabJunction_FloorDim20 0x028
#define METATILE_LabJunction_FloorShadowFadeWest 0x029
#define METATILE_LabJunction_FloorShadowFadeEast 0x02A
#define METATILE_LabJunction_FloorShadowDim40 0x02B
#define METATILE_LabJunction_FloorShadowDim20 0x02C
#define METATILE_LabJunction_FloorFadeNorth 0x03F
#define METATILE_LabJunction_FloorFadeSouth 0x02D
#define METATILE_LabJunction_WarpWest 0x013
#define METATILE_LabJunction_WarpEast 0x014
#define METATILE_LabJunction_WarpNorth 0x040
#define METATILE_LabJunction_WarpSouth 0x041
#define METATILE_LabJunction_WarpWestUpper 0x016
#define METATILE_LabJunction_WarpEastUpper 0x017
#define METATILE_LabJunction_Decor_Table_0_0 0x030
#define METATILE_LabJunction_Decor_Table_1_0 0x031
#define METATILE_LabJunction_Decor_Table_0_1 0x032
#define METATILE_LabJunction_Decor_Table_1_1 0x033
#define METATILE_LabJunction_Decor_Stool_0_0 0x034
#define METATILE_LabJunction_Decor_Cargo_0_0 0x035
#define METATILE_LabJunction_Decor_Cargo_1_0 0x036
#define METATILE_LabJunction_Decor_Cargo_0_1 0x035
#define METATILE_LabJunction_Decor_Cargo_1_1 0x036
#define METATILE_LabJunction_Decor_Cargo_0_2 0x037
#define METATILE_LabJunction_Decor_Cargo_1_2 0x038
#define METATILE_LabJunction_Decor_WallPlate_0_0 0x039
#define LAB_JUNCTION_DOOR_PALETTE 11

#endif
