#ifndef GUARD_METATILE_LABELS_H
#define GUARD_METATILE_LABELS_H

// gTileset_AdventurePaths
#define METATILE_AdventurePaths_Debris_PairLeft               0x323
#define METATILE_AdventurePaths_Debris_PairRight              0x324
#define METATILE_AdventurePaths_Debris_Single0                0x319
#define METATILE_AdventurePaths_Debris_Single1                0x31A
#define METATILE_AdventurePaths_Debris_Single2                0x31B
#define METATILE_AdventurePaths_Debris_Single3                0x31C
#define METATILE_AdventurePaths_Debris_Single4                0x31D
#define METATILE_AdventurePaths_Debris_Single5                0x31E
#define METATILE_AdventurePaths_Debris_Single6                0x31F
#define METATILE_AdventurePaths_Debris_Single7                0x320
#define METATILE_AdventurePaths_Debris_Single8                0x321
#define METATILE_AdventurePaths_Debris_Single9                0x322
#define METATILE_AdventurePaths_FormationA_BottomLeft         0x23C
#define METATILE_AdventurePaths_FormationA_BottomRight        0x23D
#define METATILE_AdventurePaths_FormationA_MiddleLeft         0x23A
#define METATILE_AdventurePaths_FormationA_MiddleRight        0x23B
#define METATILE_AdventurePaths_FormationA_TopLeft            0x238
#define METATILE_AdventurePaths_FormationA_TopRight           0x239
#define METATILE_AdventurePaths_FormationB_BottomLeft         0x242
#define METATILE_AdventurePaths_FormationB_BottomRight        0x243
#define METATILE_AdventurePaths_FormationB_MiddleLeft         0x240
#define METATILE_AdventurePaths_FormationB_MiddleRight        0x241
#define METATILE_AdventurePaths_FormationB_TopLeft            0x23E
#define METATILE_AdventurePaths_FormationB_TopRight           0x23F
#define METATILE_AdventurePaths_FormationOverlayA_Base        0x250
#define METATILE_AdventurePaths_FormationOverlayB_Base        0x2AA
#define METATILE_AdventurePaths_Island_CliffFace              0x213
#define METATILE_AdventurePaths_Island_CliffFace1             0x219
#define METATILE_AdventurePaths_Island_CliffFace2             0x21A
#define METATILE_AdventurePaths_Island_CliffFace_Left         0x214
#define METATILE_AdventurePaths_Island_CliffFace_Right        0x215
#define METATILE_AdventurePaths_Island_CliffGlow              0x216
#define METATILE_AdventurePaths_Island_CliffGlow1             0x217
#define METATILE_AdventurePaths_Island_CliffGlow2             0x218
#define METATILE_AdventurePaths_Island_Corner_NorthEast       0x20B
#define METATILE_AdventurePaths_Island_Corner_NorthWest       0x20E
#define METATILE_AdventurePaths_Island_Corner_SouthEast       0x20C
#define METATILE_AdventurePaths_Island_Corner_SouthWest       0x20D
#define METATILE_AdventurePaths_Island_Edge_East              0x208
#define METATILE_AdventurePaths_Island_Edge_North             0x207
#define METATILE_AdventurePaths_Island_Edge_South             0x209
#define METATILE_AdventurePaths_Island_Edge_South1            0x21B
#define METATILE_AdventurePaths_Island_Edge_South2            0x21C
#define METATILE_AdventurePaths_Island_Edge_West              0x20A
#define METATILE_AdventurePaths_Island_InnerCorner_NorthEast  0x20F
#define METATILE_AdventurePaths_Island_InnerCorner_NorthWest  0x212
#define METATILE_AdventurePaths_Island_InnerCorner_SouthEast  0x210
#define METATILE_AdventurePaths_Island_InnerCorner_SouthWest  0x211
#define METATILE_AdventurePaths_Island_Interior0              0x204
#define METATILE_AdventurePaths_Island_Interior1              0x205
#define METATILE_AdventurePaths_Island_Interior2              0x206
#define METATILE_AdventurePaths_Island_Underside_Left         0x247
#define METATILE_AdventurePaths_Island_Underside_Middle0      0x248
#define METATILE_AdventurePaths_Island_Underside_Middle1      0x249
#define METATILE_AdventurePaths_Island_Underside_Middle2      0x24A
#define METATILE_AdventurePaths_Island_Underside_Right        0x24B
#define METATILE_AdventurePaths_Island_Underside_Shadow0      0x308
#define METATILE_AdventurePaths_Island_Underside_Shadow1      0x309
#define METATILE_AdventurePaths_Island_Underside_Shadow2      0x30A
#define METATILE_AdventurePaths_Item_Pedestal                 0x307
#define METATILE_AdventurePaths_Satellite_SurfaceLeft         0x314
#define METATILE_AdventurePaths_Satellite_SurfaceMiddle0      0x315
#define METATILE_AdventurePaths_Satellite_SurfaceMiddle1      0x316
#define METATILE_AdventurePaths_Satellite_SurfaceMiddle2      0x317
#define METATILE_AdventurePaths_Satellite_SurfaceRight        0x318
#define METATILE_AdventurePaths_Surface_CrystalClusterBlue0   0x304
#define METATILE_AdventurePaths_Surface_CrystalClusterBlue1   0x305
#define METATILE_AdventurePaths_Surface_FleckCyan             0x234
#define METATILE_AdventurePaths_Surface_FleckViolet           0x235
#define METATILE_AdventurePaths_Surface_Fractured0            0x232
#define METATILE_AdventurePaths_Surface_Fractured1            0x233
#define METATILE_AdventurePaths_Surface_MineralCyan           0x24E
#define METATILE_AdventurePaths_Surface_MineralViolet         0x24F
#define METATILE_AdventurePaths_Surface_Pebbles0              0x236
#define METATILE_AdventurePaths_Surface_Pebbles1              0x237
#define METATILE_AdventurePaths_Surface_Rock0                 0x24C
#define METATILE_AdventurePaths_Surface_Rock1                 0x24D
#define METATILE_AdventurePaths_Terrace_Face0                 0x244
#define METATILE_AdventurePaths_Terrace_Face1                 0x245
#define METATILE_AdventurePaths_Terrace_Face2                 0x246
#define METATILE_AdventurePaths_Terrace_FaceLeftSlant0        0x30B
#define METATILE_AdventurePaths_Terrace_FaceLeftSlant1        0x30C
#define METATILE_AdventurePaths_Terrace_FaceLeftSlant2        0x30D
#define METATILE_AdventurePaths_Terrace_FaceRightSlant0       0x311
#define METATILE_AdventurePaths_Terrace_FaceRightSlant1       0x312
#define METATILE_AdventurePaths_Terrace_FaceRightSlant2       0x313
#define METATILE_AdventurePaths_Terrace_FaceShadow0           0x30E
#define METATILE_AdventurePaths_Terrace_FaceShadow1           0x30F
#define METATILE_AdventurePaths_Terrace_FaceShadow2           0x310
#define METATILE_AdventurePaths_Trail_BlockedHorizontal       0x230
#define METATILE_AdventurePaths_Trail_BlockedVertical         0x231
#define METATILE_AdventurePaths_Trail_Centre                  0x220
#define METATILE_AdventurePaths_Trail_Corner_NorthEast        0x223
#define METATILE_AdventurePaths_Trail_Corner_NorthWest        0x226
#define METATILE_AdventurePaths_Trail_Corner_SouthEast        0x224
#define METATILE_AdventurePaths_Trail_Corner_SouthWest        0x225
#define METATILE_AdventurePaths_Trail_Cross                   0x22B
#define METATILE_AdventurePaths_Trail_EndEast                 0x22D
#define METATILE_AdventurePaths_Trail_EndNorth                0x22C
#define METATILE_AdventurePaths_Trail_EndSouth                0x22E
#define METATILE_AdventurePaths_Trail_EndWest                 0x22F
#define METATILE_AdventurePaths_Trail_ExitSouth               0x306
#define METATILE_AdventurePaths_Trail_Horizontal              0x221
#define METATILE_AdventurePaths_Trail_T_MissingEast           0x228
#define METATILE_AdventurePaths_Trail_T_MissingNorth          0x227
#define METATILE_AdventurePaths_Trail_T_MissingSouth          0x229
#define METATILE_AdventurePaths_Trail_T_MissingWest           0x22A
#define METATILE_AdventurePaths_Trail_Vertical                0x222
#define METATILE_AdventurePaths_Void                          0x200
#define METATILE_AdventurePaths_Void_Stars0                   0x201
#define METATILE_AdventurePaths_Void_Stars1                   0x202
#define METATILE_AdventurePaths_Void_Stars2                   0x203

// gTileset_BattleArena
#define METATILE_BattleArena_Door  0x21B

// gTileset_BattleDome
#define METATILE_BattleDome_Door_Corridor       0x25E
#define METATILE_BattleDome_Door_Lobby          0x209
#define METATILE_BattleDome_Door_PreBattleRoom  0x20A

// gTileset_BattleFrontier
#define METATILE_BattleFrontier_CorridorOpenDoor_Bottom  0x20F
#define METATILE_BattleFrontier_CorridorOpenDoor_Top     0x207
#define METATILE_BattleFrontier_Door_Elevator            0x20E
#define METATILE_BattleFrontier_Door_MultiCorridor       0x2AD
#define METATILE_BattleFrontier_Elevator_Bottom0         0x339
#define METATILE_BattleFrontier_Elevator_Bottom1         0x33A
#define METATILE_BattleFrontier_Elevator_Bottom2         0x33B
#define METATILE_BattleFrontier_Elevator_Mid0            0x331
#define METATILE_BattleFrontier_Elevator_Mid1            0x332
#define METATILE_BattleFrontier_Elevator_Mid2            0x333
#define METATILE_BattleFrontier_Elevator_Top0            0x329
#define METATILE_BattleFrontier_Elevator_Top1            0x32A
#define METATILE_BattleFrontier_Elevator_Top2            0x32B

// gTileset_BattleFrontierOutsideEast
#define METATILE_BattleFrontierOutsideEast_Door              0x3FC
#define METATILE_BattleFrontierOutsideEast_Door_BattleArena  0x291
#define METATILE_BattleFrontierOutsideEast_Door_BattleTower  0x329
#define METATILE_BattleFrontierOutsideEast_Door_Sliding      0x396

// gTileset_BattleFrontierOutsideWest
#define METATILE_BattleFrontierOutsideWest_Door                0x3FC
#define METATILE_BattleFrontierOutsideWest_Door_BattleDome     0x28A
#define METATILE_BattleFrontierOutsideWest_Door_BattleFactory  0x263
#define METATILE_BattleFrontierOutsideWest_Door_Sliding        0x396

// gTileset_BattlePalace
#define METATILE_BattlePalace_Door  0x219

// gTileset_BattlePike
#define METATILE_BattlePike_CurtainFrames_Start   0x201
#define METATILE_BattlePike_Curtain_Stage0_Tile0  0x24A
#define METATILE_BattlePike_Curtain_Stage0_Tile1  0x251
#define METATILE_BattlePike_Curtain_Stage0_Tile2  0x252
#define METATILE_BattlePike_Curtain_Stage0_Tile3  0x253
#define METATILE_BattlePike_Curtain_Stage0_Tile4  0x259
#define METATILE_BattlePike_Curtain_Stage0_Tile5  0x25A
#define METATILE_BattlePike_Curtain_Stage0_Tile6  0x25B
#define METATILE_BattlePike_Curtain_Stage1_Tile0  0x22A
#define METATILE_BattlePike_Curtain_Stage1_Tile1  0x231
#define METATILE_BattlePike_Curtain_Stage1_Tile2  0x232
#define METATILE_BattlePike_Curtain_Stage1_Tile3  0x233
#define METATILE_BattlePike_Curtain_Stage1_Tile4  0x239
#define METATILE_BattlePike_Curtain_Stage1_Tile5  0x23A
#define METATILE_BattlePike_Curtain_Stage1_Tile6  0x23B
#define METATILE_BattlePike_Curtain_Stage2_Tile0  0x20A
#define METATILE_BattlePike_Curtain_Stage2_Tile1  0x211
#define METATILE_BattlePike_Curtain_Stage2_Tile2  0x212
#define METATILE_BattlePike_Curtain_Stage2_Tile3  0x213
#define METATILE_BattlePike_Curtain_Stage2_Tile4  0x219
#define METATILE_BattlePike_Curtain_Stage2_Tile5  0x21A
#define METATILE_BattlePike_Curtain_Stage2_Tile6  0x21B
#define METATILE_BattlePike_Curtain_Stage3_Tile0  0x2AB
#define METATILE_BattlePike_Curtain_Stage3_Tile1  0x2B2
#define METATILE_BattlePike_Curtain_Stage3_Tile2  0x2B3
#define METATILE_BattlePike_Curtain_Stage3_Tile3  0x2B4
#define METATILE_BattlePike_Curtain_Stage3_Tile4  0x2BA
#define METATILE_BattlePike_Curtain_Stage3_Tile5  0x2BB
#define METATILE_BattlePike_Curtain_Stage3_Tile6  0x2BC

// gTileset_BattlePyramid
#define METATILE_BattlePyramid_Exit   0x28E
#define METATILE_BattlePyramid_Floor  0x28D

// gTileset_BattleTent
#define METATILE_BattleTent_Door  0x26B

// gTileset_BikeShop
#define METATILE_BikeShop_Barrier_Blue_Bottom      0x2CF
#define METATILE_BikeShop_Barrier_Blue_BottomMid   0x2C7
#define METATILE_BikeShop_Barrier_Blue_Top         0x2B7
#define METATILE_BikeShop_Barrier_Blue_TopMid      0x2BF
#define METATILE_BikeShop_Barrier_Green_Bottom     0x2CE
#define METATILE_BikeShop_Barrier_Green_BottomMid  0x2C6
#define METATILE_BikeShop_Barrier_Green_Top        0x2B6
#define METATILE_BikeShop_Barrier_Green_TopMid     0x2BE
#define METATILE_BikeShop_Barrier_Hidden_Bottom    0x271
#define METATILE_BikeShop_Barrier_Hidden_Top       0x269
#define METATILE_BikeShop_Button_Blue              0x236
#define METATILE_BikeShop_Button_Green             0x22E
#define METATILE_BikeShop_Button_Pressed           0x24F
#define METATILE_BikeShop_Floor_Shadow_Top         0x26D
#define METATILE_BikeShop_Generator_Off_Tile0      0x2F0
#define METATILE_BikeShop_Generator_Off_Tile1      0x2F1
#define METATILE_BikeShop_Generator_Off_Tile2      0x2F2
#define METATILE_BikeShop_Generator_Off_Tile3      0x2F3
#define METATILE_BikeShop_Generator_Off_Tile4      0x2F4
#define METATILE_BikeShop_Generator_Off_Tile5      0x2F5
#define METATILE_BikeShop_Generator_Off_Tile6      0x2F6
#define METATILE_BikeShop_Generator_Off_Tile7      0x2F7
#define METATILE_BikeShop_Wall_Edge_Top            0x281

// gTileset_BrendansMaysHouse
#define METATILE_BrendansMaysHouse_BookOnTable       0x293
#define METATILE_BrendansMaysHouse_BrendanPC_Off     0x25A
#define METATILE_BrendansMaysHouse_BrendanPC_On      0x27F
#define METATILE_BrendansMaysHouse_MayPC_Off         0x259
#define METATILE_BrendansMaysHouse_MayPC_On          0x27E
#define METATILE_BrendansMaysHouse_MovingBox_Closed  0x268
#define METATILE_BrendansMaysHouse_MovingBox_Open    0x270

// gTileset_Building
#define METATILE_Building_PC_Off  0x004
#define METATILE_Building_PC_On   0x005
#define METATILE_Building_TV_Off  0x002
#define METATILE_Building_TV_On   0x003

// gTileset_Cave
#define METATILE_Cave_CrackedFloor                       0x22F
#define METATILE_Cave_CrackedFloor_Hole                  0x206
#define METATILE_Cave_EntranceCover                      0x229
#define METATILE_Cave_SealedChamberBraille_Mid           0x235
#define METATILE_Cave_SealedChamberEntrance_BottomLeft   0x232
#define METATILE_Cave_SealedChamberEntrance_BottomMid    0x233
#define METATILE_Cave_SealedChamberEntrance_BottomRight  0x234
#define METATILE_Cave_SealedChamberEntrance_TopLeft      0x22A
#define METATILE_Cave_SealedChamberEntrance_TopMid       0x22B
#define METATILE_Cave_SealedChamberEntrance_TopRight     0x22C
#define METATILE_Cave_ShoalCave_BlueStone_Large          0x359
#define METATILE_Cave_ShoalCave_BlueStone_Small          0x35B
#define METATILE_Cave_ShoalCave_DirtPile_Large           0x358
#define METATILE_Cave_ShoalCave_DirtPile_Small           0x35A

// gTileset_Contest
#define METATILE_Contest_CounterFlap_Bottom  0x2D9
#define METATILE_Contest_CounterFlap_Top     0x2D1
#define METATILE_Contest_FloorShadow         0x261
#define METATILE_Contest_WallShadow          0x221

// gTileset_Dewford
#define METATILE_Dewford_Door              0x225
#define METATILE_Dewford_Door_BattleTower  0x25D

// gTileset_EliteFour
#define METATILE_EliteFour_EntryDoor_ClosedBottom    0x20E
#define METATILE_EliteFour_EntryDoor_ClosedTop       0x206
#define METATILE_EliteFour_LeftSpotlightOff          0x2DD
#define METATILE_EliteFour_OpenDoorChampion_Frame    0x346
#define METATILE_EliteFour_OpenDoorChampion_Opening  0x347
#define METATILE_EliteFour_OpenDoor_Frame            0x344
#define METATILE_EliteFour_OpenDoor_Opening          0x345
#define METATILE_EliteFour_RightSpotlightOff         0x2DE

// gTileset_EverGrande
#define METATILE_EverGrande_Door_PokemonLeague  0x21D

// gTileset_Facility
#define METATILE_Facility_DataPad                       0x3E4
#define METATILE_Facility_NewMauvilleDoor_Closed_Tile0  0x314
#define METATILE_Facility_NewMauvilleDoor_Closed_Tile1  0x315
#define METATILE_Facility_NewMauvilleDoor_Closed_Tile2  0x316
#define METATILE_Facility_NewMauvilleDoor_Closed_Tile3  0x31C
#define METATILE_Facility_NewMauvilleDoor_Closed_Tile4  0x31D
#define METATILE_Facility_NewMauvilleDoor_Closed_Tile5  0x31E
#define METATILE_Facility_NewMauvilleDoor_Open_Tile0    0x2C3
#define METATILE_Facility_NewMauvilleDoor_Open_Tile1    0x2C4
#define METATILE_Facility_NewMauvilleDoor_Open_Tile2    0x2C5
#define METATILE_Facility_NewMauvilleDoor_Open_Tile3    0x2CB
#define METATILE_Facility_NewMauvilleDoor_Open_Tile4    0x2CC
#define METATILE_Facility_NewMauvilleDoor_Open_Tile5    0x2CD

// gTileset_Fallarbor
#define METATILE_Fallarbor_AshField                  0x218
#define METATILE_Fallarbor_AshGrass                  0x20A
#define METATILE_Fallarbor_BrownCaveEntrance_Bottom  0x261
#define METATILE_Fallarbor_BrownCaveEntrance_Top     0x259
#define METATILE_Fallarbor_BrownCaveIndent           0x208
#define METATILE_Fallarbor_BrownCaveOpen             0x210
#define METATILE_Fallarbor_BrownRockWall             0x265
#define METATILE_Fallarbor_Door_BattleTent           0x36C
#define METATILE_Fallarbor_Door_DarkRoof             0x2F7
#define METATILE_Fallarbor_Door_LightRoof            0x2A5
#define METATILE_Fallarbor_NormalGrass               0x212
#define METATILE_Fallarbor_RedCaveEntrance_Bottom    0x34F
#define METATILE_Fallarbor_RedCaveEntrance_Top       0x347
#define METATILE_Fallarbor_RedRockWall               0x269

// gTileset_Fortree
#define METATILE_Fortree_BridgeOverGrass_Lowered           0x24F
#define METATILE_Fortree_BridgeOverGrass_Raised            0x24E
#define METATILE_Fortree_BridgeOverTrees_Lowered           0x257
#define METATILE_Fortree_BridgeOverTrees_Raised            0x256
#define METATILE_Fortree_LongGrass_Root                    0x208
#define METATILE_Fortree_SecretBase_LongGrass_BottomLeft   0x281
#define METATILE_Fortree_SecretBase_LongGrass_BottomMid    0x282
#define METATILE_Fortree_SecretBase_LongGrass_BottomRight  0x283
#define METATILE_Fortree_SecretBase_LongGrass_TopLeft      0x279
#define METATILE_Fortree_SecretBase_LongGrass_TopMid       0x27A
#define METATILE_Fortree_SecretBase_LongGrass_TopRight     0x27B
#define METATILE_Fortree_SecretBase_Shrub                  0x271
#define METATILE_Fortree_SecretBase_ShrubOpen              0x278
#define METATILE_Fortree_WoodBridge1_Bottom                0x29F
#define METATILE_Fortree_WoodBridge1_Top                   0x297

// gTileset_General
#define METATILE_General_BlueCaveIndent        0x1B0
#define METATILE_General_BlueCaveOpen          0x1B1
#define METATILE_General_CalmWater             0x170
#define METATILE_General_CaveEntrance_Bottom   0x0A7
#define METATILE_General_CaveEntrance_Top      0x09F
#define METATILE_General_Door                  0x021
#define METATILE_General_Door_Contest          0x1DB
#define METATILE_General_Door_Gym              0x1CD
#define METATILE_General_Door_PokeCenter       0x061
#define METATILE_General_Door_PokeMart         0x041
#define METATILE_General_Grass                 0x001
#define METATILE_General_Grass_Stone           0x0E0
#define METATILE_General_Grass_TreeLeft        0x1CE
#define METATILE_General_Grass_TreeRight       0x1CF
#define METATILE_General_Grass_TreeUp          0x00E
#define METATILE_General_LongGrass             0x015
#define METATILE_General_Mountain_Stone        0x0E1
#define METATILE_General_MuddySlope_Frame0     0x0E8
#define METATILE_General_MuddySlope_Frame1     0x0E9
#define METATILE_General_MuddySlope_Frame2     0x0EA
#define METATILE_General_MuddySlope_Frame3     0x0EB
#define METATILE_General_RedCaveIndent         0x1A0
#define METATILE_General_RedCaveOpen           0x1A1
#define METATILE_General_ReflectiveWater       0x0A1
#define METATILE_General_RockWall_GrassBase    0x079
#define METATILE_General_RockWall_RockBase     0x07C
#define METATILE_General_RockWall_SandBase     0x091
#define METATILE_General_RoughDeepWater        0x14F
#define METATILE_General_RoughWater            0x14E
#define METATILE_General_SandPit_Center        0x121
#define METATILE_General_SandPit_Stone         0x0E2
#define METATILE_General_SecretBase_TreeLeft   0x026
#define METATILE_General_SecretBase_TreeRight  0x027
#define METATILE_General_SecretBase_VineLeft   0x036
#define METATILE_General_SecretBase_VineRight  0x037
#define METATILE_General_TallGrass             0x00D
#define METATILE_General_TallGrass_TreeLeft    0x1C6
#define METATILE_General_TallGrass_TreeRight   0x1C7
#define METATILE_General_TallGrass_TreeUp      0x025
#define METATILE_General_YellowCaveIndent      0x1A8
#define METATILE_General_YellowCaveOpen        0x1A9

// gTileset_GeneralHub
#define METATILE_GeneralHub_Door_PokeConnect                       0x062
#define METATILE_GeneralHub_Grass                                  0x001
#define METATILE_GeneralHub_GrassPath_Centre                       0x1D9
#define METATILE_GeneralHub_GrassPath_Conn_EastWest_North          0x1E1
#define METATILE_GeneralHub_GrassPath_Conn_EastWest_South          0x1D1
#define METATILE_GeneralHub_GrassPath_Conn_NorthEast               0x1E0
#define METATILE_GeneralHub_GrassPath_Conn_NorthSouth_East         0x1D8
#define METATILE_GeneralHub_GrassPath_Conn_NorthSouth_West         0x1DA
#define METATILE_GeneralHub_GrassPath_Conn_NorthWest               0x1E2
#define METATILE_GeneralHub_GrassPath_Conn_SouthEast               0x1D0
#define METATILE_GeneralHub_GrassPath_Conn_SouthWest               0x1D2
#define METATILE_GeneralHub_GrassWarpEast                          0x027
#define METATILE_GeneralHub_GrassWarpNorth                         0x01E
#define METATILE_GeneralHub_GrassWarpShadowEast                    0x037
#define METATILE_GeneralHub_GrassWarpShadowNorth                   0x02E
#define METATILE_GeneralHub_GrassWarpShadowSouth                   0x036
#define METATILE_GeneralHub_GrassWarpShadowWest                    0x02F
#define METATILE_GeneralHub_GrassWarpSouth                         0x026
#define METATILE_GeneralHub_GrassWarpWest                          0x01F
#define METATILE_GeneralHub_Grass_NorthDrop                        0x002
#define METATILE_GeneralHub_MountainRaised_Conn_EastWest_North     0x07C
#define METATILE_GeneralHub_MountainRaised_Conn_EastWest_South     0x06C
#define METATILE_GeneralHub_MountainRaised_Conn_NorthEast          0x07B
#define METATILE_GeneralHub_MountainRaised_Conn_NorthSouth_East    0x073
#define METATILE_GeneralHub_MountainRaised_Conn_NorthSouth_West    0x075
#define METATILE_GeneralHub_MountainRaised_Conn_NorthWest          0x07D
#define METATILE_GeneralHub_MountainRaised_Conn_SouthEast          0x06B
#define METATILE_GeneralHub_MountainRaised_Conn_SouthWest          0x06D
#define METATILE_GeneralHub_Mountain_Centre                        0x071
#define METATILE_GeneralHub_Mountain_Conn_EastWest_North           0x079
#define METATILE_GeneralHub_Mountain_Conn_EastWest_South           0x069
#define METATILE_GeneralHub_Mountain_Conn_NorthEast                0x078
#define METATILE_GeneralHub_Mountain_Conn_NorthSouth_East          0x070
#define METATILE_GeneralHub_Mountain_Conn_NorthSouth_West          0x072
#define METATILE_GeneralHub_Mountain_Conn_NorthWest                0x07A
#define METATILE_GeneralHub_Mountain_Conn_SouthEast                0x068
#define METATILE_GeneralHub_Mountain_Conn_SouthEast_Inside         0x074
#define METATILE_GeneralHub_Mountain_Conn_SouthWest                0x06A
#define METATILE_GeneralHub_Mountain_Conn_SouthWest_Inside         0x089
#define METATILE_GeneralHub_MuddyTracks                            0x055
#define METATILE_GeneralHub_Pebbles                                0x04D
#define METATILE_GeneralHub_Pond_Centre                            0x0A1
#define METATILE_GeneralHub_Pond_Conn_EastWest_South               0x0B1
#define METATILE_GeneralHub_Pond_Conn_NorthEast                    0x0C2
#define METATILE_GeneralHub_Pond_Conn_NorthSouth_East              0x0B8
#define METATILE_GeneralHub_Pond_Conn_NorthSouth_West              0x0BA
#define METATILE_GeneralHub_Pond_Conn_NorthWest                    0x0C0
#define METATILE_GeneralHub_Pond_Conn_SouthEast                    0x0B0
#define METATILE_GeneralHub_Pond_Conn_SouthWest                    0x0B2
#define METATILE_GeneralHub_SandPath_Centre                        0x121
#define METATILE_GeneralHub_SandPath_Conn_EastWest_North           0x129
#define METATILE_GeneralHub_SandPath_Conn_EastWest_South           0x119
#define METATILE_GeneralHub_SandPath_Conn_NorthEast                0x128
#define METATILE_GeneralHub_SandPath_Conn_NorthSouth_East          0x120
#define METATILE_GeneralHub_SandPath_Conn_NorthSouth_West          0x122
#define METATILE_GeneralHub_SandPath_Conn_NorthWest                0x12A
#define METATILE_GeneralHub_SandPath_Conn_SouthEast                0x118
#define METATILE_GeneralHub_SandPath_Conn_SouthWest                0x11A
#define METATILE_GeneralHub_SandPath_Stone                         0x0E2
#define METATILE_GeneralHub_StonePath_Centre                       0x109
#define METATILE_GeneralHub_StonePath_Conn_EastWest_North          0x111
#define METATILE_GeneralHub_StonePath_Conn_EastWest_South          0x101
#define METATILE_GeneralHub_StonePath_Conn_NorthEast               0x110
#define METATILE_GeneralHub_StonePath_Conn_NorthSouth_East         0x108
#define METATILE_GeneralHub_StonePath_Conn_NorthSouth_West         0x10A
#define METATILE_GeneralHub_StonePath_Conn_NorthWest               0x112
#define METATILE_GeneralHub_StonePath_Conn_SouthEast               0x100
#define METATILE_GeneralHub_StonePath_Conn_SouthWest               0x102
#define METATILE_GeneralHub_TallGrass                              0x00D
#define METATILE_GeneralHub_Tree_BottomLeft_Dense                  0x1E4
#define METATILE_GeneralHub_Tree_BottomLeft_Dense_Overlapped       0x1DC
#define METATILE_GeneralHub_Tree_BottomLeft_Dense_Overlapped_Alt   0x1F3
#define METATILE_GeneralHub_Tree_BottomLeft_Sparse                 0x1E6
#define METATILE_GeneralHub_Tree_BottomLeft_Sparse_Overlapped      0x1DE
#define METATILE_GeneralHub_Tree_BottomRight_Dense                 0x1E5
#define METATILE_GeneralHub_Tree_BottomRight_Dense_Overlapped      0x1DD
#define METATILE_GeneralHub_Tree_BottomRight_Dense_Overlapped_Alt  0x1F2
#define METATILE_GeneralHub_Tree_BottomRight_Sparse                0x1E7
#define METATILE_GeneralHub_Tree_BottomRight_Sparse_Overlapped     0x1DF
#define METATILE_GeneralHub_Tree_TopLeft_CapGrass                  0x1CE
#define METATILE_GeneralHub_Tree_TopLeft_CapTallGrass              0x1C6
#define METATILE_GeneralHub_Tree_TopLeft_Dense                     0x1D4
#define METATILE_GeneralHub_Tree_TopLeft_Sparse                    0x1D6
#define METATILE_GeneralHub_Tree_TopRight_CapGrass                 0x1CF
#define METATILE_GeneralHub_Tree_TopRight_CapTallGrass             0x1C7
#define METATILE_GeneralHub_Tree_TopRight_Dense                    0x1D5
#define METATILE_GeneralHub_Tree_TopRight_Sparse                   0x1D7

// gTileset_GenericBuilding
#define METATILE_GenericBuilding_TableEdge               0x2F1
#define METATILE_GenericBuilding_TrickHouse_Door_Closed  0x21B
#define METATILE_GenericBuilding_TrickHouse_Stairs_Down  0x219

// gTileset_HubArchitecture
#define METATILE_HubArchitecture_LabJunction_ComputerBench_0_0   0x03B
#define METATILE_HubArchitecture_LabJunction_ComputerBench_0_1   0x03D
#define METATILE_HubArchitecture_LabJunction_ComputerBench_1_0   0x03C
#define METATILE_HubArchitecture_LabJunction_ComputerBench_1_1   0x03E
#define METATILE_HubArchitecture_LabJunction_Door                0x03A
#define METATILE_HubArchitecture_LabJunction_FloorFadeNorth      0x03F
#define METATILE_HubArchitecture_LabJunction_WarpNorth           0x040
#define METATILE_HubArchitecture_LabJunction_WarpSouth           0x041
#define METATILE_HubArchitecture_MainHall_InlayE                 0x079
#define METATILE_HubArchitecture_MainHall_InlayN                 0x076
#define METATILE_HubArchitecture_MainHall_InlayNE                0x07B
#define METATILE_HubArchitecture_MainHall_InlayNW                0x07A
#define METATILE_HubArchitecture_MainHall_InlayS                 0x077
#define METATILE_HubArchitecture_MainHall_InlaySE                0x07D
#define METATILE_HubArchitecture_MainHall_InlaySW                0x07C
#define METATILE_HubArchitecture_MainHall_InlayW                 0x078
#define METATILE_HubArchitecture_MainHall_Monitor_0_0            0x071
#define METATILE_HubArchitecture_MainHall_Monitor_0_1            0x072
#define METATILE_HubArchitecture_MainHall_Plant_0_0              0x06F
#define METATILE_HubArchitecture_MainHall_Plant_0_1              0x070
#define METATILE_HubArchitecture_MainHall_Plaque                 0x081
#define METATILE_HubArchitecture_MainHall_PlinthCenter           0x07F
#define METATILE_HubArchitecture_MainHall_PlinthLeft             0x07E
#define METATILE_HubArchitecture_MainHall_PlinthRight            0x080
#define METATILE_HubArchitecture_MainHall_PlinthTopCenter        0x083
#define METATILE_HubArchitecture_MainHall_PlinthTopLeft          0x082
#define METATILE_HubArchitecture_MainHall_PlinthTopRight         0x084
#define METATILE_HubArchitecture_MainHall_Sofa_0_0               0x069
#define METATILE_HubArchitecture_MainHall_Sofa_0_1               0x06C
#define METATILE_HubArchitecture_MainHall_Sofa_1_0               0x06A
#define METATILE_HubArchitecture_MainHall_Sofa_1_1               0x06D
#define METATILE_HubArchitecture_MainHall_Sofa_2_0               0x06B
#define METATILE_HubArchitecture_MainHall_Sofa_2_1               0x06E
#define METATILE_HubArchitecture_MainHall_StairLeft              0x074
#define METATILE_HubArchitecture_MainHall_StairRight             0x075
#define METATILE_HubArchitecture_MainHall_StandReference         0x073
#define METATILE_HubArchitecture_PortalRoom_ConsoleMarkLeft      0x023
#define METATILE_HubArchitecture_PortalRoom_ConsoleMarkRight     0x024
#define METATILE_HubArchitecture_PortalRoom_ControlBase          0x022
#define METATILE_HubArchitecture_PortalRoom_ControlTop           0x02F
#define METATILE_HubArchitecture_PortalRoom_Decor_Cargo_0_0      0x035
#define METATILE_HubArchitecture_PortalRoom_Decor_Cargo_0_2      0x037
#define METATILE_HubArchitecture_PortalRoom_Decor_Cargo_1_0      0x036
#define METATILE_HubArchitecture_PortalRoom_Decor_Cargo_1_2      0x038
#define METATILE_HubArchitecture_PortalRoom_Decor_Stool_0_0      0x034
#define METATILE_HubArchitecture_PortalRoom_Decor_Table_0_0      0x030
#define METATILE_HubArchitecture_PortalRoom_Decor_Table_0_1      0x032
#define METATILE_HubArchitecture_PortalRoom_Decor_Table_1_0      0x031
#define METATILE_HubArchitecture_PortalRoom_Decor_Table_1_1      0x033
#define METATILE_HubArchitecture_PortalRoom_Floor                0x000
#define METATILE_HubArchitecture_PortalRoom_FloorDeepSouth       0x02E
#define METATILE_HubArchitecture_PortalRoom_FloorDim20           0x028
#define METATILE_HubArchitecture_PortalRoom_FloorDim40           0x027
#define METATILE_HubArchitecture_PortalRoom_FloorFadeEast        0x026
#define METATILE_HubArchitecture_PortalRoom_FloorFadeSouth       0x02D
#define METATILE_HubArchitecture_PortalRoom_FloorFadeWest        0x025
#define METATILE_HubArchitecture_PortalRoom_FloorShadow          0x001
#define METATILE_HubArchitecture_PortalRoom_FloorShadowDim20     0x02C
#define METATILE_HubArchitecture_PortalRoom_FloorShadowDim40     0x02B
#define METATILE_HubArchitecture_PortalRoom_FloorShadowFadeEast  0x02A
#define METATILE_HubArchitecture_PortalRoom_FloorShadowFadeWest  0x029
#define METATILE_HubArchitecture_PortalRoom_FrameLeft            0x010
#define METATILE_HubArchitecture_PortalRoom_FrameRight           0x011
#define METATILE_HubArchitecture_PortalRoom_FrameTop             0x00E
#define METATILE_HubArchitecture_PortalRoom_FrameTopLeft         0x00D
#define METATILE_HubArchitecture_PortalRoom_FrameTopRight        0x00F
#define METATILE_HubArchitecture_PortalRoom_HQ_21B               0x01E
#define METATILE_HubArchitecture_PortalRoom_HQ_223               0x01F
#define METATILE_HubArchitecture_PortalRoom_HQ_280               0x018
#define METATILE_HubArchitecture_PortalRoom_HQ_281               0x019
#define METATILE_HubArchitecture_PortalRoom_HQ_288               0x01A
#define METATILE_HubArchitecture_PortalRoom_HQ_289               0x01B
#define METATILE_HubArchitecture_PortalRoom_HQ_290               0x01C
#define METATILE_HubArchitecture_PortalRoom_HQ_291               0x01D
#define METATILE_HubArchitecture_PortalRoom_HQ_2B8               0x020
#define METATILE_HubArchitecture_PortalRoom_HQ_375               0x021
#define METATILE_HubArchitecture_PortalRoom_InnerBase            0x00B
#define METATILE_HubArchitecture_PortalRoom_InnerFoot            0x00C
#define METATILE_HubArchitecture_PortalRoom_InnerJoin            0x00A
#define METATILE_HubArchitecture_PortalRoom_Pillar               0x005
#define METATILE_HubArchitecture_PortalRoom_PillarCap            0x003
#define METATILE_HubArchitecture_PortalRoom_PillarEnd            0x006
#define METATILE_HubArchitecture_PortalRoom_PillarJoin           0x004
#define METATILE_HubArchitecture_PortalRoom_PillarStart          0x007
#define METATILE_HubArchitecture_PortalRoom_Shutter              0x012
#define METATILE_HubArchitecture_PortalRoom_Void                 0x002
#define METATILE_HubArchitecture_PortalRoom_Wall                 0x008
#define METATILE_HubArchitecture_PortalRoom_WallBase             0x009
#define METATILE_HubArchitecture_PortalRoom_WarpEast             0x014
#define METATILE_HubArchitecture_PortalRoom_WarpEastUpper        0x017
#define METATILE_HubArchitecture_PortalRoom_WarpSouth            0x015
#define METATILE_HubArchitecture_PortalRoom_WarpWest             0x013
#define METATILE_HubArchitecture_PortalRoom_WarpWestUpper        0x016
#define METATILE_HubArchitecture_SafariLab_BrokenHabitat_2       0x066
#define METATILE_HubArchitecture_SafariLab_Capsule_0_0           0x05B
#define METATILE_HubArchitecture_SafariLab_Capsule_0_1           0x05E
#define METATILE_HubArchitecture_SafariLab_Capsule_0_2           0x061
#define METATILE_HubArchitecture_SafariLab_Capsule_0_3           0x063
#define METATILE_HubArchitecture_SafariLab_Capsule_1_0           0x05C
#define METATILE_HubArchitecture_SafariLab_Capsule_1_1           0x05F
#define METATILE_HubArchitecture_SafariLab_Capsule_1_3           0x064
#define METATILE_HubArchitecture_SafariLab_Capsule_2_0           0x05D
#define METATILE_HubArchitecture_SafariLab_Capsule_2_1           0x060
#define METATILE_HubArchitecture_SafariLab_Capsule_2_2           0x062
#define METATILE_HubArchitecture_SafariLab_Capsule_2_3           0x065
#define METATILE_HubArchitecture_SafariLab_CaveDoor              0x04B
#define METATILE_HubArchitecture_SafariLab_CaveTop               0x04A
#define METATILE_HubArchitecture_SafariLab_FloorShadowSouth      0x068
#define METATILE_HubArchitecture_SafariLab_Habitat_0_0           0x04C
#define METATILE_HubArchitecture_SafariLab_Habitat_0_1           0x051
#define METATILE_HubArchitecture_SafariLab_Habitat_0_3           0x056
#define METATILE_HubArchitecture_SafariLab_Habitat_0_4           0x058
#define METATILE_HubArchitecture_SafariLab_Habitat_1_0           0x04D
#define METATILE_HubArchitecture_SafariLab_Habitat_1_1           0x052
#define METATILE_HubArchitecture_SafariLab_Habitat_1_4           0x059
#define METATILE_HubArchitecture_SafariLab_Habitat_2_0           0x04E
#define METATILE_HubArchitecture_SafariLab_Habitat_2_1           0x053
#define METATILE_HubArchitecture_SafariLab_Habitat_4_0           0x04F
#define METATILE_HubArchitecture_SafariLab_Habitat_4_1           0x054
#define METATILE_HubArchitecture_SafariLab_Habitat_5_0           0x050
#define METATILE_HubArchitecture_SafariLab_Habitat_5_1           0x055
#define METATILE_HubArchitecture_SafariLab_Habitat_5_3           0x057
#define METATILE_HubArchitecture_SafariLab_Habitat_5_4           0x05A
#define METATILE_HubArchitecture_SafariLab_Rock_0_0              0x042
#define METATILE_HubArchitecture_SafariLab_Rock_0_2              0x043
#define METATILE_HubArchitecture_SafariLab_Rock_2_2              0x044
#define METATILE_HubArchitecture_SafariLab_Rock_2_3              0x046
#define METATILE_HubArchitecture_SafariLab_Rock_3_3              0x047
#define METATILE_HubArchitecture_SafariLab_Rock_3_4              0x049
#define METATILE_HubArchitecture_SafariLab_Rock_4_2              0x045
#define METATILE_HubArchitecture_SafariLab_Rock_4_3              0x048
#define METATILE_HubArchitecture_SafariLab_Warning               0x067
#define METATILE_HubArchitecture_WallPanelBase                   0x039

// gTileset_HubFurnishings
#define METATILE_HubFurnishings_DoorSignBase        0x33D
#define METATILE_HubFurnishings_DoorSignTop         0x33C
#define METATILE_HubFurnishings_Factory_0AF         0x2FB
#define METATILE_HubFurnishings_Factory_0CF         0x2FC
#define METATILE_HubFurnishings_Factory_22B         0x2FD
#define METATILE_HubFurnishings_Factory_22C         0x2FE
#define METATILE_HubFurnishings_Factory_22D         0x2FF
#define METATILE_HubFurnishings_Factory_22E         0x300
#define METATILE_HubFurnishings_Factory_233         0x301
#define METATILE_HubFurnishings_Factory_234         0x302
#define METATILE_HubFurnishings_Factory_235         0x303
#define METATILE_HubFurnishings_Factory_236         0x304
#define METATILE_HubFurnishings_Factory_23A         0x305
#define METATILE_HubFurnishings_Factory_23B         0x306
#define METATILE_HubFurnishings_Factory_23C         0x307
#define METATILE_HubFurnishings_Factory_23D         0x308
#define METATILE_HubFurnishings_Factory_23E         0x309
#define METATILE_HubFurnishings_Factory_243         0x30A
#define METATILE_HubFurnishings_Factory_244         0x30B
#define METATILE_HubFurnishings_Factory_245         0x30C
#define METATILE_HubFurnishings_Factory_246         0x30D
#define METATILE_HubFurnishings_Factory_24B         0x30E
#define METATILE_HubFurnishings_Factory_24C         0x30F
#define METATILE_HubFurnishings_Factory_24D         0x310
#define METATILE_HubFurnishings_Factory_24E         0x311
#define METATILE_HubFurnishings_Factory_255         0x312
#define METATILE_HubFurnishings_Factory_256         0x313
#define METATILE_HubFurnishings_Factory_28D         0x314
#define METATILE_HubFurnishings_Factory_2AE         0x315
#define METATILE_HubFurnishings_Factory_2AF         0x316
#define METATILE_HubFurnishings_Factory_308         0x317
#define METATILE_HubFurnishings_Factory_309         0x318
#define METATILE_HubFurnishings_Factory_30A         0x319
#define METATILE_HubFurnishings_Factory_310         0x31A
#define METATILE_HubFurnishings_Factory_311         0x31B
#define METATILE_HubFurnishings_Factory_312         0x31C
#define METATILE_HubFurnishings_Factory_318         0x31D
#define METATILE_HubFurnishings_Factory_319         0x31E
#define METATILE_HubFurnishings_Factory_31A         0x31F
#define METATILE_HubFurnishings_Factory_320         0x320
#define METATILE_HubFurnishings_Factory_322         0x321
#define METATILE_HubFurnishings_Factory_380         0x322
#define METATILE_HubFurnishings_Factory_381         0x323
#define METATILE_HubFurnishings_Factory_382         0x324
#define METATILE_HubFurnishings_Factory_383         0x325
#define METATILE_HubFurnishings_Factory_386         0x326
#define METATILE_HubFurnishings_Factory_387         0x327
#define METATILE_HubFurnishings_Factory_38E         0x328
#define METATILE_HubFurnishings_Factory_38F         0x329
#define METATILE_HubFurnishings_Factory_396         0x32A
#define METATILE_HubFurnishings_Factory_397         0x32B
#define METATILE_HubFurnishings_Factory_3A2         0x32C
#define METATILE_HubFurnishings_Factory_3AA         0x32D
#define METATILE_HubFurnishings_Factory_3AB         0x32E
#define METATILE_HubFurnishings_Factory_3AC         0x32F
#define METATILE_HubFurnishings_Galactic_282        0x29D
#define METATILE_HubFurnishings_Galactic_283        0x29E
#define METATILE_HubFurnishings_Galactic_28A        0x29F
#define METATILE_HubFurnishings_Galactic_2B9        0x2A0
#define METATILE_HubFurnishings_Galactic_2BB        0x2A1
#define METATILE_HubFurnishings_Galactic_2BC        0x2A2
#define METATILE_HubFurnishings_Galactic_2BD        0x2A3
#define METATILE_HubFurnishings_Galactic_2DE        0x2A4
#define METATILE_HubFurnishings_Galactic_2DF        0x2A5
#define METATILE_HubFurnishings_Galactic_2FC        0x2A6
#define METATILE_HubFurnishings_Galactic_2FE        0x2A7
#define METATILE_HubFurnishings_Galactic_30C        0x2A8
#define METATILE_HubFurnishings_Galactic_30E        0x2A9
#define METATILE_HubFurnishings_Galactic_314        0x2AA
#define METATILE_HubFurnishings_Galactic_315        0x2AB
#define METATILE_HubFurnishings_Galactic_316        0x2AC
#define METATILE_HubFurnishings_Galactic_31C        0x2AD
#define METATILE_HubFurnishings_Galactic_31D        0x2AE
#define METATILE_HubFurnishings_Galactic_31E        0x2AF
#define METATILE_HubFurnishings_Galactic_32C        0x2B0
#define METATILE_HubFurnishings_Galactic_32D        0x2B1
#define METATILE_HubFurnishings_Galactic_32E        0x2B2
#define METATILE_HubFurnishings_Galactic_334        0x2B3
#define METATILE_HubFurnishings_Galactic_335        0x2B4
#define METATILE_HubFurnishings_Galactic_336        0x2B5
#define METATILE_HubFurnishings_Galactic_339        0x2B6
#define METATILE_HubFurnishings_Galactic_33A        0x2B7
#define METATILE_HubFurnishings_Galactic_33B        0x2B8
#define METATILE_HubFurnishings_Galactic_33C        0x2B9
#define METATILE_HubFurnishings_Galactic_33D        0x2BA
#define METATILE_HubFurnishings_Galactic_33E        0x2BB
#define METATILE_HubFurnishings_Galactic_361        0x2BC
#define METATILE_HubFurnishings_Galactic_368        0x2BD
#define METATILE_HubFurnishings_Galactic_369        0x2BE
#define METATILE_HubFurnishings_Galactic_370        0x2BF
#define METATILE_HubFurnishings_Galactic_371        0x2C0
#define METATILE_HubFurnishings_Galactic_376        0x2C1
#define METATILE_HubFurnishings_Galactic_3D8        0x2C2
#define METATILE_HubFurnishings_Galactic_3D9        0x2C3
#define METATILE_HubFurnishings_Galactic_3DA        0x2C4
#define METATILE_HubFurnishings_Galactic_3DB        0x2C5
#define METATILE_HubFurnishings_Galactic_3DC        0x2C6
#define METATILE_HubFurnishings_Galactic_3DD        0x2C7
#define METATILE_HubFurnishings_Lab_200             0x200
#define METATILE_HubFurnishings_Lab_202             0x201
#define METATILE_HubFurnishings_Lab_203             0x202
#define METATILE_HubFurnishings_Lab_204             0x203
#define METATILE_HubFurnishings_Lab_205             0x204
#define METATILE_HubFurnishings_Lab_206             0x205
#define METATILE_HubFurnishings_Lab_207             0x206
#define METATILE_HubFurnishings_Lab_208             0x207
#define METATILE_HubFurnishings_Lab_209             0x208
#define METATILE_HubFurnishings_Lab_20A             0x209
#define METATILE_HubFurnishings_Lab_20B             0x20A
#define METATILE_HubFurnishings_Lab_20C             0x20B
#define METATILE_HubFurnishings_Lab_20D             0x20C
#define METATILE_HubFurnishings_Lab_20E             0x20D
#define METATILE_HubFurnishings_Lab_20F             0x20E
#define METATILE_HubFurnishings_Lab_210             0x20F
#define METATILE_HubFurnishings_Lab_211             0x210
#define METATILE_HubFurnishings_Lab_212             0x211
#define METATILE_HubFurnishings_Lab_213             0x212
#define METATILE_HubFurnishings_Lab_214             0x213
#define METATILE_HubFurnishings_Lab_215             0x214
#define METATILE_HubFurnishings_Lab_216             0x215
#define METATILE_HubFurnishings_Lab_217             0x216
#define METATILE_HubFurnishings_Lab_218             0x217
#define METATILE_HubFurnishings_Lab_219             0x218
#define METATILE_HubFurnishings_Lab_21A             0x219
#define METATILE_HubFurnishings_Lab_21B             0x21A
#define METATILE_HubFurnishings_Lab_21C             0x21B
#define METATILE_HubFurnishings_Lab_21D             0x21C
#define METATILE_HubFurnishings_Lab_21E             0x21D
#define METATILE_HubFurnishings_Lab_21F             0x21E
#define METATILE_HubFurnishings_Lab_220             0x21F
#define METATILE_HubFurnishings_Lab_221             0x220
#define METATILE_HubFurnishings_Lab_222             0x221
#define METATILE_HubFurnishings_Lab_223             0x222
#define METATILE_HubFurnishings_Lab_224             0x223
#define METATILE_HubFurnishings_Lab_225             0x224
#define METATILE_HubFurnishings_Lab_226             0x225
#define METATILE_HubFurnishings_Lab_227             0x226
#define METATILE_HubFurnishings_Lab_228             0x227
#define METATILE_HubFurnishings_Lab_229             0x228
#define METATILE_HubFurnishings_Lab_22A             0x229
#define METATILE_HubFurnishings_Lab_22C             0x22A
#define METATILE_HubFurnishings_Lab_22D             0x22B
#define METATILE_HubFurnishings_Lab_22E             0x22C
#define METATILE_HubFurnishings_Lab_22F             0x22D
#define METATILE_HubFurnishings_Lab_230             0x22E
#define METATILE_HubFurnishings_Lab_231             0x22F
#define METATILE_HubFurnishings_Lab_232             0x230
#define METATILE_HubFurnishings_Lab_234             0x231
#define METATILE_HubFurnishings_Lab_235             0x232
#define METATILE_HubFurnishings_Lab_236             0x233
#define METATILE_HubFurnishings_Lab_238             0x234
#define METATILE_HubFurnishings_Lab_239             0x235
#define METATILE_HubFurnishings_Lab_23A             0x236
#define METATILE_HubFurnishings_Lab_23B             0x237
#define METATILE_HubFurnishings_Lab_23C             0x238
#define METATILE_HubFurnishings_Lab_23D             0x239
#define METATILE_HubFurnishings_Lab_23E             0x23A
#define METATILE_HubFurnishings_Lab_23F             0x23B
#define METATILE_HubFurnishings_Lab_240             0x23C
#define METATILE_HubFurnishings_Lab_241             0x23D
#define METATILE_HubFurnishings_Lab_242             0x23E
#define METATILE_HubFurnishings_Lab_243             0x23F
#define METATILE_HubFurnishings_Lab_244             0x240
#define METATILE_HubFurnishings_Lab_245             0x241
#define METATILE_HubFurnishings_Lab_246             0x242
#define METATILE_HubFurnishings_Lab_247             0x243
#define METATILE_HubFurnishings_Lab_248             0x244
#define METATILE_HubFurnishings_Lab_249             0x245
#define METATILE_HubFurnishings_Lab_24A             0x246
#define METATILE_HubFurnishings_Lab_24B             0x247
#define METATILE_HubFurnishings_Lab_24C             0x248
#define METATILE_HubFurnishings_Lab_24D             0x249
#define METATILE_HubFurnishings_Lab_24E             0x24A
#define METATILE_HubFurnishings_Lab_24F             0x24B
#define METATILE_HubFurnishings_Lab_252             0x24C
#define METATILE_HubFurnishings_Lab_253             0x24D
#define METATILE_HubFurnishings_Lab_254             0x24E
#define METATILE_HubFurnishings_Lab_255             0x24F
#define METATILE_HubFurnishings_Lab_256             0x250
#define METATILE_HubFurnishings_Lab_257             0x251
#define METATILE_HubFurnishings_Lab_258             0x252
#define METATILE_HubFurnishings_Lab_259             0x253
#define METATILE_HubFurnishings_Lab_25A             0x254
#define METATILE_HubFurnishings_Lab_25C             0x255
#define METATILE_HubFurnishings_Lab_25D             0x256
#define METATILE_HubFurnishings_Lab_25E             0x257
#define METATILE_HubFurnishings_Lab_25F             0x258
#define METATILE_HubFurnishings_Lab_260             0x259
#define METATILE_HubFurnishings_Lab_261             0x25A
#define METATILE_HubFurnishings_Lab_262             0x25B
#define METATILE_HubFurnishings_Lab_263             0x25C
#define METATILE_HubFurnishings_Lab_264             0x25D
#define METATILE_HubFurnishings_Lab_265             0x25E
#define METATILE_HubFurnishings_Lab_266             0x25F
#define METATILE_HubFurnishings_Lab_267             0x260
#define METATILE_HubFurnishings_Lab_268             0x261
#define METATILE_HubFurnishings_Lab_26A             0x262
#define METATILE_HubFurnishings_Lab_26B             0x263
#define METATILE_HubFurnishings_Lab_26C             0x264
#define METATILE_HubFurnishings_Lab_26D             0x265
#define METATILE_HubFurnishings_Lab_26E             0x266
#define METATILE_HubFurnishings_Lab_26F             0x267
#define METATILE_HubFurnishings_Lab_270             0x268
#define METATILE_HubFurnishings_Lab_271             0x269
#define METATILE_HubFurnishings_Lab_272             0x26A
#define METATILE_HubFurnishings_Lab_273             0x26B
#define METATILE_HubFurnishings_Lab_274             0x26C
#define METATILE_HubFurnishings_Lab_275             0x26D
#define METATILE_HubFurnishings_Lab_276             0x26E
#define METATILE_HubFurnishings_Lab_277             0x26F
#define METATILE_HubFurnishings_Lab_278             0x270
#define METATILE_HubFurnishings_Lab_279             0x271
#define METATILE_HubFurnishings_Lab_27A             0x272
#define METATILE_HubFurnishings_Lab_27B             0x273
#define METATILE_HubFurnishings_Lab_27C             0x274
#define METATILE_HubFurnishings_Lab_27D             0x275
#define METATILE_HubFurnishings_Lab_27E             0x276
#define METATILE_HubFurnishings_Lab_27F             0x277
#define METATILE_HubFurnishings_Lab_281             0x278
#define METATILE_HubFurnishings_Lab_282             0x279
#define METATILE_HubFurnishings_Lab_283             0x27A
#define METATILE_HubFurnishings_Lab_284             0x27B
#define METATILE_HubFurnishings_Lab_285             0x27C
#define METATILE_HubFurnishings_Lab_286             0x27D
#define METATILE_HubFurnishings_Lab_287             0x27E
#define METATILE_HubFurnishings_Lab_288             0x27F
#define METATILE_HubFurnishings_Lab_289             0x280
#define METATILE_HubFurnishings_Lab_28A             0x281
#define METATILE_HubFurnishings_Lab_28B             0x282
#define METATILE_HubFurnishings_Lab_28C             0x283
#define METATILE_HubFurnishings_Lab_28D             0x284
#define METATILE_HubFurnishings_Lab_28E             0x285
#define METATILE_HubFurnishings_Lab_28F             0x286
#define METATILE_HubFurnishings_Lab_290             0x287
#define METATILE_HubFurnishings_Lab_291             0x288
#define METATILE_HubFurnishings_Lab_292             0x289
#define METATILE_HubFurnishings_Lab_293             0x28A
#define METATILE_HubFurnishings_Lab_294             0x28B
#define METATILE_HubFurnishings_Lab_295             0x28C
#define METATILE_HubFurnishings_Lab_296             0x28D
#define METATILE_HubFurnishings_Lab_297             0x28E
#define METATILE_HubFurnishings_Lab_298             0x28F
#define METATILE_HubFurnishings_Lab_299             0x290
#define METATILE_HubFurnishings_Lab_29A             0x291
#define METATILE_HubFurnishings_Lab_29B             0x292
#define METATILE_HubFurnishings_Lab_29C             0x293
#define METATILE_HubFurnishings_Lab_29D             0x294
#define METATILE_HubFurnishings_Lab_29E             0x295
#define METATILE_HubFurnishings_Lab_29F             0x296
#define METATILE_HubFurnishings_Lab_2A0             0x297
#define METATILE_HubFurnishings_Lab_2A1             0x298
#define METATILE_HubFurnishings_Lab_2A2             0x299
#define METATILE_HubFurnishings_Lab_2A4             0x29A
#define METATILE_HubFurnishings_Lab_2A5             0x29B
#define METATILE_HubFurnishings_PortalRoom_Opening  0x330
#define METATILE_HubFurnishings_Rocket_213          0x2C8
#define METATILE_HubFurnishings_Rocket_228          0x2C9
#define METATILE_HubFurnishings_Rocket_229          0x2CA
#define METATILE_HubFurnishings_Rocket_22A          0x2CB
#define METATILE_HubFurnishings_Rocket_2A7          0x2CC
#define METATILE_HubFurnishings_Rocket_2BA          0x2CD
#define METATILE_HubFurnishings_Rocket_2C0          0x2CE
#define METATILE_HubFurnishings_Rocket_2C1          0x2CF
#define METATILE_HubFurnishings_Rocket_2C2          0x2D0
#define METATILE_HubFurnishings_Rocket_2E8          0x2D1
#define METATILE_HubFurnishings_Rocket_2E9          0x2D2
#define METATILE_HubFurnishings_Rocket_2F0          0x2D3
#define METATILE_HubFurnishings_Rocket_2F1          0x2D4
#define METATILE_HubFurnishings_Rocket_2FC          0x2D5
#define METATILE_HubFurnishings_Rocket_2FD          0x2D6
#define METATILE_HubFurnishings_Rocket_2FE          0x2D7
#define METATILE_HubFurnishings_Rocket_2FF          0x2D8
#define METATILE_HubFurnishings_Rocket_304          0x2D9
#define METATILE_HubFurnishings_Rocket_305          0x2DA
#define METATILE_HubFurnishings_Rocket_306          0x2DB
#define METATILE_HubFurnishings_Rocket_307          0x2DC
#define METATILE_HubFurnishings_Rocket_30C          0x2DD
#define METATILE_HubFurnishings_Rocket_30D          0x2DE
#define METATILE_HubFurnishings_Rocket_30E          0x2DF
#define METATILE_HubFurnishings_Rocket_336          0x2E0
#define METATILE_HubFurnishings_Rocket_349          0x2E1
#define METATILE_HubFurnishings_Rocket_34A          0x2E2
#define METATILE_HubFurnishings_Rocket_34B          0x2E3
#define METATILE_HubFurnishings_Rocket_351          0x2E4
#define METATILE_HubFurnishings_Rocket_352          0x2E5
#define METATILE_HubFurnishings_Rocket_353          0x2E6
#define METATILE_HubFurnishings_Rocket_3B8          0x2E7
#define METATILE_HubFurnishings_Rocket_3B9          0x2E8
#define METATILE_HubFurnishings_Rocket_3BA          0x2E9
#define METATILE_HubFurnishings_Rocket_3BB          0x2EA
#define METATILE_HubFurnishings_Rocket_3BC          0x2EB
#define METATILE_HubFurnishings_Rocket_3BD          0x2EC
#define METATILE_HubFurnishings_Rocket_3BE          0x2ED
#define METATILE_HubFurnishings_Rocket_3BF          0x2EE
#define METATILE_HubFurnishings_Rocket_3C0          0x2EF
#define METATILE_HubFurnishings_Rocket_3C1          0x2F0
#define METATILE_HubFurnishings_Rocket_3C2          0x2F1
#define METATILE_HubFurnishings_Rocket_3C3          0x2F2
#define METATILE_HubFurnishings_Rocket_3C4          0x2F3
#define METATILE_HubFurnishings_Rocket_3C5          0x2F4
#define METATILE_HubFurnishings_Rocket_3C6          0x2F5
#define METATILE_HubFurnishings_Rocket_3D8          0x2F6
#define METATILE_HubFurnishings_Rocket_3D9          0x2F7
#define METATILE_HubFurnishings_Rocket_3DC          0x2F8
#define METATILE_HubFurnishings_Rocket_3DD          0x2F9
#define METATILE_HubFurnishings_Rocket_3FA          0x2FA
#define METATILE_HubFurnishings_SofaWallTop_0       0x339
#define METATILE_HubFurnishings_SofaWallTop_1       0x33A
#define METATILE_HubFurnishings_SofaWallTop_2       0x33B
#define METATILE_HubFurnishings_WallPanelTop        0x29C

// gTileset_InsideOfTruck
#define METATILE_InsideOfTruck_DoorClosedFloor_Bottom  0x21D
#define METATILE_InsideOfTruck_DoorClosedFloor_Mid     0x215
#define METATILE_InsideOfTruck_DoorClosedFloor_Top     0x20D
#define METATILE_InsideOfTruck_ExitLight_Bottom        0x218
#define METATILE_InsideOfTruck_ExitLight_Mid           0x210
#define METATILE_InsideOfTruck_ExitLight_Top           0x208

// gTileset_InsideShip
#define METATILE_InsideShip_DoorIndent_Locked           0x234
#define METATILE_InsideShip_DoorIndent_Unlocked         0x21A
#define METATILE_InsideShip_IntactDoor_Bottom_Interior  0x297
#define METATILE_InsideShip_IntactDoor_Bottom_Locked    0x233
#define METATILE_InsideShip_IntactDoor_Bottom_Unlocked  0x22B

// gTileset_Lavaridge
#define METATILE_Lavaridge_AshGrass             0x207
#define METATILE_Lavaridge_CaveEntrance_Bottom  0x25E
#define METATILE_Lavaridge_CaveEntrance_Top     0x256
#define METATILE_Lavaridge_LavaField            0x271
#define METATILE_Lavaridge_NormalGrass          0x206
#define METATILE_Lavaridge_RockWall             0x274

// gTileset_Lilycove
#define METATILE_Lilycove_Door             0x246
#define METATILE_Lilycove_Door_DeptStore   0x30C
#define METATILE_Lilycove_Door_SafariZone  0x32D
#define METATILE_Lilycove_Door_Wooden      0x28E
#define METATILE_Lilycove_Wailmer0         0x290
#define METATILE_Lilycove_Wailmer0_Alt     0x298
#define METATILE_Lilycove_Wailmer1         0x291
#define METATILE_Lilycove_Wailmer1_Alt     0x299
#define METATILE_Lilycove_Wailmer2         0x2A0
#define METATILE_Lilycove_Wailmer3         0x2A1

// gTileset_LilycoveMuseum
#define METATILE_LilycoveMuseum_Painting0_Left   0x25A
#define METATILE_LilycoveMuseum_Painting0_Right  0x25B
#define METATILE_LilycoveMuseum_Painting1_Left   0x25C
#define METATILE_LilycoveMuseum_Painting1_Right  0x25D
#define METATILE_LilycoveMuseum_Painting2_Left   0x25E
#define METATILE_LilycoveMuseum_Painting2_Right  0x25F
#define METATILE_LilycoveMuseum_Painting3_Left   0x260
#define METATILE_LilycoveMuseum_Painting3_Right  0x261
#define METATILE_LilycoveMuseum_Painting4_Left   0x262
#define METATILE_LilycoveMuseum_Painting4_Right  0x263

// gTileset_Mauville
#define METATILE_Mauville_DeepSand_BottomMid   0x259
#define METATILE_Mauville_DeepSand_Center      0x251
#define METATILE_Mauville_Door                 0x2AC
#define METATILE_Mauville_DoorTop_CyclingRoad  0x281
#define METATILE_Mauville_Door_BattleTent      0x3D4
#define METATILE_Mauville_Door_CyclingRoad     0x289
#define METATILE_Mauville_Door_Verdanturf      0x3A1
#define METATILE_Mauville_MirageTower_Tile0    0x3D8
#define METATILE_Mauville_MirageTower_Tile1    0x3D9
#define METATILE_Mauville_MirageTower_Tile10   0x3E4
#define METATILE_Mauville_MirageTower_Tile11   0x3E5
#define METATILE_Mauville_MirageTower_Tile2    0x3DA
#define METATILE_Mauville_MirageTower_Tile3    0x3E0
#define METATILE_Mauville_MirageTower_Tile4    0x3E1
#define METATILE_Mauville_MirageTower_Tile5    0x3E2
#define METATILE_Mauville_MirageTower_Tile6    0x3E8
#define METATILE_Mauville_MirageTower_Tile7    0x3E9
#define METATILE_Mauville_MirageTower_Tile8    0x3EA
#define METATILE_Mauville_MirageTower_Tile9    0x3F0
#define METATILE_Mauville_MirageTower_TileA    0x3F1
#define METATILE_Mauville_MirageTower_TileB    0x3F2
#define METATILE_Mauville_MirageTower_TileC    0x3DB
#define METATILE_Mauville_MirageTower_TileD    0x3DC
#define METATILE_Mauville_MirageTower_TileE    0x3DD
#define METATILE_Mauville_MirageTower_TileF    0x3E3

// gTileset_MauvilleGym
#define METATILE_MauvilleGym_FloorTile        0x21A
#define METATILE_MauvilleGym_GreenBeamH1_Off  0x230
#define METATILE_MauvilleGym_GreenBeamH1_On   0x220
#define METATILE_MauvilleGym_GreenBeamH2_Off  0x231
#define METATILE_MauvilleGym_GreenBeamH2_On   0x221
#define METATILE_MauvilleGym_GreenBeamH3_Off  0x238
#define METATILE_MauvilleGym_GreenBeamH3_On   0x228
#define METATILE_MauvilleGym_GreenBeamH4_Off  0x239
#define METATILE_MauvilleGym_GreenBeamH4_On   0x229
#define METATILE_MauvilleGym_GreenBeamV1_On   0x240
#define METATILE_MauvilleGym_GreenBeamV2_On   0x248
#define METATILE_MauvilleGym_PoleBottom_Off   0x243
#define METATILE_MauvilleGym_PoleBottom_On    0x242
#define METATILE_MauvilleGym_PoleTop_Off      0x251
#define METATILE_MauvilleGym_PoleTop_On       0x250
#define METATILE_MauvilleGym_PressedSwitch    0x206
#define METATILE_MauvilleGym_RaisedSwitch     0x205
#define METATILE_MauvilleGym_RedBeamH1_Off    0x232
#define METATILE_MauvilleGym_RedBeamH1_On     0x222
#define METATILE_MauvilleGym_RedBeamH2_Off    0x233
#define METATILE_MauvilleGym_RedBeamH2_On     0x223
#define METATILE_MauvilleGym_RedBeamH3_Off    0x23A
#define METATILE_MauvilleGym_RedBeamH3_On     0x22A
#define METATILE_MauvilleGym_RedBeamH4_Off    0x23B
#define METATILE_MauvilleGym_RedBeamH4_On     0x22B
#define METATILE_MauvilleGym_RedBeamV1_On     0x241
#define METATILE_MauvilleGym_RedBeamV2_On     0x249

// gTileset_MeteorFalls
#define METATILE_MeteorFalls_CaveEntrance_Bottom  0x24E
#define METATILE_MeteorFalls_CaveEntrance_Left    0x24D
#define METATILE_MeteorFalls_CaveEntrance_Right   0x24F
#define METATILE_MeteorFalls_CaveEntrance_Top     0x246

// gTileset_Mossdeep
#define METATILE_Mossdeep_Door              0x2A1
#define METATILE_Mossdeep_Door_SpaceCenter  0x2ED

// gTileset_MossdeepGameCorner
#define METATILE_MossdeepGameCorner_CounterClosed_Bottom  0x232
#define METATILE_MossdeepGameCorner_CounterClosed_Top     0x22A
#define METATILE_MossdeepGameCorner_CounterOpen_Bottom    0x234
#define METATILE_MossdeepGameCorner_CounterOpen_Top       0x22C

// gTileset_MossdeepGym
#define METATILE_MossdeepGym_YellowArrow_Right  0x250

// gTileset_Pacifidlog
#define METATILE_Pacifidlog_Door                               0x21A
#define METATILE_Pacifidlog_FloatingLogs_HorizontalLeft        0x250
#define METATILE_Pacifidlog_FloatingLogs_HorizontalRight       0x251
#define METATILE_Pacifidlog_FloatingLogs_VerticalBottom        0x260
#define METATILE_Pacifidlog_FloatingLogs_VerticalTop           0x258
#define METATILE_Pacifidlog_HalfSubmergedLogs_HorizontalLeft   0x252
#define METATILE_Pacifidlog_HalfSubmergedLogs_HorizontalRight  0x253
#define METATILE_Pacifidlog_HalfSubmergedLogs_VerticalBottom   0x261
#define METATILE_Pacifidlog_HalfSubmergedLogs_VerticalTop      0x259
#define METATILE_Pacifidlog_SkyPillar_CrackedFloor_Hole        0x237
#define METATILE_Pacifidlog_SkyPillar_DoorOpen_Bottom          0x2B2
#define METATILE_Pacifidlog_SkyPillar_DoorOpen_Top             0x2AA
#define METATILE_Pacifidlog_SubmergedLogs_HorizontalLeft       0x254
#define METATILE_Pacifidlog_SubmergedLogs_HorizontalRight      0x255
#define METATILE_Pacifidlog_SubmergedLogs_VerticalBottom       0x262
#define METATILE_Pacifidlog_SubmergedLogs_VerticalTop          0x25A

// gTileset_Petalburg
#define METATILE_Petalburg_Door_BirchsLab   0x249
#define METATILE_Petalburg_Door_Littleroot  0x248
#define METATILE_Petalburg_Door_Oldale      0x287

// gTileset_PetalburgGym
#define METATILE_PetalburgGym_Door                0x224
#define METATILE_PetalburgGym_RoomEntrance_Left   0x210
#define METATILE_PetalburgGym_RoomEntrance_Right  0x211
#define METATILE_PetalburgGym_SlidingDoor_Frame0  0x218
#define METATILE_PetalburgGym_SlidingDoor_Frame1  0x219
#define METATILE_PetalburgGym_SlidingDoor_Frame2  0x21A
#define METATILE_PetalburgGym_SlidingDoor_Frame3  0x21B
#define METATILE_PetalburgGym_SlidingDoor_Frame4  0x21C

// gTileset_PokemonCenter
#define METATILE_PokemonCenter_CounterBarrier            0x25D
#define METATILE_PokemonCenter_Door_CableClub            0x264
#define METATILE_PokemonCenter_Escalator1F_Tile0_Frame0  0x280
#define METATILE_PokemonCenter_Escalator1F_Tile0_Frame1  0x282
#define METATILE_PokemonCenter_Escalator1F_Tile0_Frame2  0x284
#define METATILE_PokemonCenter_Escalator1F_Tile1_Frame0  0x281
#define METATILE_PokemonCenter_Escalator1F_Tile1_Frame1  0x283
#define METATILE_PokemonCenter_Escalator1F_Tile1_Frame2  0x285
#define METATILE_PokemonCenter_Escalator1F_Tile2_Frame0  0x288
#define METATILE_PokemonCenter_Escalator1F_Tile2_Frame1  0x28A
#define METATILE_PokemonCenter_Escalator1F_Tile2_Frame2  0x28C
#define METATILE_PokemonCenter_Escalator1F_Tile3_Frame0  0x289
#define METATILE_PokemonCenter_Escalator1F_Tile3_Frame1  0x28B
#define METATILE_PokemonCenter_Escalator1F_Tile3_Frame2  0x28D
#define METATILE_PokemonCenter_Escalator2F_Tile0_Frame0  0x2A0
#define METATILE_PokemonCenter_Escalator2F_Tile0_Frame1  0x2A2
#define METATILE_PokemonCenter_Escalator2F_Tile0_Frame2  0x2A4
#define METATILE_PokemonCenter_Escalator2F_Tile1_Frame0  0x2A1
#define METATILE_PokemonCenter_Escalator2F_Tile1_Frame1  0x2A3
#define METATILE_PokemonCenter_Escalator2F_Tile1_Frame2  0x2A5
#define METATILE_PokemonCenter_Escalator2F_Tile2_Frame0  0x2A8
#define METATILE_PokemonCenter_Escalator2F_Tile2_Frame1  0x2AA
#define METATILE_PokemonCenter_Escalator2F_Tile2_Frame2  0x2AC
#define METATILE_PokemonCenter_Floor_Plain_Alt           0x2E4
#define METATILE_PokemonCenter_Floor_ShadowTop           0x21E
#define METATILE_PokemonCenter_Floor_ShadowTop_Alt       0x2DC

// gTileset_Restaurant
#define METATILE_Restaurant_KitchenDoorClosed  0x227
#define METATILE_Restaurant_KitchenDoorOpen    0x217

// gTileset_Rustboro
#define METATILE_Rustboro_Door_Gray  0x21F
#define METATILE_Rustboro_Door_Tan   0x22F

// gTileset_SecretBase
#define METATILE_SecretBase_AttractMat_BottomLeft       0x313
#define METATILE_SecretBase_AttractMat_BottomMid        0x314
#define METATILE_SecretBase_AttractMat_BottomRight      0x315
#define METATILE_SecretBase_AttractMat_Center           0x30C
#define METATILE_SecretBase_AttractMat_MidLeft          0x30B
#define METATILE_SecretBase_AttractMat_MidRight         0x30D
#define METATILE_SecretBase_AttractMat_TopLeft          0x303
#define METATILE_SecretBase_AttractMat_TopMid           0x304
#define METATILE_SecretBase_AttractMat_TopRight         0x305
#define METATILE_SecretBase_BallPoster                  0x330
#define METATILE_SecretBase_BigPlant_BaseLeft1          0x2EC
#define METATILE_SecretBase_BigPlant_BaseLeft2          0x2EE
#define METATILE_SecretBase_BigPlant_BaseRight1         0x2ED
#define METATILE_SecretBase_BigPlant_BaseRight2         0x2EF
#define METATILE_SecretBase_BigPlant_TopLeft            0x2E4
#define METATILE_SecretBase_BigPlant_TopLeftWall        0x2E5
#define METATILE_SecretBase_BigPlant_TopRightWall       0x2E6
#define METATILE_SecretBase_BlueBalloon                 0x33C
#define METATILE_SecretBase_BlueBrick_Bottom            0x22F
#define METATILE_SecretBase_BlueBrick_Top               0x227
#define METATILE_SecretBase_BluePoster                  0x333
#define METATILE_SecretBase_BlueTent_BottomLeft         0x258
#define METATILE_SecretBase_BlueTent_BottomRight        0x269
#define METATILE_SecretBase_BlueTent_Door               0x259
#define METATILE_SecretBase_BlueTent_DoorTop            0x251
#define METATILE_SecretBase_BlueTent_MidLeft            0x250
#define METATILE_SecretBase_BlueTent_MidRight           0x270
#define METATILE_SecretBase_BlueTent_TopLeft            0x248
#define METATILE_SecretBase_BlueTent_TopMid             0x249
#define METATILE_SecretBase_BlueTent_TopRight           0x268
#define METATILE_SecretBase_BreakableDoor_BottomClosed  0x23F
#define METATILE_SecretBase_BreakableDoor_BottomOpen    0x276
#define METATILE_SecretBase_BreakableDoor_TopClosed     0x237
#define METATILE_SecretBase_BreakableDoor_TopOpen       0x26E
#define METATILE_SecretBase_BrickChair                  0x2C8
#define METATILE_SecretBase_BrickDesk_BottomLeft        0x2B0
#define METATILE_SecretBase_BrickDesk_BottomMid         0x2B1
#define METATILE_SecretBase_BrickDesk_BottomRight       0x2B2
#define METATILE_SecretBase_BrickDesk_Center            0x2A9
#define METATILE_SecretBase_BrickDesk_MidLeft           0x2A8
#define METATILE_SecretBase_BrickDesk_MidRight          0x2AA
#define METATILE_SecretBase_BrickDesk_TopLeft           0x2A0
#define METATILE_SecretBase_BrickDesk_TopMid            0x2A1
#define METATILE_SecretBase_BrickDesk_TopRight          0x2A2
#define METATILE_SecretBase_CampChair                   0x2C9
#define METATILE_SecretBase_CampDesk_BottomLeft         0x2B4
#define METATILE_SecretBase_CampDesk_BottomMid          0x2B5
#define METATILE_SecretBase_CampDesk_BottomRight        0x2B6
#define METATILE_SecretBase_CampDesk_Center             0x2AD
#define METATILE_SecretBase_CampDesk_MidLeft            0x2AC
#define METATILE_SecretBase_CampDesk_MidRight           0x2AE
#define METATILE_SecretBase_CampDesk_TopLeft            0x2A4
#define METATILE_SecretBase_CampDesk_TopMid             0x2A5
#define METATILE_SecretBase_CampDesk_TopRight           0x2A6
#define METATILE_SecretBase_ColorfulPlant_BaseLeft1     0x2E8
#define METATILE_SecretBase_ColorfulPlant_BaseLeft2     0x2EA
#define METATILE_SecretBase_ColorfulPlant_BaseRight1    0x2E9
#define METATILE_SecretBase_ColorfulPlant_BaseRight2    0x2EB
#define METATILE_SecretBase_ColorfulPlant_TopLeft       0x2E0
#define METATILE_SecretBase_ColorfulPlant_TopLeftWall   0x2E1
#define METATILE_SecretBase_ColorfulPlant_TopRight      0x2E2
#define METATILE_SecretBase_ColorfulPlant_TopRightWall  0x2E3
#define METATILE_SecretBase_ComfortChair                0x2C1
#define METATILE_SecretBase_ComfortDesk_BottomLeft      0x29E
#define METATILE_SecretBase_ComfortDesk_BottomMid       0x29F
#define METATILE_SecretBase_ComfortDesk_BottomRight     0x2AB
#define METATILE_SecretBase_ComfortDesk_TopLeft         0x296
#define METATILE_SecretBase_ComfortDesk_TopMid          0x297
#define METATILE_SecretBase_ComfortDesk_TopRight        0x2A3
#define METATILE_SecretBase_CutePoster                  0x334
#define METATILE_SecretBase_CuteTV                      0x2F6
#define METATILE_SecretBase_Fence_Horizontal            0x22C
#define METATILE_SecretBase_Fence_Vertical              0x233
#define METATILE_SecretBase_FireBlastMat_BottomLeft     0x265
#define METATILE_SecretBase_FireBlastMat_BottomMid      0x266
#define METATILE_SecretBase_FireBlastMat_BottomRight    0x267
#define METATILE_SecretBase_FireBlastMat_Center         0x25E
#define METATILE_SecretBase_FireBlastMat_MidLeft        0x25D
#define METATILE_SecretBase_FireBlastMat_MidRight       0x25F
#define METATILE_SecretBase_FireBlastMat_TopLeft        0x25A
#define METATILE_SecretBase_FireBlastMat_TopMid         0x25B
#define METATILE_SecretBase_FireBlastMat_TopRight       0x25C
#define METATILE_SecretBase_FissureMat_BottomLeft       0x316
#define METATILE_SecretBase_FissureMat_BottomMid        0x317
#define METATILE_SecretBase_FissureMat_BottomRight      0x328
#define METATILE_SecretBase_FissureMat_Center           0x30F
#define METATILE_SecretBase_FissureMat_MidLeft          0x30E
#define METATILE_SecretBase_FissureMat_MidRight         0x320
#define METATILE_SecretBase_FissureMat_TopLeft          0x306
#define METATILE_SecretBase_FissureMat_TopMid           0x307
#define METATILE_SecretBase_FissureMat_TopRight         0x318
#define METATILE_SecretBase_GlassOrnament_Base1         0x28A
#define METATILE_SecretBase_GlassOrnament_Base2         0x28B
#define METATILE_SecretBase_GlassOrnament_Top           0x282
#define METATILE_SecretBase_GlassOrnament_TopWall       0x283
#define METATILE_SecretBase_GlitterMat                  0x260
#define METATILE_SecretBase_GoldShield_Base1            0x336
#define METATILE_SecretBase_GoldShield_Base2            0x337
#define METATILE_SecretBase_GoldShield_Top              0x32E
#define METATILE_SecretBase_GoldShield_TopWall          0x32F
#define METATILE_SecretBase_GorgeousPlant_BaseLeft1     0x2F8
#define METATILE_SecretBase_GorgeousPlant_BaseLeft2     0x2FA
#define METATILE_SecretBase_GorgeousPlant_BaseRight1    0x2F9
#define METATILE_SecretBase_GorgeousPlant_BaseRight2    0x2FB
#define METATILE_SecretBase_GorgeousPlant_TopLeft       0x2F0
#define METATILE_SecretBase_GorgeousPlant_TopLeftWall   0x2F1
#define METATILE_SecretBase_GorgeousPlant_TopRight      0x2F2
#define METATILE_SecretBase_GorgeousPlant_TopRightWall  0x2F3
#define METATILE_SecretBase_GreenPoster                 0x331
#define METATILE_SecretBase_Ground                      0x20A
#define METATILE_SecretBase_HardChair                   0x2CA
#define METATILE_SecretBase_HardDesk_BottomLeft         0x2B7
#define METATILE_SecretBase_HardDesk_BottomMid          0x2CB
#define METATILE_SecretBase_HardDesk_BottomRight        0x2CC
#define METATILE_SecretBase_HardDesk_Center             0x2C3
#define METATILE_SecretBase_HardDesk_MidLeft            0x2AF
#define METATILE_SecretBase_HardDesk_MidRight           0x2C4
#define METATILE_SecretBase_HardDesk_TopLeft            0x2A7
#define METATILE_SecretBase_HardDesk_TopMid             0x2BB
#define METATILE_SecretBase_HardDesk_TopRight           0x2BC
#define METATILE_SecretBase_HeavyChair                  0x2BA
#define METATILE_SecretBase_HeavyDesk_BottomLeft        0x298
#define METATILE_SecretBase_HeavyDesk_BottomMid         0x299
#define METATILE_SecretBase_HeavyDesk_BottomRight       0x29A
#define METATILE_SecretBase_HeavyDesk_TopLeft           0x290
#define METATILE_SecretBase_HeavyDesk_TopMid            0x291
#define METATILE_SecretBase_HeavyDesk_TopRight          0x292
#define METATILE_SecretBase_JumpMat                     0x261
#define METATILE_SecretBase_KissPoster_Left             0x32C
#define METATILE_SecretBase_KissPoster_Right            0x32D
#define METATILE_SecretBase_LongPoster_Left             0x31E
#define METATILE_SecretBase_LongPoster_Right            0x31F
#define METATILE_SecretBase_MudBall                     0x228
#define METATILE_SecretBase_NoteMat_A                   0x27D
#define METATILE_SecretBase_NoteMat_B                   0x27E
#define METATILE_SecretBase_NoteMat_C_High              0x2B3
#define METATILE_SecretBase_NoteMat_C_Low               0x278
#define METATILE_SecretBase_NoteMat_D                   0x279
#define METATILE_SecretBase_NoteMat_E                   0x27A
#define METATILE_SecretBase_NoteMat_F                   0x27B
#define METATILE_SecretBase_NoteMat_G                   0x27C
#define METATILE_SecretBase_PC                          0x220
#define METATILE_SecretBase_PC_On                       0x224
#define METATILE_SecretBase_PikaPoster_Left             0x31C
#define METATILE_SecretBase_PikaPoster_Right            0x31D
#define METATILE_SecretBase_PokemonChair                0x2B9
#define METATILE_SecretBase_PokemonDesk                 0x28F
#define METATILE_SecretBase_PowderSnowMat_BottomLeft    0x310
#define METATILE_SecretBase_PowderSnowMat_BottomMid     0x311
#define METATILE_SecretBase_PowderSnowMat_BottomRight   0x312
#define METATILE_SecretBase_PowderSnowMat_Center        0x309
#define METATILE_SecretBase_PowderSnowMat_MidLeft       0x308
#define METATILE_SecretBase_PowderSnowMat_MidRight      0x30A
#define METATILE_SecretBase_PowderSnowMat_TopLeft       0x300
#define METATILE_SecretBase_PowderSnowMat_TopMid        0x301
#define METATILE_SecretBase_PowderSnowMat_TopRight      0x302
#define METATILE_SecretBase_PrettyChair                 0x2C0
#define METATILE_SecretBase_PrettyDesk_BottomLeft       0x2CD
#define METATILE_SecretBase_PrettyDesk_BottomMid        0x2CE
#define METATILE_SecretBase_PrettyDesk_BottomRight      0x2CF
#define METATILE_SecretBase_PrettyDesk_Center           0x2C6
#define METATILE_SecretBase_PrettyDesk_MidLeft          0x2C5
#define METATILE_SecretBase_PrettyDesk_MidRight         0x2C7
#define METATILE_SecretBase_PrettyDesk_TopLeft          0x2BD
#define METATILE_SecretBase_PrettyDesk_TopMid           0x2BE
#define METATILE_SecretBase_PrettyDesk_TopRight         0x2BF
#define METATILE_SecretBase_PrettyFlowers_Base1         0x2DC
#define METATILE_SecretBase_PrettyFlowers_Base2         0x2DD
#define METATILE_SecretBase_PrettyFlowers_Top           0x2D4
#define METATILE_SecretBase_PrettyFlowers_TopWall       0x2D5
#define METATILE_SecretBase_RaggedChair                 0x2C2
#define METATILE_SecretBase_RaggedDesk_BottomLeft       0x29B
#define METATILE_SecretBase_RaggedDesk_BottomMid        0x29C
#define METATILE_SecretBase_RaggedDesk_BottomRight      0x29D
#define METATILE_SecretBase_RaggedDesk_TopLeft          0x293
#define METATILE_SecretBase_RaggedDesk_TopMid           0x294
#define METATILE_SecretBase_RaggedDesk_TopRight         0x295
#define METATILE_SecretBase_RedBalloon                  0x338
#define METATILE_SecretBase_RedBrick_Bottom             0x22D
#define METATILE_SecretBase_RedBrick_Top                0x225
#define METATILE_SecretBase_RedPlant_Base1              0x2D8
#define METATILE_SecretBase_RedPlant_Base2              0x2D9
#define METATILE_SecretBase_RedPlant_Top                0x2D0
#define METATILE_SecretBase_RedPlant_TopWall            0x2D1
#define METATILE_SecretBase_RedPoster                   0x332
#define METATILE_SecretBase_RedTent_BottomLeft          0x240
#define METATILE_SecretBase_RedTent_BottomRight         0x23B
#define METATILE_SecretBase_RedTent_Door                0x241
#define METATILE_SecretBase_RedTent_DoorTop             0x239
#define METATILE_SecretBase_RedTent_MidLeft             0x238
#define METATILE_SecretBase_RedTent_MidRight            0x23A
#define METATILE_SecretBase_RedTent_TopLeft             0x230
#define METATILE_SecretBase_RedTent_TopMid              0x231
#define METATILE_SecretBase_RedTent_TopRight            0x232
#define METATILE_SecretBase_RegisterPC                  0x221
#define METATILE_SecretBase_RoundTV                     0x2F5
#define METATILE_SecretBase_SandOrnament_Base1          0x28D
#define METATILE_SecretBase_SandOrnament_Base2          0x28E
#define METATILE_SecretBase_SandOrnament_BrokenBase     0x28C
#define METATILE_SecretBase_SandOrnament_BrokenTop      0x284
#define METATILE_SecretBase_SandOrnament_Top            0x285
#define METATILE_SecretBase_SandOrnament_TopWall        0x286
#define METATILE_SecretBase_SeaPoster_Left              0x324
#define METATILE_SecretBase_SeaPoster_Right             0x325
#define METATILE_SecretBase_SilverShield_Base1          0x2DE
#define METATILE_SecretBase_SilverShield_Base2          0x2DF
#define METATILE_SecretBase_SilverShield_Top            0x2D6
#define METATILE_SecretBase_SilverShield_TopWall        0x2D7
#define METATILE_SecretBase_SkyPoster_Left              0x326
#define METATILE_SecretBase_SkyPoster_Right             0x327
#define METATILE_SecretBase_Slide_MatLeft               0x26F
#define METATILE_SecretBase_Slide_MatRight              0x277
#define METATILE_SecretBase_Slide_SlideBottom           0x264
#define METATILE_SecretBase_Slide_SlideTop              0x23E
#define METATILE_SecretBase_Slide_StairLanding          0x23D
#define METATILE_SecretBase_Slide_Stairs                0x263
#define METATILE_SecretBase_Slide_TopLeft               0x235
#define METATILE_SecretBase_Slide_TopRight              0x236
#define METATILE_SecretBase_SmallChair                  0x2B8
#define METATILE_SecretBase_SmallDesk                   0x287
#define METATILE_SecretBase_SolidBoard_Bottom           0x23C
#define METATILE_SecretBase_SolidBoard_Top              0x234
#define METATILE_SecretBase_SpikesMat_BottomLeft        0x329
#define METATILE_SecretBase_SpikesMat_BottomMid         0x32A
#define METATILE_SecretBase_SpikesMat_BottomRight       0x32B
#define METATILE_SecretBase_SpikesMat_Center            0x322
#define METATILE_SecretBase_SpikesMat_MidLeft           0x321
#define METATILE_SecretBase_SpikesMat_MidRight          0x323
#define METATILE_SecretBase_SpikesMat_TopLeft           0x319
#define METATILE_SecretBase_SpikesMat_TopMid            0x31A
#define METATILE_SecretBase_SpikesMat_TopRight          0x31B
#define METATILE_SecretBase_SpinMat                     0x262
#define METATILE_SecretBase_Stand_BaseLeft              0x273
#define METATILE_SecretBase_Stand_BaseRight             0x274
#define METATILE_SecretBase_Stand_CornerLeft            0x26A
#define METATILE_SecretBase_Stand_CornerRight           0x26D
#define METATILE_SecretBase_Stand_MidLeft               0x26B
#define METATILE_SecretBase_Stand_MidRight              0x26C
#define METATILE_SecretBase_Stand_StairsLeft            0x272
#define METATILE_SecretBase_Stand_StairsRight           0x275
#define METATILE_SecretBase_SurfMat_BottomLeft          0x252
#define METATILE_SecretBase_SurfMat_BottomMid           0x253
#define METATILE_SecretBase_SurfMat_BottomRight         0x254
#define METATILE_SecretBase_SurfMat_Center              0x24B
#define METATILE_SecretBase_SurfMat_MidLeft             0x24A
#define METATILE_SecretBase_SurfMat_MidRight            0x24C
#define METATILE_SecretBase_SurfMat_TopLeft             0x242
#define METATILE_SecretBase_SurfMat_TopMid              0x243
#define METATILE_SecretBase_SurfMat_TopRight            0x244
#define METATILE_SecretBase_TV                          0x2F4
#define METATILE_SecretBase_ThunderMat_BottomLeft       0x255
#define METATILE_SecretBase_ThunderMat_BottomMid        0x256
#define METATILE_SecretBase_ThunderMat_BottomRight      0x257
#define METATILE_SecretBase_ThunderMat_Center           0x24E
#define METATILE_SecretBase_ThunderMat_MidLeft          0x24D
#define METATILE_SecretBase_ThunderMat_MidRight         0x24F
#define METATILE_SecretBase_ThunderMat_TopLeft          0x245
#define METATILE_SecretBase_ThunderMat_TopMid           0x246
#define METATILE_SecretBase_ThunderMat_TopRight         0x247
#define METATILE_SecretBase_Tire_BottomLeft             0x288
#define METATILE_SecretBase_Tire_BottomRight            0x289
#define METATILE_SecretBase_Tire_TopLeft                0x280
#define METATILE_SecretBase_Tire_TopRight               0x281
#define METATILE_SecretBase_TropicalPlant_Base1         0x2DA
#define METATILE_SecretBase_TropicalPlant_Base2         0x2DB
#define METATILE_SecretBase_TropicalPlant_Top           0x2D2
#define METATILE_SecretBase_TropicalPlant_TopWall       0x2D3
#define METATILE_SecretBase_Wall_TopMid                 0x202
#define METATILE_SecretBase_YellowBalloon               0x340
#define METATILE_SecretBase_YellowBrick_Bottom          0x22E
#define METATILE_SecretBase_YellowBrick_Top             0x226

// gTileset_Shop
#define METATILE_Shop_Door_Elevator   0x285
#define METATILE_Shop_Laptop1_Flash   0x258
#define METATILE_Shop_Laptop1_Normal  0x29D
#define METATILE_Shop_Laptop2_Flash   0x260
#define METATILE_Shop_Laptop2_Normal  0x2A5

// gTileset_Slateport
#define METATILE_Slateport_Door             0x2DC
#define METATILE_Slateport_Door_BattleTent  0x393

// gTileset_Sootopolis
#define METATILE_Sootopolis_Door             0x21E
#define METATILE_Sootopolis_Door_Closed      0x248
#define METATILE_Sootopolis_Door_PeakedRoof  0x21C
#define METATILE_Sootopolis_GymDoor_Closed   0x250
#define METATILE_Sootopolis_RoughWater       0x290

// gTileset_SootopolisGym
#define METATILE_SootopolisGym_Ice_Broken   0x206
#define METATILE_SootopolisGym_Ice_Cracked  0x20E
#define METATILE_SootopolisGym_Stairs       0x207

// gTileset_TrainerHill
#define METATILE_TrainerHill_CounterDoor          0x334
#define METATILE_TrainerHill_Door_Elevator_Lobby  0x32C
#define METATILE_TrainerHill_Door_Elevator_Roof   0x383
#define METATILE_TrainerHill_GreenFloorTile       0x307

// gTileset_TrickHousePuzzle
#define METATILE_TrickHousePuzzle_Arrow_RedOnBlack_Down       0x263
#define METATILE_TrickHousePuzzle_Arrow_RedOnBlack_Left       0x261
#define METATILE_TrickHousePuzzle_Arrow_RedOnBlack_Left_Alt   0x27B
#define METATILE_TrickHousePuzzle_Arrow_RedOnBlack_Right      0x260
#define METATILE_TrickHousePuzzle_Arrow_RedOnBlack_Right_Alt  0x27C
#define METATILE_TrickHousePuzzle_Arrow_RedOnBlack_Up         0x262
#define METATILE_TrickHousePuzzle_Arrow_YellowOnWhite_Right   0x298
#define METATILE_TrickHousePuzzle_BlueDoorH_Closed_Tile0      0x23B
#define METATILE_TrickHousePuzzle_BlueDoorH_Closed_Tile1      0x23C
#define METATILE_TrickHousePuzzle_BlueDoorH_Closed_Tile2      0x243
#define METATILE_TrickHousePuzzle_BlueDoorH_Closed_Tile3      0x244
#define METATILE_TrickHousePuzzle_BlueDoorH_Open_Tile0        0x24B
#define METATILE_TrickHousePuzzle_BlueDoorH_Open_Tile1        0x24C
#define METATILE_TrickHousePuzzle_BlueDoorH_Open_Tile2        0x253
#define METATILE_TrickHousePuzzle_BlueDoorH_Open_Tile3        0x254
#define METATILE_TrickHousePuzzle_BlueDoorV_Open0             0x23D
#define METATILE_TrickHousePuzzle_BlueDoorV_Open1             0x245
#define METATILE_TrickHousePuzzle_BlueDoorV_Retracted         0x24D
#define METATILE_TrickHousePuzzle_Button_Pressed              0x259
#define METATILE_TrickHousePuzzle_Button_Up                   0x258
#define METATILE_TrickHousePuzzle_Door_Shuttered              0x26A
#define METATILE_TrickHousePuzzle_Floor_ShadowTop             0x255
#define METATILE_TrickHousePuzzle_Floor_ShadowTop_Alt         0x252
#define METATILE_TrickHousePuzzle_Lever_Off                   0x23E
#define METATILE_TrickHousePuzzle_Lever_On                    0x23F
#define METATILE_TrickHousePuzzle_RedDoorH_Closed_Tile0       0x238
#define METATILE_TrickHousePuzzle_RedDoorH_Closed_Tile1       0x239
#define METATILE_TrickHousePuzzle_RedDoorH_Closed_Tile2       0x240
#define METATILE_TrickHousePuzzle_RedDoorH_Closed_Tile3       0x241
#define METATILE_TrickHousePuzzle_RedDoorH_Open_Tile0         0x248
#define METATILE_TrickHousePuzzle_RedDoorH_Open_Tile1         0x249
#define METATILE_TrickHousePuzzle_RedDoorH_Open_Tile2         0x250
#define METATILE_TrickHousePuzzle_RedDoorH_Open_Tile3         0x251
#define METATILE_TrickHousePuzzle_RedDoorV_Open0              0x23A
#define METATILE_TrickHousePuzzle_RedDoorV_Open1              0x242
#define METATILE_TrickHousePuzzle_RedDoorV_Retracted          0x24A
#define METATILE_TrickHousePuzzle_Stairs_Down                 0x20B

// gTileset_Underwater
#define METATILE_Underwater_FloorShadow  0x228
#define METATILE_Underwater_RockWall     0x21E

// Other
#define METATILE_RS_MossdeepGym_RedArrow_Down   0x205
#define METATILE_RS_MossdeepGym_RedArrow_Left   0x20C
#define METATILE_RS_MossdeepGym_RedArrow_Right  0x204
#define METATILE_RS_MossdeepGym_RedArrow_Up     0x20D
#define METATILE_RS_MossdeepGym_Switch_Down     0x239
#define METATILE_RS_MossdeepGym_Switch_Up       0x238

// BEGIN GENERATED SHARED HUB LABELS
#define METATILE_HubArchitecture_PortalRoom_Decor_WallPlate_0_0 0x039
#define METATILE_HubFurnishings_Galactic_21C 0x29C
#define METATILE_HubFurnishings_PlantedHabitat_0_0 0x33E
#define METATILE_HubFurnishings_PlantedHabitat_1_0 0x33F
#define METATILE_HubFurnishings_PlantedHabitat_2_0 0x340
#define METATILE_HubFurnishings_PlantedHabitat_3_0 0x341
#define METATILE_HubFurnishings_PlantedHabitat_4_0 0x342
#define METATILE_HubFurnishings_PlantedHabitat_5_0 0x343
#define METATILE_HubFurnishings_PlantedHabitat_0_1 0x344
#define METATILE_HubFurnishings_PlantedHabitat_1_1 0x345
#define METATILE_HubFurnishings_PlantedHabitat_2_1 0x346
#define METATILE_HubFurnishings_PlantedHabitat_3_1 0x347
#define METATILE_HubFurnishings_PlantedHabitat_4_1 0x348
#define METATILE_HubFurnishings_PlantedHabitat_5_1 0x349
#define METATILE_HubFurnishings_PlantedHabitat_0_2 0x34A
#define METATILE_HubFurnishings_PlantedHabitat_1_2 0x34B
#define METATILE_HubFurnishings_PlantedHabitat_2_2 0x34C
#define METATILE_HubFurnishings_PlantedHabitat_3_2 0x34D
#define METATILE_HubFurnishings_PlantedHabitat_4_2 0x34E
#define METATILE_HubFurnishings_PlantedHabitat_5_2 0x34F
#define METATILE_HubFurnishings_PlantedHabitat_0_3 0x350
#define METATILE_HubFurnishings_PlantedHabitat_1_3 0x351
#define METATILE_HubFurnishings_PlantedHabitat_2_3 0x352
#define METATILE_HubFurnishings_PlantedHabitat_3_3 0x353
#define METATILE_HubFurnishings_PlantedHabitat_4_3 0x354
#define METATILE_HubFurnishings_PlantedHabitat_5_3 0x355
#define METATILE_HubFurnishings_PlantedHabitat_0_4 0x356
#define METATILE_HubFurnishings_PlantedHabitat_1_4 0x357
#define METATILE_HubFurnishings_PlantedHabitat_2_4 0x358
#define METATILE_HubFurnishings_PlantedHabitat_3_4 0x359
#define METATILE_HubFurnishings_PlantedHabitat_4_4 0x35A
#define METATILE_HubFurnishings_PlantedHabitat_5_4 0x35B
#define METATILE_HubFurnishings_PlantedBrokenHabitat_0 0x35C
#define METATILE_HubFurnishings_PlantedBrokenHabitat_1 0x35D
#define METATILE_HubFurnishings_PlantedBrokenHabitat_2 0x35E
#define METATILE_HubFurnishings_PlantedBrokenHabitat_3 0x35F
#define METATILE_HubFurnishings_PlantedBrokenHabitat_4 0x360
#define METATILE_HubFurnishings_PlantedBrokenHabitat_5 0x361
#define METATILE_HubFurnishings_BerryLab_Soil 0x362
#define METATILE_HubFurnishings_BerryLab_GlassBack0 0x363
#define METATILE_HubFurnishings_BerryLab_GlassBack1 0x364
#define METATILE_HubFurnishings_BerryLab_GlassBack2 0x365
#define METATILE_HubFurnishings_BerryLab_GlassBack3 0x366
#define METATILE_HubFurnishings_BerryLab_GlassBack4 0x367
#define METATILE_HubFurnishings_BerryLab_GlassBack5 0x368
#define METATILE_HubFurnishings_BerryLab_PlantTop 0x369
#define METATILE_HubFurnishings_BerryLab_PlantBase 0x36A
#define METATILE_HubFurnishings_BerryLab_BedEndLeft 0x36B
#define METATILE_HubFurnishings_BerryLab_BedEndRight 0x36C
#define METATILE_HubFurnishings_BerryLab_SoilRim 0x36D
#define METATILE_HubFurnishings_BerryLab_InactiveBed 0x36E
#define METATILE_HubFurnishings_BerryLab_GrowLight 0x36F
#define METATILE_HubFurnishings_BerryLab_SeedTray 0x370
#define METATILE_HubFurnishings_BerryLab_PropagationBase 0x371
#define METATILE_HubFurnishings_BerryLab_PlantBaseShadow 0x372
#define METATILE_HubFurnishings_BerryLab_PlantTopShadow 0x373
#define METATILE_HubFurnishings_SupplyDepot_CounterLeft 0x374
#define METATILE_HubFurnishings_SupplyDepot_CounterRight 0x375
#define METATILE_HubFurnishings_SupplyDepot_ComputerShadow_0 0x376
#define METATILE_HubFurnishings_SupplyDepot_ComputerShadow_1 0x377
#define METATILE_HubFurnishings_SupplyDepot_SpecimenFloor_0_0 0x378
#define METATILE_HubFurnishings_SupplyDepot_SpecimenFloor_1_0 0x379
#define METATILE_HubFurnishings_SupplyDepot_SpecimenFloor_0_1 0x37A
#define METATILE_HubFurnishings_SupplyDepot_SpecimenFloor_1_1 0x37B
#define METATILE_HubFurnishings_SupplyDepot_SpecimenFloor_0_2 0x37C
#define METATILE_HubFurnishings_SupplyDepot_SpecimenFloor_1_2 0x37D
#define METATILE_HubFurnishings_SupplyDepot_ComputerFloorTop_0 0x37E
#define METATILE_HubFurnishings_SupplyDepot_SpecimenPlainTop_0 0x37F
#define METATILE_HubFurnishings_SupplyDepot_ComputerFloorTop_1 0x380
#define METATILE_HubFurnishings_SupplyDepot_SpecimenPlainTop_1 0x381
#define METATILE_HubFurnishings_SupplyDepot_PillarCapFloor 0x382
#define METATILE_HubFurnishings_SupplyDepot_MarketDrawerTop 0x383
#define METATILE_HubFurnishings_SupplyDepot_MarketDrawerTopShadow 0x384
#define METATILE_HubFurnishings_SupplyDepot_MarketDrawerBase 0x385
#define METATILE_HubFurnishings_SupplyDepot_MarketDrawerBaseShadow 0x386
#define METATILE_HubFurnishings_SupplyDepot_MarketCrate 0x387
#define METATILE_HubFurnishings_SupplyDepot_MarketCrateShadow 0x388
#define METATILE_HubFurnishings_SupplyDepot_MarketRedBasket 0x389
#define METATILE_HubFurnishings_SupplyDepot_MarketRedBasketShadow 0x38A
#define METATILE_HubFurnishings_SupplyDepot_MarketGreenBasket 0x38B
#define METATILE_HubFurnishings_SupplyDepot_MarketGreenBasketShadow 0x38C
#define METATILE_HubFurnishings_SupplyDepot_MarketBottles 0x38D
#define METATILE_HubFurnishings_SupplyDepot_MarketBottlesShadow 0x38E
#define METATILE_HubFurnishings_SupplyDepot_MarketGoods 0x38F
#define METATILE_HubFurnishings_SupplyDepot_MarketGoodsShadow 0x390
#define METATILE_HubFurnishings_SupplyDepot_MarketBookDisplay0 0x391
#define METATILE_HubFurnishings_SupplyDepot_MarketBookDisplay0Shadow 0x392
#define METATILE_HubFurnishings_SupplyDepot_MarketBookDisplay1 0x393
#define METATILE_HubFurnishings_SupplyDepot_MarketBookDisplay1Shadow 0x394
#define METATILE_HubFurnishings_SupplyDepot_MarketMedicineDisplay0 0x395
#define METATILE_HubFurnishings_SupplyDepot_MarketMedicineDisplay0Shadow 0x396
#define METATILE_HubFurnishings_SupplyDepot_MarketMedicineDisplay1 0x397
#define METATILE_HubFurnishings_SupplyDepot_MarketMedicineDisplay1Shadow 0x398
// END GENERATED SHARED HUB LABELS

#endif // GUARD_METATILE_LABELS_H
