#ifndef GUARD_CONSTANTS_ROGUE_ROUTE_EVENTS_H
#define GUARD_CONSTANTS_ROGUE_ROUTE_EVENTS_H

#define ROGUE_STOLEN_TRADE_CASE_REWARD_MONEY 5000
#define ROGUE_HEXED_SHRINE_REWARD_BASE 5000
#define ROGUE_HEXED_SHRINE_REWARD_PER_DIFFICULTY 1000
#define ROGUE_HEXED_SHRINE_REWARD_MAX 15000
#define ROGUE_FORBIDDEN_STONE_REWARD_MONEY 10000
#define ROGUE_FORBIDDEN_STONE_SOUL_COUNT 3
#define ROGUE_APRICORN_CHOICE_COUNT 3
#define ROGUE_APRICORN_BALL_REWARD_COUNT 5
#define ROGUE_BURIED_CACHE_MONEY_BASE 4000
#define ROGUE_BURIED_CACHE_MONEY_PER_DIFFICULTY 500
#define ROGUE_BURIED_CACHE_MONEY_MAX 10000

enum
{
    ROGUE_ROUTE_EVENT_STATE_NOT_STARTED,
    ROGUE_ROUTE_EVENT_STATE_ACTIVE,
    ROGUE_ROUTE_EVENT_STATE_REWARD_PENDING,
    ROGUE_ROUTE_EVENT_STATE_COMPLETED,
};

enum
{
    ROGUE_ROUTE_EVENT_RESULT_FAILED,
    ROGUE_ROUTE_EVENT_RESULT_SUCCESS,
    ROGUE_ROUTE_EVENT_RESULT_MISSING_ITEM,
    ROGUE_ROUTE_EVENT_RESULT_NO_SPACE,
    ROGUE_ROUTE_EVENT_RESULT_MONEY_FULL,
    ROGUE_ROUTE_EVENT_RESULT_CANT_GIVE_MON,
    ROGUE_ROUTE_EVENT_RESULT_PARTY_FULL,
    ROGUE_ROUTE_EVENT_RESULT_WRONG_MON,
    ROGUE_ROUTE_EVENT_RESULT_PROTECTED_MON,
    ROGUE_ROUTE_EVENT_RESULT_WRONG_SITE,
    ROGUE_ROUTE_EVENT_RESULT_ALREADY_DUG,
};

enum
{
    ROGUE_BURIED_CACHE_ANCIENT,
    ROGUE_BURIED_CACHE_TRAINER,
    ROGUE_BURIED_CACHE_RELIC,
    ROGUE_BURIED_CACHE_JACKPOT,
    ROGUE_BURIED_CACHE_TYPE_COUNT,
};

enum
{
    ROGUE_FOSSIL_RESTORATION_STABLE,
    ROGUE_FOSSIL_RESTORATION_ADAPTIVE,
};

#endif // GUARD_CONSTANTS_ROGUE_ROUTE_EVENTS_H
