#ifndef GUARD_CONSTANTS_ROGUE_ROUTE_EVENTS_H
#define GUARD_CONSTANTS_ROGUE_ROUTE_EVENTS_H

enum
{
    ROGUE_ROUTE_EVENT_STATE_NOT_STARTED,
    ROGUE_ROUTE_EVENT_STATE_ACTIVE,
    ROGUE_ROUTE_EVENT_STATE_REWARD_PENDING,
    ROGUE_ROUTE_EVENT_STATE_COMPLETED,
};

enum
{
    ROGUE_ROUTE_EVENT_RESULT_FAILED,
    ROGUE_ROUTE_EVENT_RESULT_SUCCESS,
    ROGUE_ROUTE_EVENT_RESULT_MISSING_ITEM,
    ROGUE_ROUTE_EVENT_RESULT_NO_SPACE,
};

#endif // GUARD_CONSTANTS_ROGUE_ROUTE_EVENTS_H
