#ifndef GUARD_CONSTANTS_ROGUE_ADVENTURE_QUESTS_H
#define GUARD_CONSTANTS_ROGUE_ADVENTURE_QUESTS_H

#define ROGUE_ADVENTURE_QUEST_CAPACITY 16
#define ROGUE_ADVENTURE_QUEST_INVALID_ID 0xFF
#define ROGUE_ADVENTURE_QUEST_INVALID_ROOM 0x3F
#define ROGUE_ADVENTURE_QUEST_MAX_NODE_COUNT 16
#define ROGUE_ADVENTURE_QUEST_MAX_ROUTE_DELAY 3

enum
{
    ROGUE_ADVENTURE_QUEST_DEFINITION_NONE,
    ROGUE_ADVENTURE_QUEST_DEFINITION_STOLEN_TRADE_CASE,
    ROGUE_ADVENTURE_QUEST_DEFINITION_ANOMALOUS_FOSSIL,
    ROGUE_ADVENTURE_QUEST_DEFINITION_FORBIDDEN_STONE,
    ROGUE_ADVENTURE_QUEST_DEFINITION_APRICORN_CRAFTING,
    ROGUE_ADVENTURE_QUEST_DEFINITION_MYSTERY_EGG_COURIER,
    ROGUE_ADVENTURE_QUEST_DEFINITION_COUNT,
};

enum
{
    ROGUE_ADVENTURE_QUEST_STATE_EMPTY,
    ROGUE_ADVENTURE_QUEST_STATE_ACTIVE,
    ROGUE_ADVENTURE_QUEST_STATE_READY,
};

enum
{
    ROGUE_ADVENTURE_QUEST_SIGNAL_NONE,
    ROGUE_ADVENTURE_QUEST_SIGNAL_TRAINER_DEFEATED,
    ROGUE_ADVENTURE_QUEST_SIGNAL_ROUTE_COMPLETED,
    ROGUE_ADVENTURE_QUEST_SIGNAL_ITEM_OBTAINED,
    ROGUE_ADVENTURE_QUEST_SIGNAL_POKEMON_CAUGHT,
    ROGUE_ADVENTURE_QUEST_SIGNAL_OBJECTIVE_PROGRESS,
    ROGUE_ADVENTURE_QUEST_SIGNAL_SCENE_COMPLETED,
    ROGUE_ADVENTURE_QUEST_SIGNAL_DAYCARE_DELIVERY,
    ROGUE_ADVENTURE_QUEST_SIGNAL_COUNT,
};

#define ROGUE_ADVENTURE_QUEST_NODE_COMPLETE 0xFF

#define ROGUE_ADVENTURE_QUEST_NODE_FLAG_ROUTE_SCENE (1 << 0)
#define ROGUE_ADVENTURE_QUEST_NODE_FLAG_PROGRESS_SET_BITS (1 << 1)
#define ROGUE_ADVENTURE_QUEST_NODE_FLAG_ADVANCE_ON_PROGRESS (1 << 2)

#endif // GUARD_CONSTANTS_ROGUE_ADVENTURE_QUESTS_H
