#ifndef GUARD_CONSTANTS_ROGUE_ROUTE_SCENES_H
#define GUARD_CONSTANTS_ROGUE_ROUTE_SCENES_H

enum
{
    ROGUE_ROUTE_SCENE_RECIPE_NONE,
    ROGUE_ROUTE_SCENE_RECIPE_STOLEN_TRADE_CASE_OFFER,
    ROGUE_ROUTE_SCENE_RECIPE_STOLEN_TRADE_CASE_CAMP,
    ROGUE_ROUTE_SCENE_RECIPE_STOLEN_TRADE_CASE_PAYOFF,
    ROGUE_ROUTE_SCENE_RECIPE_HEXED_SHRINE,
    ROGUE_ROUTE_SCENE_RECIPE_ANOMALOUS_FOSSIL_OFFER,
    ROGUE_ROUTE_SCENE_RECIPE_ANOMALOUS_FOSSIL_RESTORATION,
    ROGUE_ROUTE_SCENE_RECIPE_COUNT,
};

enum
{
    ROGUE_ROUTE_SCENE_SOURCE_ONE_OFF,
    ROGUE_ROUTE_SCENE_SOURCE_QUEST_GENERATOR,
    ROGUE_ROUTE_SCENE_SOURCE_QUEST_NODE,
    ROGUE_ROUTE_SCENE_SOURCE_REACTIVE,
    ROGUE_ROUTE_SCENE_SOURCE_COUNT,
};

enum
{
    ROGUE_ROUTE_ENVIRONMENT_FIELD,
    ROGUE_ROUTE_ENVIRONMENT_FOREST,
    ROGUE_ROUTE_ENVIRONMENT_CAVE,
    ROGUE_ROUTE_ENVIRONMENT_MOUNTAIN,
    ROGUE_ROUTE_ENVIRONMENT_WATERFRONT,
    ROGUE_ROUTE_ENVIRONMENT_URBAN,
    ROGUE_ROUTE_ENVIRONMENT_COUNT,
};

enum
{
    ROGUE_ROUTE_SCENE_LOT_SMALL,
    ROGUE_ROUTE_SCENE_LOT_MEDIUM,
    ROGUE_ROUTE_SCENE_LOT_LARGE,
    ROGUE_ROUTE_SCENE_LOT_SIZE_COUNT,
};

#define ROGUE_ROUTE_SCENE_MAX_LOTS 10
#define ROGUE_ROUTE_SCENE_MAX_PLACEMENTS 3
#define ROGUE_ROUTE_SCENE_MAX_ROLES 4

#endif // GUARD_CONSTANTS_ROGUE_ROUTE_SCENES_H
