#ifndef GUARD_CONSTANTS_ROGUE_ROUTE_SCENES_H
#define GUARD_CONSTANTS_ROGUE_ROUTE_SCENES_H

enum
{
    ROGUE_ROUTE_SCENE_RECIPE_NONE,
    ROGUE_ROUTE_SCENE_RECIPE_STOLEN_TRADE_CASE_OFFER,
    ROGUE_ROUTE_SCENE_RECIPE_STOLEN_TRADE_CASE_CAMP,
    ROGUE_ROUTE_SCENE_RECIPE_STOLEN_TRADE_CASE_PAYOFF,
    ROGUE_ROUTE_SCENE_RECIPE_HEXED_SHRINE,
    ROGUE_ROUTE_SCENE_RECIPE_ANOMALOUS_FOSSIL_OFFER,
    ROGUE_ROUTE_SCENE_RECIPE_ANOMALOUS_FOSSIL_RESTORATION,
    ROGUE_ROUTE_SCENE_RECIPE_FORBIDDEN_STONE_OFFER,
    ROGUE_ROUTE_SCENE_RECIPE_FORBIDDEN_STONE_SOULS,
    ROGUE_ROUTE_SCENE_RECIPE_FORBIDDEN_STONE_PAYOFF,
    ROGUE_ROUTE_SCENE_RECIPE_APRICORN_GROVE,
    ROGUE_ROUTE_SCENE_RECIPE_APRICORN_GROVE_AND_ARTISAN,
    ROGUE_ROUTE_SCENE_RECIPE_APRICORN_ARTISAN,
    ROGUE_ROUTE_SCENE_RECIPE_UNBOUND_TUTOR,
    ROGUE_ROUTE_SCENE_RECIPE_TRAVELING_MERCHANT,
    ROGUE_ROUTE_SCENE_RECIPE_BREEDERS_EXCHANGE,
    ROGUE_ROUTE_SCENE_RECIPE_BURIED_CACHE,
    ROGUE_ROUTE_SCENE_RECIPE_TIDE_SALVAGE,
    ROGUE_ROUTE_SCENE_RECIPE_COUNT,
};

enum
{
    ROGUE_ROUTE_SCENE_SOURCE_ONE_OFF,
    ROGUE_ROUTE_SCENE_SOURCE_QUEST_GENERATOR,
    ROGUE_ROUTE_SCENE_SOURCE_QUEST_NODE,
    ROGUE_ROUTE_SCENE_SOURCE_REACTIVE,
    ROGUE_ROUTE_SCENE_SOURCE_COUNT,
};

enum
{
    ROGUE_ROUTE_ENVIRONMENT_FIELD,
    ROGUE_ROUTE_ENVIRONMENT_FOREST,
    ROGUE_ROUTE_ENVIRONMENT_CAVE,
    ROGUE_ROUTE_ENVIRONMENT_MOUNTAIN,
    ROGUE_ROUTE_ENVIRONMENT_WATERFRONT,
    ROGUE_ROUTE_ENVIRONMENT_URBAN,
    ROGUE_ROUTE_ENVIRONMENT_COUNT,
};

enum
{
    ROGUE_ROUTE_SCENE_SPOT_NPC,
    ROGUE_ROUTE_SCENE_SPOT_NPC_WITH_DECOR,
    ROGUE_ROUTE_SCENE_SPOT_DECOR,
    ROGUE_ROUTE_SCENE_SPOT_PLANT_PATCH,
    ROGUE_ROUTE_SCENE_SPOT_TYPE_COUNT,
};

enum
{
    ROGUE_ROUTE_SCENE_TERRAIN_LAND,
    ROGUE_ROUTE_SCENE_TERRAIN_WATER,
    ROGUE_ROUTE_SCENE_TERRAIN_ICE,
    ROGUE_ROUTE_SCENE_TERRAIN_CAVE,
    ROGUE_ROUTE_SCENE_TERRAIN_COUNT,
};

#define ROGUE_ROUTE_SCENE_TERRAIN_MASK(terrain) (1 << (terrain))
#define ROGUE_ROUTE_SCENE_TERRAIN_MASK_LAND ROGUE_ROUTE_SCENE_TERRAIN_MASK(ROGUE_ROUTE_SCENE_TERRAIN_LAND)
#define ROGUE_ROUTE_SCENE_TERRAIN_MASK_WATER ROGUE_ROUTE_SCENE_TERRAIN_MASK(ROGUE_ROUTE_SCENE_TERRAIN_WATER)
#define ROGUE_ROUTE_SCENE_TERRAIN_MASK_ICE ROGUE_ROUTE_SCENE_TERRAIN_MASK(ROGUE_ROUTE_SCENE_TERRAIN_ICE)
#define ROGUE_ROUTE_SCENE_TERRAIN_MASK_CAVE ROGUE_ROUTE_SCENE_TERRAIN_MASK(ROGUE_ROUTE_SCENE_TERRAIN_CAVE)
#define ROGUE_ROUTE_SCENE_TERRAIN_MASK_STANDARD (ROGUE_ROUTE_SCENE_TERRAIN_MASK_LAND | ROGUE_ROUTE_SCENE_TERRAIN_MASK_CAVE)
#define ROGUE_ROUTE_SCENE_TERRAIN_MASK_ALL ((1 << ROGUE_ROUTE_SCENE_TERRAIN_COUNT) - 1)

#define ROGUE_ROUTE_SCENE_MAX_SPOT_GROUPS 10
#define ROGUE_ROUTE_SCENE_MAX_SPOTS 10
#define ROGUE_ROUTE_SCENE_MAX_LOTS ROGUE_ROUTE_SCENE_MAX_SPOT_GROUPS
#define ROGUE_ROUTE_SCENE_MAX_PLACEMENTS 3
#define ROGUE_ROUTE_SCENE_MAX_ROLES 4

// Save-backed variables track which fallback families have appeared and which
// have been completed during the current Adventure. Each variable owns eight
// encountered bits and eight completed bits.
enum
{
    ROGUE_ROUTE_FAMILY_STOLEN_TRADE_CASE,
    ROGUE_ROUTE_FAMILY_HEXED_SHRINE,
    ROGUE_ROUTE_FAMILY_ANOMALOUS_FOSSIL,
    ROGUE_ROUTE_FAMILY_FORBIDDEN_STONE,
    ROGUE_ROUTE_FAMILY_APRICORN_CRAFTING,
    ROGUE_ROUTE_FAMILY_UNBOUND_TUTOR,
    ROGUE_ROUTE_FAMILY_TRAVELING_MERCHANT,
    ROGUE_ROUTE_FAMILY_BREEDERS_EXCHANGE,
    ROGUE_ROUTE_FAMILY_BURIED_CACHE,
    ROGUE_ROUTE_FAMILY_TIDE_SALVAGE,
    ROGUE_ROUTE_FAMILY_COUNT,
};

#define ROGUE_ROUTE_FAMILY_HISTORY_PER_VAR 8
#define ROGUE_ROUTE_FAMILY_HISTORY_COMPLETED_SHIFT 8

#endif // GUARD_CONSTANTS_ROGUE_ROUTE_SCENES_H
