#ifndef GUARD_CONSTANTS_ROGUE_ROUTE_EVENTS_H
#define GUARD_CONSTANTS_ROGUE_ROUTE_EVENTS_H

enum
{
    ROGUE_ROUTE_EVENT_NONE,
    ROGUE_ROUTE_EVENT_DELIVERY,
};

enum
{
    ROGUE_ROUTE_EVENT_ANCHOR_SENDER,
    ROGUE_ROUTE_EVENT_ANCHOR_RECIPIENT,
    ROGUE_ROUTE_EVENT_ANCHOR_COUNT,
};

enum
{
    ROGUE_ROUTE_EVENT_STATE_NOT_STARTED,
    ROGUE_ROUTE_EVENT_STATE_CARRYING,
    ROGUE_ROUTE_EVENT_STATE_COMPLETED,
};

#endif // GUARD_CONSTANTS_ROGUE_ROUTE_EVENTS_H
