gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Welcome to EMERALD ROGUE:\n"
	.string "DIVERGENCE!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Each time you set out, the routes\n"
	.string "and wild POKéMON may be entirely\n"
	.string "different.\p"
	.string "For a field researcher, it's a\n"
	.string "dream come true!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But that's enough about my research!\p"
	.string "Tell me about yourself.$"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Select an avatar$"

gText_Birch_AvatarStyle0::
	.string "Select an appearance$"

gText_Birch_AvatarStyle1::
	.string "Select clothing style$"

gText_Birch_WhatsYourName::
	.string "Now, what is your name?$"

gText_Birch_HappyWithAvatar::
	.string "So this is your avatar?\n(Can be changed later)$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "{PLAYER}{KUN}!"
	.string "$"

gText_Birch_AreYouReady::
	.string "Well, I'll be expecting you.\p"
	.string "Come see me at my POKéMON LAB!\p"
	.string "$"
