"""Append planted Safari habitat variants to the shared catalogue."""
from PIL import Image
from generate_portal_room import ROOT, Source

FLOWER_START = 1008


def append_terrariums(cat):
    from generate_hub_tiles import render
    assert len(cat.metas) == 830, 'Planted habitat IDs moved; an explicit map migration is required'
    grass = render(Source('general', 'lab'), 1)
    bank = 1  # Existing green, red and yellow bank; never recolor shared assets.
    pal = cat.pals[bank]
    # Retain the outdoor grass pattern with two greens from the room palette.
    greens = sorted(grass.getcolors(), key=lambda p: sum(p[1]))
    convert = {c: pal.index((57, 131, 82)) if i == 0 else pal.index((74, 180, 98))
               for i, (_, c) in enumerate(greens)}
    grass_indices = Image.new('P', (16, 16))
    grass_indices.putdata([convert[c] for c in grass.getdata()])
    # Map plant roles explicitly: nearest-color matching turned the source
    # grass grey/lavender and the leaf outlines navy. Background pixels reuse
    # the surrounding grass pattern in every animation frame.
    plant_colors = {
        (57, 82, 0): (57, 131, 82),
        (57, 139, 49): (57, 131, 82),
        (24, 164, 106): (74, 180, 98),
        (131, 197, 98): (74, 180, 98),
        (205, 65, 82): (189, 98, 82),
        (255, 197, 148): (238, 213, 205),
    }
    frames = []
    for frame in range(3):
        flower = Image.open(ROOT/f'data/tilesets/primary/general/anim/flower/{frame}.png').convert('RGB')
        indices = Image.new('P', (16, 16))
        for y in range(16):
            for x in range(16):
                color = flower.getpixel((x, y))
                indices.putpixel((x, y), grass_indices.getpixel((x, y))
                    if color in convert else pal.index(plant_colors[color]))
        frames.append([indices.crop((x, y, x+8, y+8)).tobytes() for y in (0, 8) for x in (0, 8)])
    floor = cat.render(cat.mapping['safari_lab'][cat.config['rooms']['safari_lab']['names']['Floor']])
    cat.terrariums = {}
    def tile(raw, palette):
        if raw not in cat.tiles: cat.tiles.append(raw)
        return cat.tiles.index(raw) | (palette << 12)
    def original(name):
        return cat.mapping['safari_lab'][cat.config['rooms']['safari_lab']['names'][name]]
    # Insets match the existing 96x80 frame: planting stops under its mullions
    # and front plinth. Outside pixels remain the original lab floor.
    for broken in (False, True):
        rows = (4,) if broken else range(5)
        for y in rows:
            for x in range(6):
                name = f'BrokenHabitat_{x}' if broken else f'Habitat_{x}_{y}'
                old = original(name)
                vals = []
                for ty in (0, 8):
                    for tx in (0, 8):
                        colors = []
                        for py in range(ty, ty+8):
                            for px in range(tx, tx+8):
                                gx, gy = x*16+px, y*16+py
                                colors.append(pal[grass_indices.getpixel((px, py))]
                                    if 8 <= gx <= 88 and 8 <= gy <= 64 else floor.getpixel((px, py)))
                        # Boundary tiles may contain floor and grass; choose an
                        # existing palette per 8x8 tile, preserving floor colors.
                        pi = min(range(11), key=lambda b: sum(min(sum((c[k]-p[k])**2 for k in range(3)) for p in cat.pals[b][1:]) for c in set(colors)))
                        raw = bytes(min(range(1,16),key=lambda i:sum((c[k]-cat.pals[pi][i][k])**2 for k in range(3))) for c in colors)
                        vals.append(tile(raw, pi))
                # Two small patches leave most of the walking area open grass.
                if (x, y) in ((1, 1), (4, 2)):
                    vals = [(FLOWER_START+i)|(bank<<12) for i in range(4)]
                vals += cat.metas[old][4:]
                cat.terrariums[name] = len(cat.metas)
                cat.metas.append(vals)
                cat.attrs.append(cat.attrs[old])
    assert len(cat.tiles) <= FLOWER_START, 'Terrarium animation overlaps static graphics'
    cat.tiles += [bytes(64)] * (FLOWER_START-len(cat.tiles)) + frames[0]
    cat.terrarium_frames = frames


def animation_header(cat):
    text = '// Generated by scripts/generate_hub_tiles.py; do not edit.\n'
    text += f'#define TERRARIUM_FLOWER_TILE_START {FLOWER_START}\n'
    for frame, tiles in enumerate(cat.terrarium_frames):
        raw = b''.join(bytes(t[i] | (t[i+1]<<4) for i in range(0,64,2)) for t in tiles)
        vals = [raw[i] | (raw[i+1]<<8) for i in range(0,len(raw),2)]
        text += f'static const u16 sTerrariumFlowerFrame{frame}[] = {{\n'
        for i in range(0,len(vals),8): text += '    '+', '.join(f'0x{v:04X}' for v in vals[i:i+8])+',\n'
        text += '};\n'
    return text.encode()
