#include "global.h"
#include "constants/abilities.h"
#include "constants/flags.h"
#include "constants/items.h"
#include "constants/moves.h"
#include "constants/region_map_sections.h"
#include "constants/rgb.h"
#include "event_data.h"
#include "random.h"

#include "rogue_baked.h"
#include "rogue_colour_utils.h"
#include "rogue_gifts.h"
#include "rogue_hub.h"
#include "rogue_pokedex.h"
#include "rogue_query.h"
#include "rogue_quest.h"
#include "rogue_save.h"

struct CustomTrainerData
{
    u8 const* name;
    u32 trainerId;
    u8 trainerColour;
};

struct CustomMonData
{
    u8 const* nickname;
    u16 const* moves;
    u16 const* abilities;
    u32 otId;
    u16 movesCount;
    u16 customTrainerId;
    u16 species;
    u16 pokeball;
    u16 heldItem;
    u16 isShiny : 1;
};

static u8 const sRarityToCustomTrainerIndex[] = 
{
    [UNIQUE_RARITY_COMMON]      = CUSTOM_TRAINER_COMMON,
    [UNIQUE_RARITY_RARE]        = CUSTOM_TRAINER_RARE,
    [UNIQUE_RARITY_EPIC]        = CUSTOM_TRAINER_EPIC,
    [UNIQUE_RARITY_EXOTIC]      = CUSTOM_TRAINER_EXOTIC,
    [UNIQUE_RARITY_LEGENDARY]   = CUSTOM_TRAINER_LEGEND,
};

static u16 const sDynamicCustomMonAbilities[] = 
{
#ifdef ROGUE_EXPANSION
    ABILITY_GOOD_AS_GOLD,
    ABILITY_WATER_ABSORB,
    ABILITY_VOLT_ABSORB,
    ABILITY_FLASH_FIRE,
    ABILITY_SPEED_BOOST,
    ABILITY_ADAPTABILITY,
    ABILITY_INTIMIDATE,
    ABILITY_DRIZZLE,
    ABILITY_DROUGHT,
    ABILITY_SNOW_WARNING,
    ABILITY_SAND_STREAM,
    ABILITY_QUICK_DRAW,
    ABILITY_NEUTRALIZING_GAS,
    ABILITY_ELECTRIC_SURGE,
    ABILITY_PSYCHIC_SURGE,
    ABILITY_MISTY_SURGE,
    ABILITY_GRASSY_SURGE,
    ABILITY_PROTEAN,
    ABILITY_MAGIC_BOUNCE,
    ABILITY_MOXIE,
    ABILITY_ILLUSION,
    ABILITY_REGENERATOR,
    ABILITY_SUPER_LUCK,
    ABILITY_CONTRARY,
    ABILITY_NO_GUARD,
    ABILITY_SKILL_LINK,
    ABILITY_SHELL_ARMOR,
    ABILITY_GUTS,
    ABILITY_THICK_FAT,
    ABILITY_HUGE_POWER,
    ABILITY_SERENE_GRACE,
    ABILITY_BATTLE_ARMOR,
    ABILITY_WEAK_ARMOR,
    ABILITY_TOXIC_DEBRIS,
    ABILITY_UNSEEN_FIST,
    ABILITY_GORILLA_TACTICS,
    ABILITY_TOUGH_CLAWS,
    ABILITY_FULL_METAL_BODY,
    ABILITY_TECHNICIAN,
    ABILITY_EMERGENCY_EXIT,
    ABILITY_PRANKSTER,
    ABILITY_POWER_OF_ALCHEMY,
    ABILITY_OPPORTUNIST,
    ABILITY_LEVITATE,
    ABILITY_MULTISCALE,
    ABILITY_COSTAR,
    ABILITY_POISON_HEAL,
    ABILITY_NEUROFORCE,
    ABILITY_MOODY,
    ABILITY_HOSPITALITY,
    ABILITY_COMATOSE,
    ABILITY_BERSERK,
    ABILITY_SIMPLE,
    ABILITY_UNAWARE,
    ABILITY_HARVEST,
    ABILITY_MOLD_BREAKER,
    ABILITY_SHEER_FORCE,
    ABILITY_OVERCOAT,
    ABILITY_IRON_BARBS,
    ABILITY_DEFIANT,
    ABILITY_STALL,
    ABILITY_SNIPER,
    ABILITY_MULTITYPE,
    ABILITY_SHARPNESS,
    ABILITY_PURIFYING_SALT,
    ABILITY_EARTH_EATER,
    ABILITY_WIND_RIDER,
    ABILITY_WELL_BAKED_BODY,
    ABILITY_THERMAL_EXCHANGE,
    ABILITY_ROCKY_PAYLOAD,
    ABILITY_DRAGONS_MAW,
    ABILITY_TRANSISTOR,
    ABILITY_PUNK_ROCK,
    ABILITY_MEGA_LAUNCHER,
    ABILITY_STEELWORKER,
    ABILITY_ARMOR_TAIL,
    ABILITY_QUEENLY_MAJESTY,
    ABILITY_GUARD_DOG,
    ABILITY_MAGIC_GUARD,
    ABILITY_TINTED_LENS,
    ABILITY_STRONG_JAW,
    ABILITY_IRON_FIST,
    ABILITY_RECKLESS,
    ABILITY_ANALYTIC,
    ABILITY_DOWNLOAD,
    ABILITY_SCRAPPY,
    ABILITY_FUR_COAT,
    ABILITY_ICE_SCALES,
    ABILITY_MIRROR_ARMOR,
    ABILITY_STORM_DRAIN,
    ABILITY_LIGHTNING_ROD,
    ABILITY_SAP_SIPPER,
    ABILITY_PIXILATE,
    ABILITY_AERILATE,
    ABILITY_REFRIGERATE,
    ABILITY_GALVANIZE,
    ABILITY_LIQUID_VOICE,
    ABILITY_DAUNTLESS_SHIELD,
    ABILITY_INTREPID_SWORD,
    ABILITY_CHILLING_NEIGH,
    ABILITY_GRIM_NEIGH,
    ABILITY_SUPREME_OVERLORD
#else
    ABILITY_DRIZZLE,
    ABILITY_SPEED_BOOST,
    ABILITY_BATTLE_ARMOR,
    ABILITY_LIMBER,
    ABILITY_SAND_VEIL,
    ABILITY_STATIC,
    ABILITY_VOLT_ABSORB,
    ABILITY_WATER_ABSORB,
    ABILITY_CLOUD_NINE,
    ABILITY_COMPOUND_EYES,
    ABILITY_COLOR_CHANGE,
    ABILITY_FLASH_FIRE,
    ABILITY_SHIELD_DUST,
    ABILITY_SUCTION_CUPS,
    ABILITY_INTIMIDATE,
    ABILITY_SHADOW_TAG,
    ABILITY_ROUGH_SKIN,
    ABILITY_LEVITATE,
    ABILITY_EFFECT_SPORE,
    ABILITY_CLEAR_BODY,
    ABILITY_SERENE_GRACE,
    ABILITY_SWIFT_SWIM,
    ABILITY_CHLOROPHYLL,
    ABILITY_HUGE_POWER,
    ABILITY_INNER_FOCUS,
    ABILITY_SOUNDPROOF,
    ABILITY_RAIN_DISH,
    ABILITY_SAND_STREAM,
    ABILITY_PRESSURE,
    ABILITY_THICK_FAT,
    ABILITY_FLAME_BODY,
    ABILITY_RUN_AWAY,
    ABILITY_PICKUP,
    ABILITY_HUSTLE,
    ABILITY_CUTE_CHARM,
    ABILITY_SHED_SKIN,
    ABILITY_GUTS,
    ABILITY_MARVEL_SCALE,
    ABILITY_ROCK_HEAD,
    ABILITY_DROUGHT,
    ABILITY_WHITE_SMOKE,
    ABILITY_PURE_POWER,
    ABILITY_SHELL_ARMOR,
    ABILITY_AIR_LOCK,
#endif
};

static u16 const sDynamicCustomMonMoves[] = 
{
#ifdef ROGUE_EXPANSION
    MOVE_HYDRO_STEAM,
    MOVE_CHILLING_WATER,
    MOVE_TORCH_SONG,
    MOVE_JET_PUNCH,
    MOVE_STONE_AXE,
    MOVE_THUNDEROUS_KICK,
    MOVE_BOOMBURST,
    MOVE_SURGING_STRIKES,
    MOVE_PARTING_SHOT,
    MOVE_GRASSY_GLIDE,
    MOVE_DYNAMAX_CANNON,
    MOVE_STOMPING_TANTRUM,
    MOVE_BANEFUL_BUNKER,
    MOVE_DIAMOND_STORM,
    MOVE_PLAY_ROUGH,
    MOVE_FREEZE_DRY,
    MOVE_PHANTOM_FORCE,
    MOVE_V_CREATE,
    MOVE_SECRET_SWORD,
    MOVE_FOCUS_BLAST,
    MOVE_SPORE,
    MOVE_GUNK_SHOT,
    MOVE_BRAVE_BIRD,
    MOVE_CLOSE_COMBAT,
    MOVE_HURRICANE,
    MOVE_SLUDGE_BOMB,
    MOVE_HEADLONG_RUSH,
    MOVE_LEAF_BLADE,
    MOVE_METEOR_MASH,
    MOVE_EARTH_POWER,
    MOVE_SKILL_SWAP,
    MOVE_FAKE_OUT,
    MOVE_EXTREME_SPEED,
    MOVE_ROCK_SLIDE,
    MOVE_RAPID_SPIN,
    MOVE_MEGAHORN,
    MOVE_WISH,
    MOVE_THUNDER,
    MOVE_POWER_GEM,
    MOVE_THUNDERCLAP,
    MOVE_GIGATON_HAMMER,
    MOVE_SALT_CURE,
    MOVE_WICKED_BLOW,
    MOVE_POLTERGEIST,
    MOVE_METEOR_BEAM,
    MOVE_SPIRIT_BREAK,
    MOVE_RECOVER,
    MOVE_NO_RETREAT,
    MOVE_LUNGE,
    MOVE_METRONOME,
    MOVE_TOPSY_TURVY,
    MOVE_QUIVER_DANCE,
    MOVE_BATON_PASS,
    MOVE_MOONGEIST_BEAM,
    MOVE_MAGMA_STORM,
    MOVE_RUINATION,
    MOVE_REVELATION_DANCE,
    MOVE_SUCKER_PUNCH,
    MOVE_COLLISION_COURSE,
    MOVE_ROLLOUT,
    MOVE_FURY_CUTTER,
    MOVE_LAST_RESPECTS,
    MOVE_ACROBATICS,
    MOVE_BUG_BUZZ,
    MOVE_POWER_TRIP,
    MOVE_WEATHER_BALL,
    MOVE_BODY_PRESS,
    MOVE_POWER_UP_PUNCH,
    MOVE_FIRE_LASH,
    MOVE_MYSTICAL_FIRE,
    MOVE_FLAME_CHARGE,
    MOVE_SHADOW_BALL,
    MOVE_BRINE,
    MOVE_IRON_HEAD,
    MOVE_TRAILBLAZE,
    MOVE_POLLEN_PUFF,
    MOVE_NUZZLE,
    MOVE_FLASH_CANNON,
    MOVE_PSYSHOCK,
    MOVE_STORED_POWER,
    MOVE_ICY_WIND,
    MOVE_AVALANCHE,
    MOVE_OVERHEAT,
    MOVE_SCALE_SHOT,
    MOVE_SNARL,
    MOVE_LIQUIDATION,
    MOVE_MUDDY_WATER,
    MOVE_ACID_SPRAY,
    MOVE_CLEAR_SMOG,
    MOVE_BULLDOZE,
    MOVE_ROCK_TOMB,
    MOVE_POUNCE,
    MOVE_GIGA_DRAIN,
    MOVE_SUPERCELL_SLAM,
    MOVE_HEAVY_SLAM,
    MOVE_ELECTROWEB,
    MOVE_ENCORE,
    MOVE_ZEN_HEADBUTT,
    MOVE_DISABLE,
    MOVE_TORMENT,
    MOVE_TRIPLE_AXEL,
    MOVE_TOXIC_SPIKES,
    MOVE_DRAGON_RUSH,
    MOVE_DRACO_METEOR,
    MOVE_NIGHT_SLASH,
    MOVE_GRAVITY,
    MOVE_DARK_PULSE,
    MOVE_PAIN_SPLIT,
    MOVE_MOONBLAST,
    MOVE_MAGIC_COAT,
    MOVE_BURNING_JEALOUSY,
    MOVE_ALLURING_VOICE,
    MOVE_PSYCHIC_NOISE,
    MOVE_TEMPER_FLARE,
    MOVE_STRENGTH_SAP,
    MOVE_YAWN,
    MOVE_PERISH_SONG,
    MOVE_COURT_CHANGE,
    MOVE_METAL_BURST,
    MOVE_INFESTATION,
    MOVE_ZAP_CANNON,
    MOVE_ERUPTION,
    MOVE_SIGNAL_BEAM,
    MOVE_HORN_LEECH,
    MOVE_VACUUM_WAVE,
    MOVE_MIRROR_COAT,
    MOVE_BELLY_DRUM,
    MOVE_SCORCHING_SANDS,
    MOVE_TRICK_ROOM,
    MOVE_NASTY_PLOT,
    MOVE_U_TURN,
    MOVE_DRAGON_DANCE,
    MOVE_CALM_MIND,
    MOVE_KNOCK_OFF,
    MOVE_ANCIENT_POWER,
    MOVE_SWORDS_DANCE,
    MOVE_SUBSTITUTE,
    MOVE_BODY_SLAM,
    MOVE_FLIP_TURN,
    MOVE_APPLE_ACID,
    MOVE_VOLT_SWITCH,
    MOVE_BREAKING_SWIPE,
    MOVE_FOUL_PLAY,
    MOVE_DRAINING_KISS,
    MOVE_HEX,
    MOVE_GYRO_BALL,
    MOVE_TAUNT,
    MOVE_LEECH_SEED,
    MOVE_STICKY_WEB,
    MOVE_STEALTH_ROCK,
    MOVE_SPIKES,
    MOVE_HAZE,
    MOVE_DESTINY_BOND,
    MOVE_FELL_STINGER,
    MOVE_WILL_O_WISP,
    MOVE_AQUA_RING,
    MOVE_CHARGE,
    MOVE_CHARM,
    MOVE_TOXIC,
    MOVE_ROCK_POLISH,
    MOVE_CURSE,
    MOVE_CONFUSE_RAY,
    MOVE_THUNDER_WAVE,
    MOVE_MAGNET_RISE,
    MOVE_SWEET_KISS,
#else
    MOVE_PAY_DAY,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_THUNDER_PUNCH,
    MOVE_SWORDS_DANCE,
    MOVE_FLY,
    MOVE_BODY_SLAM,
    MOVE_SURF,
    MOVE_ICE_BEAM,
    MOVE_COUNTER,
    MOVE_DRAGON_RAGE,
    MOVE_EARTHQUAKE,
    MOVE_PSYCHIC,
    MOVE_METRONOME,
    MOVE_MIRROR_MOVE,
    MOVE_FIRE_BLAST,
    MOVE_SOFT_BOILED,
    MOVE_TRANSFORM,
    MOVE_SUBSTITUTE,
    MOVE_CURSE,
    MOVE_AEROBLAST,
    MOVE_MACH_PUNCH,
    MOVE_BELLY_DRUM,
    MOVE_ZAP_CANNON,
    MOVE_OUTRAGE,
    MOVE_GIGA_DRAIN,
    MOVE_ROLLOUT,
    MOVE_SACRED_FIRE,
    MOVE_MEGAHORN,
    MOVE_SYNTHESIS,
    MOVE_CRUNCH,
    MOVE_EXTREME_SPEED,
    MOVE_ANCIENT_POWER,
    MOVE_SHADOW_BALL,
    MOVE_FUTURE_SIGHT,
    MOVE_FAKE_OUT,
    MOVE_UPROAR,
    MOVE_WILL_O_WISP,
    MOVE_WISH,
    MOVE_ASSIST,
    MOVE_SUPERPOWER,
    MOVE_MAGIC_COAT,
    MOVE_BRICK_BREAK,
    MOVE_KNOCK_OFF,
    MOVE_SKILL_SWAP,
    MOVE_LUSTER_PURGE,
    MOVE_HYPER_VOICE,
    MOVE_BLAST_BURN,
    MOVE_HYDRO_CANNON,
    MOVE_OVERHEAT,
    MOVE_SIGNAL_BEAM,
    MOVE_AERIAL_ACE,
    MOVE_ICICLE_SPEAR,
    MOVE_FRENZY_PLANT,
    MOVE_BULK_UP,
    MOVE_VOLT_TACKLE,
    MOVE_CALM_MIND,
    MOVE_DRAGON_DANCE,
    MOVE_PSYCHO_BOOST,
    MOVE_ROCK_BLAST,
    MOVE_ERUPTION,
    MOVE_PERISH_SONG,
    MOVE_PAIN_SPLIT,
#endif
};

STATIC_ASSERT(ARRAY_COUNT(sDynamicCustomMonAbilities) <= 127, SizeOfDynamicCustomMonAbilities);
#ifdef ROGUE_EXPANSION
STATIC_ASSERT(ARRAY_COUNT(sDynamicCustomMonAbilities) == 102, DynamicStandardAbilityPoolAuditCount);
#endif
STATIC_ASSERT(ARRAY_COUNT(sDynamicCustomMonAbilities) >= 4, LegendaryAbilitySeedHasFourCandidates);
STATIC_ASSERT(NUM_ABILITY_SLOTS < 4, LegendaryAbilitySeedCanAvoidNativeSlots);
#define DYNAMIC_MOVE_POOL_CAPACITY 180
#define DYNAMIC_MOVE_SELECTION_CAPACITY (1 << 14)
#define DYNAMIC_MOVE_PAIR_COUNT ((DYNAMIC_MOVE_POOL_CAPACITY * (DYNAMIC_MOVE_POOL_CAPACITY - 1)) / 2)
#define DYNAMIC_MOVE_PAIR_CODE_START (DYNAMIC_MOVE_POOL_CAPACITY + 1)
#define DYNAMIC_TYPED_MOVE_SELECTION_STRIDE (DYNAMIC_MOVE_POOL_CAPACITY + 1)

STATIC_ASSERT(ARRAY_COUNT(sDynamicCustomMonMoves) <= DYNAMIC_MOVE_POOL_CAPACITY, SizeOfDynamicCustomMonMoves);
STATIC_ASSERT(DYNAMIC_MOVE_PAIR_CODE_START + DYNAMIC_MOVE_PAIR_COUNT <= DYNAMIC_MOVE_SELECTION_CAPACITY, DynamicMoveSelectionFits14Bits);
STATIC_ASSERT(NUMBER_OF_MON_TYPES * 4 * DYNAMIC_TYPED_MOVE_SELECTION_STRIDE <= DYNAMIC_MOVE_SELECTION_CAPACITY, TypedUniqueMoveSelectionFits14Bits);
STATIC_ASSERT(ABILITIES_COUNT <= 1024, DynamicUniqueAbilityFits10Bits);

#define DYNAMIC_UNIQUE_ABILITY_MIN ABILITY_STRONG_WINDS
#define DYNAMIC_UNIQUE_ABILITY_MAX ABILITY_GUIDING_FLAMES

// These are the only custom abilities which are not safe and useful on an
// arbitrary generated Pokemon. Keep this list explicit so new abilities do
// not silently enter the serialized generation pool without an audit.
static const u16 sExcludedDynamicUniqueAbilities[] =
{
    ABILITY_UNUSED_320,
    ABILITY_PASSIVE_INCOME,
    ABILITY_DEBUG,
    ABILITY_BOUNTY,
    ABILITY_GRAND_REVEAL,
    ABILITY_ULTRA_FALLOUT,
    ABILITY_ULTRA_SWOLE,
    ABILITY_ULTRA_STRUT,
    ABILITY_ULTRA_CONDUCTOR,
    ABILITY_ULTRA_ASCENT,
    ABILITY_ULTRA_EDGE,
    ABILITY_ULTRA_DEVOUR,
    ABILITY_ULTRA_VENIN,
    ABILITY_ULTRA_INJECTION,
    ABILITY_ULTRA_BASTION,
    ABILITY_ULTRA_DETONATION,
    ABILITY_UNSPEAKABLE,
    ABILITY_BLACK_ICE,
    ABILITY_PRIMAL_ECHO,
    ABILITY_PRIMAL_PARASITE,
    ABILITY_PRIMAL_WRAITH,
    ABILITY_PRIMAL_MOLTING,
    ABILITY_PRIMAL_CURRENT,
    ABILITY_SINGULARITY_DRIVE,
    ABILITY_SINGULARITY_TARGETING,
    ABILITY_SINGULARITY_IMPACT,
    ABILITY_SINGULARITY_AIRSPACE,
    ABILITY_SINGULARITY_REACTOR,
    ABILITY_SINGULARITY_OVERLOAD,
    ABILITY_PRIMAL_TIRANNY,
    ABILITY_SINGULARITY_EDGE,
    ABILITY_SINGULARITY_PRISM,
    ABILITY_SINGULARITY_ARRAY,
    ABILITY_PRIMAL_CREST,
    ABILITY_PRIMAL_THUNDER,
    ABILITY_COUNTERPUNCH,
    ABILITY_RAPID_REPLICA,
    ABILITY_COLOSSAL,
    ABILITY_TRASH_ALCHEMY,
    ABILITY_POTENTIAL,
    ABILITY_WHY_NOT,
    ABILITY_PRIMAL_ONSLAUGHT,
    ABILITY_SINGULARITY_CRASH,
    ABILITY_HIDDEN_STASH,
};

#define DYNAMIC_UNIQUE_ABILITY_COUNT \
    (DYNAMIC_UNIQUE_ABILITY_MAX - DYNAMIC_UNIQUE_ABILITY_MIN + 1 - ARRAY_COUNT(sExcludedDynamicUniqueAbilities))

STATIC_ASSERT(DYNAMIC_UNIQUE_ABILITY_COUNT == 564, DynamicUniqueAbilityPoolAuditCount);

bool8 RogueGift_IsDynamicUniqueAbilityEligible(u16 ability)
{
    u16 i;

    if(ability < DYNAMIC_UNIQUE_ABILITY_MIN || ability > DYNAMIC_UNIQUE_ABILITY_MAX)
        return FALSE;

    for(i = 0; i < ARRAY_COUNT(sExcludedDynamicUniqueAbilities); ++i)
    {
        if(sExcludedDynamicUniqueAbilities[i] == ability)
            return FALSE;
    }

    return TRUE;
}

u16 RogueGift_GetDynamicUniqueAbilityPoolCount(void)
{
    return DYNAMIC_UNIQUE_ABILITY_COUNT;
}

#ifdef ROGUE_EXPANSION
// A synergy move is derived from the serialized unique ability rather than
// stored separately. Entries are therefore part of the dynamic-mon format and
// must be treated as compatibility-sensitive after the first public release.
static const u16 sDynamicUniqueAbilitySynergyMoves[ABILITIES_COUNT] =
{
    [ABILITY_THERMAL_LIFT] = MOVE_MYSTICAL_FIRE,
    [ABILITY_VINE_LASH] = MOVE_GIGA_DRAIN,
    [ABILITY_SHELL_FORMATION] = MOVE_CHILLING_WATER,
    [ABILITY_TOXIC_TANDEM] = MOVE_SLUDGE_BOMB,
    [ABILITY_GNAW_DOWN] = MOVE_CRUNCH,
    [ABILITY_SOFT_BODY] = MOVE_SING,
    [ABILITY_IMMOLATE] = MOVE_BODY_SLAM,
    [ABILITY_SPIRAL_GAZE] = MOVE_HYPNOSIS,
    [ABILITY_CHAMPION] = MOVE_JET_PUNCH,
    [ABILITY_VOLCANIC_RAGE] = MOVE_MYSTICAL_FIRE,
    [ABILITY_STRIKE_FEAR] = MOVE_GLARE,
    [ABILITY_AFTERSHOCK] = MOVE_EARTH_POWER,
    [ABILITY_SIGHTING_SYSTEM] = MOVE_ZAP_CANNON,
    [ABILITY_DUELIST] = MOVE_LEAF_BLADE,
    [ABILITY_DREAM_SEQUENCE] = MOVE_HYPNOSIS,
    [ABILITY_AQUATIC_ARMOR] = MOVE_CHILLING_WATER,
    [ABILITY_MULTITASK] = MOVE_TAUNT,
    [ABILITY_BONE_KEEPER] = MOVE_SHADOW_BONE,
    [ABILITY_STRIKER] = MOVE_THUNDEROUS_KICK,
    [ABILITY_UPPERCUT] = MOVE_JET_PUNCH,
    [ABILITY_VOLT_BREAK] = MOVE_BOOMBURST,
    [ABILITY_INTENSIVE_CARE] = MOVE_HELPING_HAND,
    [ABILITY_STARLOCK] = MOVE_RECOVER,
    [ABILITY_IMPROV] = MOVE_TAUNT,
    [ABILITY_SWEET_NOTHINGS] = MOVE_DRAINING_KISS,
    [ABILITY_PRIMORDIAL_WAKE] = MOVE_CHILLING_WATER,
    [ABILITY_EXHUMED] = MOVE_POWER_GEM,
    [ABILITY_DEEP_SLEEP] = MOVE_YAWN,
    [ABILITY_ONE_MIND] = MOVE_PSYSHOCK,
    [ABILITY_SKY_TYRANT] = MOVE_POWER_GEM,
    [ABILITY_VERDANT_HAVEN] = MOVE_TAUNT,
    [ABILITY_BLINDING_SMOKE] = MOVE_MYSTICAL_FIRE,
    [ABILITY_GUIDING_FLAMES] = MOVE_SHADOW_BALL,
    [ABILITY_DEATH_ROLL] = MOVE_CRUNCH,
    [ABILITY_NOCTURNAL] = MOVE_HYPNOSIS,
    [ABILITY_FORMATION_FIGHTER] = MOVE_TAUNT,
    [ABILITY_BEACON] = MOVE_DARK_PULSE,
    [ABILITY_FESTIVAL] = MOVE_QUIVER_DANCE,
    [ABILITY_HANDYWORK] = MOVE_BODY_SLAM,
    [ABILITY_ROYAL_DECREE] = MOVE_TAUNT,
    [ABILITY_HEXCRAFT] = MOVE_TAUNT,
    [ABILITY_FORTIFIED_SPIN] = MOVE_PROTECT,
    [ABILITY_BURROW] = MOVE_DIG,
    [ABILITY_TOXIC_MONSOON] = MOVE_SLUDGE_BOMB,
    [ABILITY_COLD_READ] = MOVE_FOCUS_ENERGY,
    [ABILITY_PLOW_THROUGH] = MOVE_EARTH_POWER,
    [ABILITY_DELIVERY_BAG] = MOVE_TAUNT,
    [ABILITY_SCRAP_DRAFT] = MOVE_WHIRLWIND,
    [ABILITY_INFERNAL_RAGE] = MOVE_MYSTICAL_FIRE,
    [ABILITY_RUMBLE_ROLL] = MOVE_EARTH_POWER,
    [ABILITY_STORYBOARD] = MOVE_TAUNT,
    [ABILITY_BREAKDANCE] = MOVE_THUNDEROUS_KICK,
    [ABILITY_DYNAMO_FISTS] = MOVE_THUNDER,
    [ABILITY_SUNSTALKER] = MOVE_LEAF_BLADE,
    [ABILITY_FLASH_FIRESTORM] = MOVE_THUNDEROUS_KICK,
    [ABILITY_FOREST_AMBUSH] = MOVE_TAUNT,
    [ABILITY_SOLARBOOST] = MOVE_MYSTICAL_FIRE,
    [ABILITY_BRAVERY] = MOVE_BRAVE_BIRD,
    [ABILITY_WATER_GLIDE] = MOVE_BRAVE_BIRD,
    [ABILITY_DISTORTION] = MOVE_UPROAR,
    [ABILITY_VICEJAW] = MOVE_BITE,
    [ABILITY_EMPTY_HAND] = MOVE_JET_PUNCH,
    [ABILITY_CHARGED_CRY] = MOVE_BOOMBURST,
    [ABILITY_CALL] = MOVE_TAUNT,
    [ABILITY_RESPONSE] = MOVE_TAUNT,
    [ABILITY_ACID_REFLUX] = MOVE_STOCKPILE,
    [ABILITY_NEEDLEBURST] = MOVE_BODY_SLAM,
    [ABILITY_MOON_TOTEM] = MOVE_DARK_PULSE,
    [ABILITY_SUN_TOTEM] = MOVE_MYSTICAL_FIRE,
    [ABILITY_ELECTROCYTES] = MOVE_THUNDER,
    [ABILITY_PETRIFYING_ROOTS] = MOVE_BODY_SLAM,
    [ABILITY_VENDETTA] = MOVE_LEAF_BLADE,
    [ABILITY_SIDEWINDER] = MOVE_CRUNCH,
    [ABILITY_FOSSIL_DRILL] = MOVE_POWER_GEM,
    [ABILITY_STEALTH] = MOVE_SHADOW_FORCE,
    [ABILITY_TROPICAL_CANOPY] = MOVE_BRAVE_BIRD,
    [ABILITY_ODD_SIGNAL] = MOVE_TAUNT,
    [ABILITY_HEARTTHROB] = MOVE_DRAINING_KISS,
    [ABILITY_PREDATOR] = MOVE_BRAVE_BIRD,
    [ABILITY_WIND_CHIMES] = MOVE_BOOMBURST,
    [ABILITY_ABYSSAL_MAW] = MOVE_CRUNCH,
    [ABILITY_WISHMAKER] = MOVE_WISH,
    [ABILITY_ADRENALINE] = MOVE_JET_PUNCH,
    [ABILITY_UPROOT] = MOVE_GIGA_DRAIN,
    [ABILITY_SPELLFIST] = MOVE_JET_PUNCH,
    [ABILITY_AERIAL_ASSAULT] = MOVE_BRAVE_BIRD,
    [ABILITY_SPILLWAY] = MOVE_CHILLING_WATER,
    [ABILITY_CALL_ALLIES] = MOVE_BOOMBURST,
    [ABILITY_X_RAY_JAWS] = MOVE_CRUNCH,
    [ABILITY_REGAL_DECREE] = MOVE_TAUNT,
    [ABILITY_HIVE_COMMAND] = MOVE_ATTACK_ORDER,
    [ABILITY_UNDERTOW] = MOVE_CHILLING_WATER,
    [ABILITY_BUNNY_EARS] = MOVE_BODY_SLAM,
    [ABILITY_CHATTERBOX] = MOVE_BRAVE_BIRD,
    [ABILITY_SANDMAN] = MOVE_EARTH_POWER,
    [ABILITY_KOMBO] = MOVE_SLUDGE_BOMB,
    [ABILITY_SUBMERGE] = MOVE_DIVE,
    [ABILITY_SYLVAN_SURGE] = MOVE_GIGA_DRAIN,
    [ABILITY_SHORT_CIRCUIT] = MOVE_THUNDER,
    [ABILITY_STILL_MIND] = MOVE_CHILLING_WATER,
    [ABILITY_BURNING_HEART] = MOVE_MYSTICAL_FIRE,
    [ABILITY_IRON_WILL] = MOVE_GIGA_DRAIN,
    [ABILITY_TIME_RIFT] = MOVE_ROAR_OF_TIME,
    [ABILITY_MAGMA_SEAL] = MOVE_MYSTICAL_FIRE,
    [ABILITY_DARK_DIMENSION] = MOVE_SHADOW_FORCE,
    [ABILITY_DRIFT_SONG] = MOVE_CHILLING_WATER,
    [ABILITY_TIDEBORN] = MOVE_TAUNT,
    [ABILITY_BLOOM_BURST] = MOVE_FLOWER_SHIELD,
    [ABILITY_NATURAL_FLOW] = MOVE_GIGA_DRAIN,
    [ABILITY_WILD_EMBER] = MOVE_MYSTICAL_FIRE,
    [ABILITY_RUSH_CURRENT] = MOVE_CHILLING_WATER,
    [ABILITY_SOARING_GALE] = MOVE_HURRICANE,
    [ABILITY_PSYCHIC_PARRY] = MOVE_LEAF_BLADE,
    [ABILITY_TERRAFORM] = MOVE_EARTH_POWER,
    [ABILITY_DEMOLITION] = MOVE_JET_PUNCH,
    [ABILITY_THROWING_FORM] = MOVE_WHIRLWIND,
    [ABILITY_WEB_TAILOR] = MOVE_LEAF_BLADE,
    [ABILITY_TUFTED_AWAY] = MOVE_TAUNT,
    [ABILITY_PRETTY_PETALS] = MOVE_TAUNT,
    [ABILITY_TIDECALL] = MOVE_PROTECT,
    [ABILITY_SPRING_CLEAN] = MOVE_SURGING_STRIKES,
    [ABILITY_KNIGHTLY] = MOVE_BODY_SLAM,
    [ABILITY_MAELSTROM] = MOVE_RECOVER,
    [ABILITY_HEALING_CURRENT] = MOVE_RECOVER,
    [ABILITY_LIVEWIRE_NEST] = MOVE_BUG_BUZZ,
    [ABILITY_PYROMANCY] = MOVE_MYSTICAL_FIRE,
    [ABILITY_ROCKET_FIST] = MOVE_JET_PUNCH,
    [ABILITY_POWER_PLAY] = MOVE_SUCKER_PUNCH,
    [ABILITY_WARPATH] = MOVE_BRAVE_BIRD,
    [ABILITY_RADIANT] = MOVE_MYSTICAL_FIRE,
    [ABILITY_FLOWING_LESSON] = MOVE_CHILLING_WATER,
    [ABILITY_RESOLUTE_BLADE] = MOVE_CLOSE_COMBAT,
    [ABILITY_WHITE_INFERNO] = MOVE_MYSTICAL_FIRE,
    [ABILITY_BLACK_THUNDER] = MOVE_THUNDER,
    [ABILITY_ABSOLUTE_ZERO] = MOVE_FREEZE_DRY,
    [ABILITY_OPENING_VERSE] = MOVE_BOOMBURST,
    [ABILITY_LIKE_WATER] = MOVE_CLOSE_COMBAT,
    [ABILITY_MODULAR] = MOVE_TECHNO_BLAST,
    [ABILITY_FINAL_STEP] = MOVE_BODY_SLAM,
    [ABILITY_BRAMBLE_GUARD] = MOVE_SPIKY_SHIELD,
    [ABILITY_SPELLBOOK] = MOVE_TAUNT,
    [ABILITY_NINJA_TOOLS] = MOVE_WATER_SHURIKEN,
    [ABILITY_WORK_CREW] = MOVE_DIG,
    [ABILITY_DUSTSTORM] = MOVE_SPORE,
    [ABILITY_FLOWER_RITUAL] = MOVE_TAUNT,
    [ABILITY_WINDSURGE] = MOVE_BRAVE_BIRD,
    [ABILITY_HAUTE_COUTURE] = MOVE_BODY_SLAM,
    [ABILITY_SCREEN_TEST] = MOVE_TAUNT,
    [ABILITY_ATOMIZER] = MOVE_RECOVER,
    [ABILITY_INVERSION] = MOVE_TAUNT,
    [ABILITY_ALGAE_BLOOM] = MOVE_SLUDGE_BOMB,
    [ABILITY_PRIMAL_STORM] = MOVE_CRUNCH,
    [ABILITY_POLAR_BEACON] = MOVE_POWER_GEM,
    [ABILITY_SERENE_VOICE] = MOVE_BOOMBURST,
    [ABILITY_SWITCHBOARD] = MOVE_NUZZLE,
    [ABILITY_MOONGLASS] = MOVE_TAUNT,
    [ABILITY_GRAVE_GROVE] = MOVE_BODY_SLAM,
    [ABILITY_KEYRING] = MOVE_TAUNT,
    [ABILITY_RESONANCE] = MOVE_BOOMBURST,
    [ABILITY_HOT_SHELLS] = MOVE_BOOMBURST,
    [ABILITY_DYNAMO] = MOVE_CHARGE,
    [ABILITY_FROSTBITE_RITUAL] = MOVE_TAUNT,
    [ABILITY_POLLINATE] = MOVE_TAUNT,
    [ABILITY_CENTER_STAGE] = MOVE_QUIVER_DANCE,
    [ABILITY_TRAILBREAKER] = MOVE_EARTH_POWER,
    [ABILITY_ROYAL_GARDEN] = MOVE_BODY_SLAM,
    [ABILITY_BEGUILE] = MOVE_ENCORE,
    [ABILITY_FLOWER_CHAIN] = MOVE_RECOVER,
    [ABILITY_MANTIS_MIMICRY] = MOVE_BUG_BUZZ,
    [ABILITY_SPORELIGHT] = MOVE_RECOVER,
    [ABILITY_BEAR_HUG] = MOVE_BODY_SLAM,
    [ABILITY_RKS_RELAY] = MOVE_U_TURN,
    [ABILITY_PSYCHIC_MAW] = MOVE_CRUNCH,
    [ABILITY_ELEMENTALIST] = MOVE_MYSTICAL_FIRE,
    [ABILITY_WAR_CHOIR] = MOVE_BOOMBURST,
    [ABILITY_IMPACT] = MOVE_JET_PUNCH,
    [ABILITY_SEEDCLOUD] = MOVE_SPORE,
    [ABILITY_RIPJAW] = MOVE_CRUNCH,
    [ABILITY_QUICKSAND] = MOVE_EARTH_POWER,
    [ABILITY_OCTOLOCK] = MOVE_OCTOLOCK,
    [ABILITY_TEA_SERVICE] = MOVE_TEATIME,
    [ABILITY_BAD_INFLUENCE] = MOVE_TAUNT,
    [ABILITY_BAG_OF_TRICKS] = MOVE_DARK_PULSE,
    [ABILITY_HECKLER] = MOVE_BOOMBURST,
    [ABILITY_WAILING_REEF] = MOVE_BOOMBURST,
    [ABILITY_VARIETY_ACT] = MOVE_TAUNT,
    [ABILITY_SPACE_RIFT] = MOVE_SPACIAL_REND,
    [ABILITY_FORMATION] = MOVE_NO_RETREAT,
    [ABILITY_SUGAR_COAT] = MOVE_RECOVER,
    [ABILITY_SHORT_FUSE] = MOVE_DARK_PULSE,
    [ABILITY_IRON_STAMP] = MOVE_FLASH_CANNON,
    [ABILITY_EJECT] = MOVE_U_TURN,
    [ABILITY_DRAGONIZE] = MOVE_BODY_SLAM,
    [ABILITY_PIERCING_DRILL] = MOVE_BODY_SLAM,
    [ABILITY_CROWN_OF_FANGS] = MOVE_DRAGON_RUSH,
    [ABILITY_REGAL_AEGIS] = MOVE_TAUNT,
    [ABILITY_BAD_MOUTH] = MOVE_BOOMBURST,
    [ABILITY_JUNGLE_LASH] = MOVE_U_TURN,
    [ABILITY_SHARDSTORM] = MOVE_LEAF_BLADE,
    [ABILITY_DEATH_CURRENT] = MOVE_CHILLING_WATER,
    [ABILITY_HIGH_CLIMBER] = MOVE_BODY_SLAM,
    [ABILITY_BARBED_MONSOON] = MOVE_BODY_SLAM,
    [ABILITY_FALSE_APPLAUSE] = MOVE_BODY_SLAM,
    [ABILITY_DIRGE] = MOVE_BOOMBURST,
    [ABILITY_SHOWSTOPPER] = MOVE_QUIVER_DANCE,
    [ABILITY_FEVER_DREAM] = MOVE_SPORE,
    [ABILITY_FUNERAL_RITE] = MOVE_REVIVAL_BLESSING,
    [ABILITY_CARVING_RUSH] = MOVE_FILLET_AWAY,
    [ABILITY_PHOTOKERATITIS] = MOVE_BODY_SLAM,
    [ABILITY_SWALLOWED] = MOVE_REST,
    [ABILITY_CHEFS_PICK] = MOVE_DRAGON_RUSH,
    [ABILITY_OLIVE_GROVE] = MOVE_GIGA_DRAIN,
    [ABILITY_TEMPERED_EMBER] = MOVE_MYSTICAL_FIRE,
    [ABILITY_TAR_CANNON] = MOVE_CALM_MIND,
    [ABILITY_SOUL_BRAND] = MOVE_DESTINY_BOND,
    [ABILITY_ROADBURN] = MOVE_U_TURN,
    [ABILITY_CAUSTIC_BLOOM] = MOVE_POWER_GEM,
    [ABILITY_WORLD_PRISM] = MOVE_TERA_STARSTORM,
    [ABILITY_PUPPET_MASTER] = MOVE_TAUNT,
    [ABILITY_MEAN_STREAK] = MOVE_SWORDS_DANCE,
    [ABILITY_MALICIOUS_MIND] = MOVE_TAUNT,
    [ABILITY_TOXIC_VANITY] = MOVE_NUZZLE,
    [ABILITY_FAULT_FINDER] = MOVE_EARTH_POWER,
    [ABILITY_ROYAL_TREATMENT] = MOVE_PARTING_SHOT,
    [ABILITY_BRAIN_SURF] = MOVE_THUNDER,
    [ABILITY_SNOWPLOW] = MOVE_FREEZE_DRY,
    [ABILITY_NEST_BOSS] = MOVE_SUCKER_PUNCH,
    [ABILITY_LANAKILA_LAW] = MOVE_ENCORE,
    [ABILITY_RAILGUN_CHARGE] = MOVE_POWER_GEM,
    [ABILITY_FAIRY_TALE] = MOVE_HEALING_WISH,
    [ABILITY_GALARICA_ROUNDS] = MOVE_SHELL_SIDE_ARM,
    [ABILITY_TALL_TALE] = MOVE_DRAGON_HAMMER,
    [ABILITY_FIRE_MANE] = MOVE_MYSTICAL_FIRE,
    [ABILITY_ROLLING_START] = MOVE_ROLLOUT,
    [ABILITY_FUNERAL_DANCE] = MOVE_SHADOW_BONE,
    [ABILITY_MOMENTUM] = MOVE_NIGHT_SLASH,
    [ABILITY_FREESTYLE] = MOVE_JET_PUNCH,
    [ABILITY_PRISM_REFRACTION] = MOVE_PHOTON_GEYSER,
    [ABILITY_ENDLESS_CORE] = MOVE_HYPER_BEAM,
    [ABILITY_BREACH_POINT] = MOVE_U_TURN,
    [ABILITY_SALT_FORTRESS] = MOVE_IRON_DEFENSE,
    [ABILITY_GROUND_FAULT] = MOVE_THUNDER,
    [ABILITY_WITHERING_SCRIPT] = MOVE_RUINATION,
    [ABILITY_SEVERING_RITE] = MOVE_RUINATION,
    [ABILITY_EARTHEN_SEAL] = MOVE_RUINATION,
    [ABILITY_CINDER_EDICT] = MOVE_RUINATION,
    [ABILITY_LAST_POUR] = MOVE_RECOVER,
    [ABILITY_FAMILY_FEUD] = MOVE_SURGING_STRIKES,
    [ABILITY_CRUEL_PREMONITION] = MOVE_FREEZING_GLARE,
    [ABILITY_SPIRIT_FEAST] = MOVE_DARK_PULSE,
};
#endif

enum DynamicSynergyPolicy
{
    DYNAMIC_SYNERGY_POLICY_UNIFORM,
    DYNAMIC_SYNERGY_POLICY_OFFENSE,
};

enum DynamicSynergyProfileId
{
    DYNAMIC_SYNERGY_PROFILE_NONE,
    DYNAMIC_SYNERGY_PROFILE_PUNCH,
    DYNAMIC_SYNERGY_PROFILE_KICK,
    DYNAMIC_SYNERGY_PROFILE_SLICE,
    DYNAMIC_SYNERGY_PROFILE_BITE,
    DYNAMIC_SYNERGY_PROFILE_SOUND,
    DYNAMIC_SYNERGY_PROFILE_DANCE,
    DYNAMIC_SYNERGY_PROFILE_HEALING,
    DYNAMIC_SYNERGY_PROFILE_PIVOT,
    DYNAMIC_SYNERGY_PROFILE_RECOIL,
    DYNAMIC_SYNERGY_PROFILE_MULTI_HIT,
    DYNAMIC_SYNERGY_PROFILE_POWDER,
    DYNAMIC_SYNERGY_PROFILE_PROTECTION,
    DYNAMIC_SYNERGY_PROFILE_PULSE,
    DYNAMIC_SYNERGY_PROFILE_BONE,
    DYNAMIC_SYNERGY_PROFILE_KISS,
    DYNAMIC_SYNERGY_PROFILE_STATUS,
    DYNAMIC_SYNERGY_PROFILE_RECHARGE,
    DYNAMIC_SYNERGY_PROFILE_CONTACT,
    DYNAMIC_SYNERGY_PROFILE_DYNAMO_FISTS,
    DYNAMIC_SYNERGY_PROFILE_FAULT_FINDER,
    DYNAMIC_SYNERGY_PROFILE_ROLLING_START,
    DYNAMIC_SYNERGY_PROFILE_RECOVER_STRENGTH_SAP,
    DYNAMIC_SYNERGY_PROFILE_ENCORE_DISABLE,
    DYNAMIC_SYNERGY_PROFILE_BEGUILE,
    DYNAMIC_SYNERGY_PROFILE_LOW_ACCURACY,
    DYNAMIC_SYNERGY_PROFILE_ALLY_TARGET,
    DYNAMIC_SYNERGY_PROFILE_BITE_OR_CRUNCH,
    DYNAMIC_SYNERGY_PROFILE_ORDER,
    DYNAMIC_SYNERGY_PROFILE_FORCED_SWITCH,
    DYNAMIC_SYNERGY_PROFILE_PSYCHIC_STATUS,
    DYNAMIC_SYNERGY_PROFILE_GHOST_STATUS,
    DYNAMIC_SYNERGY_PROFILE_ATTACK_BOOST,
    DYNAMIC_SYNERGY_PROFILE_WEAK_MOVE,
    DYNAMIC_SYNERGY_PROFILE_CRITICAL_HIT,
    DYNAMIC_SYNERGY_PROFILE_DEFENSE_BOOST,
    DYNAMIC_SYNERGY_PROFILE_TYPE_ANY_BASE,
    DYNAMIC_SYNERGY_PROFILE_TYPE_DAMAGE_BASE = DYNAMIC_SYNERGY_PROFILE_TYPE_ANY_BASE + NUMBER_OF_MON_TYPES,
    DYNAMIC_SYNERGY_PROFILE_EXACT_BASE = 0x1000,
};

STATIC_ASSERT(DYNAMIC_SYNERGY_PROFILE_TYPE_DAMAGE_BASE + NUMBER_OF_MON_TYPES < DYNAMIC_SYNERGY_PROFILE_EXACT_BASE, DynamicSynergyProfileRangesDoNotOverlap);

#define DYNAMIC_SYNERGY_CHOICE_NATURAL 3
#define DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(type) (DYNAMIC_SYNERGY_PROFILE_TYPE_ANY_BASE + (type))
#define DYNAMIC_SYNERGY_PROFILE_TYPE_DAMAGE(type) (DYNAMIC_SYNERGY_PROFILE_TYPE_DAMAGE_BASE + (type))
#define DYNAMIC_SYNERGY_PROFILE_EXACT(move) (DYNAMIC_SYNERGY_PROFILE_EXACT_BASE + (move))

struct DynamicSynergyProfile
{
    u16 moves[3];
    u8 policy;
};

#ifdef ROGUE_EXPANSION
// Slots are physical, special, and utility. These slots are serialized by the
// legendary synergy choice, so never reorder or replace them after release.
static const u16 sDynamicTypeSynergyMoves[NUMBER_OF_MON_TYPES][4] =
{
    [TYPE_NORMAL]   = { MOVE_EXTREME_SPEED,  MOVE_GLARE,        MOVE_BOOMBURST,     MOVE_BODY_SLAM },
    [TYPE_FIGHTING] = { MOVE_CLOSE_COMBAT,   MOVE_BULK_UP,      MOVE_FOCUS_BLAST,   MOVE_DRAIN_PUNCH },
    [TYPE_FLYING]   = { MOVE_BRAVE_BIRD,     MOVE_ROOST,        MOVE_HURRICANE,     MOVE_AIR_SLASH },
    [TYPE_POISON]   = { MOVE_GUNK_SHOT,      MOVE_TOXIC,        MOVE_SLUDGE_BOMB,   MOVE_POISON_JAB },
    [TYPE_GROUND]   = { MOVE_HEADLONG_RUSH,  MOVE_SPIKES,       MOVE_EARTH_POWER,   MOVE_SCORCHING_SANDS },
    [TYPE_ROCK]     = { MOVE_ROCK_SLIDE,     MOVE_STEALTH_ROCK, MOVE_POWER_GEM,     MOVE_ANCIENT_POWER },
    [TYPE_BUG]      = { MOVE_LUNGE,          MOVE_STICKY_WEB,   MOVE_BUG_BUZZ,      MOVE_FELL_STINGER },
    [TYPE_GHOST]    = { MOVE_POLTERGEIST,    MOVE_DESTINY_BOND, MOVE_SHADOW_BALL,   MOVE_HEX },
    [TYPE_STEEL]    = { MOVE_IRON_HEAD,      MOVE_SHIFT_GEAR,   MOVE_FLASH_CANNON,  MOVE_GYRO_BALL },
    [TYPE_FIRE]     = { MOVE_FIRE_LASH,      MOVE_WILL_O_WISP,  MOVE_OVERHEAT,      MOVE_SACRED_FIRE },
    [TYPE_WATER]    = { MOVE_LIQUIDATION,    MOVE_RAIN_DANCE,   MOVE_MUDDY_WATER,   MOVE_FLIP_TURN },
    [TYPE_GRASS]    = { MOVE_LEAF_BLADE,     MOVE_LEECH_SEED,   MOVE_GIGA_DRAIN,    MOVE_APPLE_ACID },
    [TYPE_ELECTRIC] = { MOVE_SUPERCELL_SLAM, MOVE_THUNDER_WAVE, MOVE_THUNDER,       MOVE_VOLT_SWITCH },
    [TYPE_PSYCHIC]  = { MOVE_ZEN_HEADBUTT,   MOVE_TRICK_ROOM,   MOVE_PSYSHOCK,      MOVE_FUTURE_SIGHT },
    [TYPE_ICE]      = { MOVE_TRIPLE_AXEL,    MOVE_HAZE,         MOVE_FREEZE_DRY,    MOVE_FROST_BREATH },
    [TYPE_DRAGON]   = { MOVE_DRAGON_RUSH,    MOVE_DRAGON_DANCE, MOVE_DRACO_METEOR,  MOVE_BREAKING_SWIPE },
    [TYPE_DARK]     = { MOVE_NIGHT_SLASH,    MOVE_TAUNT,        MOVE_DARK_PULSE,    MOVE_FOUL_PLAY },
    [TYPE_FAIRY]    = { MOVE_PLAY_ROUGH,     MOVE_CHARM,        MOVE_MOONBLAST,     MOVE_DRAINING_KISS },
};
#endif

static u16 GetDynamicUniqueAbilitySynergyProfileId(u16 ability)
{
#ifdef ROGUE_EXPANSION
    u16 move;

    if(ability >= ARRAY_COUNT(sDynamicUniqueAbilitySynergyMoves))
        return DYNAMIC_SYNERGY_PROFILE_NONE;

    switch(ability)
    {
    case ABILITY_IMMOLATE:
    case ABILITY_HAUTE_COUTURE:
    case ABILITY_DRAGONIZE:
        return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_NORMAL);
    case ABILITY_TOXIC_TANDEM:
        return DYNAMIC_SYNERGY_PROFILE_TYPE_DAMAGE(TYPE_POISON);
    case ABILITY_SIGHTING_SYSTEM:
        return DYNAMIC_SYNERGY_PROFILE_LOW_ACCURACY;
    case ABILITY_INTENSIVE_CARE:
        return DYNAMIC_SYNERGY_PROFILE_ALLY_TARGET;
    case ABILITY_VICEJAW:
        return DYNAMIC_SYNERGY_PROFILE_BITE_OR_CRUNCH;
    case ABILITY_HIVE_COMMAND:
        return DYNAMIC_SYNERGY_PROFILE_ORDER;
    case ABILITY_THROWING_FORM:
        return DYNAMIC_SYNERGY_PROFILE_FORCED_SWITCH;
    case ABILITY_TAR_CANNON:
        return DYNAMIC_SYNERGY_PROFILE_PSYCHIC_STATUS;
    case ABILITY_SOUL_BRAND:
        return DYNAMIC_SYNERGY_PROFILE_GHOST_STATUS;
    case ABILITY_MEAN_STREAK:
        return DYNAMIC_SYNERGY_PROFILE_ATTACK_BOOST;
    case ABILITY_TOXIC_VANITY:
        return DYNAMIC_SYNERGY_PROFILE_WEAK_MOVE;
    case ABILITY_MOMENTUM:
        return DYNAMIC_SYNERGY_PROFILE_CRITICAL_HIT;
    case ABILITY_SALT_FORTRESS:
        return DYNAMIC_SYNERGY_PROFILE_DEFENSE_BOOST;
    case ABILITY_FINAL_STEP:
        return DYNAMIC_SYNERGY_PROFILE_SOUND;
    case ABILITY_BRAVERY:
    case ABILITY_WATER_GLIDE:
    case ABILITY_TROPICAL_CANOPY:
    case ABILITY_PREDATOR:
    case ABILITY_CHATTERBOX:
    case ABILITY_WINDSURGE:
        return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_FLYING);
    case ABILITY_MOON_TOTEM:
    case ABILITY_BAG_OF_TRICKS:
    case ABILITY_SHORT_FUSE:
        return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_DARK);
    case ABILITY_SPIRIT_FEAST:
        return DYNAMIC_SYNERGY_PROFILE_TYPE_DAMAGE(TYPE_DARK);
    case ABILITY_DYNAMO_FISTS:
        return DYNAMIC_SYNERGY_PROFILE_DYNAMO_FISTS;
    case ABILITY_FAULT_FINDER:
        return DYNAMIC_SYNERGY_PROFILE_FAULT_FINDER;
    case ABILITY_ROLLING_START:
        return DYNAMIC_SYNERGY_PROFILE_ROLLING_START;
    case ABILITY_STARLOCK:
        return DYNAMIC_SYNERGY_PROFILE_EXACT(MOVE_RECOVER);
    case ABILITY_MAELSTROM:
        return DYNAMIC_SYNERGY_PROFILE_RECOVER_STRENGTH_SAP;
    case ABILITY_FORTIFIED_SPIN:
    case ABILITY_TIDECALL:
        return DYNAMIC_SYNERGY_PROFILE_EXACT(MOVE_PROTECT);
    case ABILITY_LANAKILA_LAW:
        return DYNAMIC_SYNERGY_PROFILE_ENCORE_DISABLE;
    case ABILITY_BEGUILE:
        return DYNAMIC_SYNERGY_PROFILE_BEGUILE;
    }

    move = sDynamicUniqueAbilitySynergyMoves[ability];
    switch(move)
    {
    case MOVE_NONE:             return DYNAMIC_SYNERGY_PROFILE_NONE;
    case MOVE_JET_PUNCH:        return DYNAMIC_SYNERGY_PROFILE_PUNCH;
    case MOVE_THUNDEROUS_KICK:  return DYNAMIC_SYNERGY_PROFILE_KICK;
    case MOVE_LEAF_BLADE:       return DYNAMIC_SYNERGY_PROFILE_SLICE;
    case MOVE_CRUNCH:           return DYNAMIC_SYNERGY_PROFILE_BITE;
    case MOVE_BOOMBURST:        return DYNAMIC_SYNERGY_PROFILE_SOUND;
    case MOVE_QUIVER_DANCE:     return DYNAMIC_SYNERGY_PROFILE_DANCE;
    case MOVE_RECOVER:          return DYNAMIC_SYNERGY_PROFILE_HEALING;
    case MOVE_U_TURN:           return DYNAMIC_SYNERGY_PROFILE_PIVOT;
    case MOVE_BRAVE_BIRD:       return DYNAMIC_SYNERGY_PROFILE_RECOIL;
    case MOVE_SURGING_STRIKES:  return DYNAMIC_SYNERGY_PROFILE_MULTI_HIT;
    case MOVE_SPORE:            return DYNAMIC_SYNERGY_PROFILE_POWDER;
    case MOVE_PROTECT:          return DYNAMIC_SYNERGY_PROFILE_PROTECTION;
    case MOVE_DARK_PULSE:       return DYNAMIC_SYNERGY_PROFILE_PULSE;
    case MOVE_SHADOW_BONE:      return DYNAMIC_SYNERGY_PROFILE_BONE;
    case MOVE_DRAINING_KISS:    return DYNAMIC_SYNERGY_PROFILE_KISS;
    case MOVE_TAUNT:            return DYNAMIC_SYNERGY_PROFILE_STATUS;
    case MOVE_HYPER_BEAM:       return DYNAMIC_SYNERGY_PROFILE_RECHARGE;
    case MOVE_BODY_SLAM:        return DYNAMIC_SYNERGY_PROFILE_CONTACT;
    case MOVE_CLOSE_COMBAT:     return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_FIGHTING);
    case MOVE_HURRICANE:        return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_FLYING);
    case MOVE_SLUDGE_BOMB:      return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_POISON);
    case MOVE_EARTH_POWER:      return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_GROUND);
    case MOVE_POWER_GEM:        return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_ROCK);
    case MOVE_BUG_BUZZ:         return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_BUG);
    case MOVE_FLASH_CANNON:     return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_STEEL);
    case MOVE_MYSTICAL_FIRE:    return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_FIRE);
    case MOVE_CHILLING_WATER:   return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_WATER);
    case MOVE_GIGA_DRAIN:       return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_GRASS);
    case MOVE_THUNDER:          return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_ELECTRIC);
    case MOVE_PSYSHOCK:         return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_PSYCHIC);
    case MOVE_FREEZE_DRY:       return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_ICE);
    case MOVE_DRAGON_RUSH:      return DYNAMIC_SYNERGY_PROFILE_TYPE_ANY(TYPE_DRAGON);
    default:                    return DYNAMIC_SYNERGY_PROFILE_EXACT(move);
    }
#else
    return DYNAMIC_SYNERGY_PROFILE_NONE;
#endif
}

static struct DynamicSynergyProfile GetDynamicSynergyProfile(u16 profileId)
{
    struct DynamicSynergyProfile profile = { .policy = DYNAMIC_SYNERGY_POLICY_UNIFORM };

#ifdef ROGUE_EXPANSION
    if(profileId >= DYNAMIC_SYNERGY_PROFILE_TYPE_ANY_BASE
     && profileId < DYNAMIC_SYNERGY_PROFILE_TYPE_ANY_BASE + NUMBER_OF_MON_TYPES)
    {
        u8 type = profileId - DYNAMIC_SYNERGY_PROFILE_TYPE_ANY_BASE;
        profile.moves[0] = sDynamicTypeSynergyMoves[type][0];
        profile.moves[1] = sDynamicTypeSynergyMoves[type][2];
        profile.moves[2] = sDynamicTypeSynergyMoves[type][1];
        profile.policy = DYNAMIC_SYNERGY_POLICY_OFFENSE;
        return profile;
    }
    if(profileId >= DYNAMIC_SYNERGY_PROFILE_TYPE_DAMAGE_BASE
     && profileId < DYNAMIC_SYNERGY_PROFILE_TYPE_DAMAGE_BASE + NUMBER_OF_MON_TYPES)
    {
        u8 type = profileId - DYNAMIC_SYNERGY_PROFILE_TYPE_DAMAGE_BASE;
        profile.moves[0] = sDynamicTypeSynergyMoves[type][0];
        profile.moves[1] = sDynamicTypeSynergyMoves[type][2];
        profile.moves[2] = sDynamicTypeSynergyMoves[type][3];
        profile.policy = DYNAMIC_SYNERGY_POLICY_OFFENSE;
        return profile;
    }
    if(profileId >= DYNAMIC_SYNERGY_PROFILE_EXACT_BASE)
    {
        profile.moves[0] = profileId - DYNAMIC_SYNERGY_PROFILE_EXACT_BASE;
        return profile;
    }

    switch(profileId)
    {
    case DYNAMIC_SYNERGY_PROFILE_PUNCH:
        profile = (struct DynamicSynergyProfile){{ MOVE_JET_PUNCH, MOVE_NONE, MOVE_DRAIN_PUNCH }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_KICK:
        profile = (struct DynamicSynergyProfile){{ MOVE_THUNDEROUS_KICK, MOVE_NONE, MOVE_TRIPLE_AXEL }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_SLICE:
        profile = (struct DynamicSynergyProfile){{ MOVE_LEAF_BLADE, MOVE_AIR_SLASH, MOVE_BITTER_BLADE }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_BITE:
        profile = (struct DynamicSynergyProfile){{ MOVE_CRUNCH, MOVE_PSYCHIC_FANGS, MOVE_JAW_LOCK }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_SOUND:
        profile = (struct DynamicSynergyProfile){{ MOVE_NONE, MOVE_BOOMBURST, MOVE_SNARL }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_DANCE:
        profile = (struct DynamicSynergyProfile){{ MOVE_AQUA_STEP, MOVE_REVELATION_DANCE, MOVE_QUIVER_DANCE }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_HEALING:
        profile = (struct DynamicSynergyProfile){{ MOVE_HORN_LEECH, MOVE_DRAINING_KISS, MOVE_RECOVER }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_PIVOT:
        profile = (struct DynamicSynergyProfile){{ MOVE_U_TURN, MOVE_VOLT_SWITCH, MOVE_PARTING_SHOT }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_RECOIL:
        profile = (struct DynamicSynergyProfile){{ MOVE_BRAVE_BIRD, MOVE_MIND_BLOWN, MOVE_FLARE_BLITZ }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_MULTI_HIT:
        profile = (struct DynamicSynergyProfile){{ MOVE_SURGING_STRIKES, MOVE_WATER_SHURIKEN, MOVE_SCALE_SHOT }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_POWDER:
        profile = (struct DynamicSynergyProfile){{ MOVE_SPORE, MOVE_SLEEP_POWDER, MOVE_STUN_SPORE }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_PROTECTION:
        profile = (struct DynamicSynergyProfile){{ MOVE_PROTECT, MOVE_SPIKY_SHIELD, MOVE_BANEFUL_BUNKER }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_PULSE:
        profile = (struct DynamicSynergyProfile){{ MOVE_NONE, MOVE_DARK_PULSE, MOVE_HEAL_PULSE }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_BONE:
        profile = (struct DynamicSynergyProfile){{ MOVE_SHADOW_BONE, MOVE_BONE_RUSH, MOVE_BONEMERANG }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_KISS:
        profile = (struct DynamicSynergyProfile){{ MOVE_NONE, MOVE_DRAINING_KISS, MOVE_SWEET_KISS }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_STATUS:
        profile = (struct DynamicSynergyProfile){{ MOVE_TAUNT, MOVE_ENCORE, MOVE_DISABLE }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_RECHARGE:
        profile = (struct DynamicSynergyProfile){{ MOVE_GIGA_IMPACT, MOVE_HYPER_BEAM, MOVE_METEOR_ASSAULT }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_CONTACT:
        profile = (struct DynamicSynergyProfile){{ MOVE_BODY_SLAM, MOVE_DRAINING_KISS, MOVE_FAKE_OUT }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_DYNAMO_FISTS:
        profile = (struct DynamicSynergyProfile){{ MOVE_THUNDER_PUNCH, MOVE_THUNDER, MOVE_CHARGE }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_FAULT_FINDER:
        profile = (struct DynamicSynergyProfile){{ MOVE_HEADLONG_RUSH, MOVE_EARTH_POWER, MOVE_FLASH_CANNON }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_ROLLING_START:
        profile = (struct DynamicSynergyProfile){{ MOVE_ROLLOUT, MOVE_ICE_BALL, MOVE_NONE }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_RECOVER_STRENGTH_SAP:
        profile = (struct DynamicSynergyProfile){{ MOVE_RECOVER, MOVE_STRENGTH_SAP, MOVE_NONE }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_ENCORE_DISABLE:
        profile = (struct DynamicSynergyProfile){{ MOVE_ENCORE, MOVE_DISABLE, MOVE_NONE }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_BEGUILE:
        profile = (struct DynamicSynergyProfile){{ MOVE_ENCORE, MOVE_DISABLE, MOVE_TORMENT }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_LOW_ACCURACY:
        profile = (struct DynamicSynergyProfile){{ MOVE_DYNAMIC_PUNCH, MOVE_ZAP_CANNON, MOVE_SING }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_ALLY_TARGET:
        profile = (struct DynamicSynergyProfile){{ MOVE_HELPING_HAND, MOVE_HEAL_PULSE, MOVE_AROMATIC_MIST }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_BITE_OR_CRUNCH:
        profile = (struct DynamicSynergyProfile){{ MOVE_BITE, MOVE_CRUNCH, MOVE_NONE }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_ORDER:
        profile = (struct DynamicSynergyProfile){{ MOVE_ATTACK_ORDER, MOVE_DEFEND_ORDER, MOVE_HEAL_ORDER }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_FORCED_SWITCH:
        profile = (struct DynamicSynergyProfile){{ MOVE_DRAGON_TAIL, MOVE_ROAR, MOVE_WHIRLWIND }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_PSYCHIC_STATUS:
        profile = (struct DynamicSynergyProfile){{ MOVE_CALM_MIND, MOVE_TRICK_ROOM, MOVE_GRAVITY }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_GHOST_STATUS:
        profile = (struct DynamicSynergyProfile){{ MOVE_DESTINY_BOND, MOVE_CURSE, MOVE_CONFUSE_RAY }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_ATTACK_BOOST:
        profile = (struct DynamicSynergyProfile){{ MOVE_SWORDS_DANCE, MOVE_BULK_UP, MOVE_DRAGON_DANCE }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    case DYNAMIC_SYNERGY_PROFILE_WEAK_MOVE:
        profile = (struct DynamicSynergyProfile){{ MOVE_NUZZLE, MOVE_ACID_SPRAY, MOVE_FAKE_OUT }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_CRITICAL_HIT:
        profile = (struct DynamicSynergyProfile){{ MOVE_LEAF_BLADE, MOVE_FROST_BREATH, MOVE_NIGHT_SLASH }, DYNAMIC_SYNERGY_POLICY_OFFENSE};
        break;
    case DYNAMIC_SYNERGY_PROFILE_DEFENSE_BOOST:
        profile = (struct DynamicSynergyProfile){{ MOVE_IRON_DEFENSE, MOVE_ACID_ARMOR, MOVE_BULK_UP }, DYNAMIC_SYNERGY_POLICY_UNIFORM};
        break;
    }
#endif

    return profile;
}

static struct DynamicSynergyProfile GetDynamicUniqueAbilitySynergyProfile(u16 ability)
{
    return GetDynamicSynergyProfile(GetDynamicUniqueAbilitySynergyProfileId(ability));
}

static u16 GetDynamicUniqueAbilitySynergyMove(u16 ability, u8 synergyChoice)
{
    struct DynamicSynergyProfile profile;

    if(synergyChoice >= DYNAMIC_SYNERGY_CHOICE_NATURAL)
        return MOVE_NONE;

    profile = GetDynamicUniqueAbilitySynergyProfile(ability);
    return profile.moves[synergyChoice];
}

static struct DynamicSynergyProfile GetCreationSynergyProfile(u8 type)
{
    struct DynamicSynergyProfile profile = { .policy = DYNAMIC_SYNERGY_POLICY_UNIFORM };

#ifdef ROGUE_EXPANSION
    switch(type)
    {
    case TYPE_NORMAL:   profile = (struct DynamicSynergyProfile){{ MOVE_SUBSTITUTE, MOVE_RECOVER, MOVE_SWORDS_DANCE }, DYNAMIC_SYNERGY_POLICY_UNIFORM}; break;
    case TYPE_FIRE:     profile.moves[0] = MOVE_WILL_O_WISP; break;
    case TYPE_WATER:    profile.moves[0] = MOVE_AQUA_RING; break;
    case TYPE_POISON:   profile = (struct DynamicSynergyProfile){{ MOVE_TOXIC_SPIKES, MOVE_TOXIC, MOVE_NONE }, DYNAMIC_SYNERGY_POLICY_UNIFORM}; break;
    case TYPE_ROCK:     profile = (struct DynamicSynergyProfile){{ MOVE_STEALTH_ROCK, MOVE_ROCK_POLISH, MOVE_NONE }, DYNAMIC_SYNERGY_POLICY_UNIFORM}; break;
    case TYPE_BUG:      profile = (struct DynamicSynergyProfile){{ MOVE_STICKY_WEB, MOVE_QUIVER_DANCE, MOVE_NONE }, DYNAMIC_SYNERGY_POLICY_UNIFORM}; break;
    case TYPE_GHOST:    profile = (struct DynamicSynergyProfile){{ MOVE_DESTINY_BOND, MOVE_CURSE, MOVE_CONFUSE_RAY }, DYNAMIC_SYNERGY_POLICY_UNIFORM}; break;
    case TYPE_GRASS:    profile = (struct DynamicSynergyProfile){{ MOVE_LEECH_SEED, MOVE_SPORE, MOVE_STRENGTH_SAP }, DYNAMIC_SYNERGY_POLICY_UNIFORM}; break;
    case TYPE_ELECTRIC: profile = (struct DynamicSynergyProfile){{ MOVE_CHARGE, MOVE_THUNDER_WAVE, MOVE_MAGNET_RISE }, DYNAMIC_SYNERGY_POLICY_UNIFORM}; break;
    case TYPE_PSYCHIC:  profile = (struct DynamicSynergyProfile){{ MOVE_TRICK_ROOM, MOVE_CALM_MIND, MOVE_GRAVITY }, DYNAMIC_SYNERGY_POLICY_UNIFORM}; break;
    case TYPE_ICE:      profile.moves[0] = MOVE_HAZE; break;
    case TYPE_DARK:     profile = (struct DynamicSynergyProfile){{ MOVE_TAUNT, MOVE_NASTY_PLOT, MOVE_TORMENT }, DYNAMIC_SYNERGY_POLICY_UNIFORM}; break;
    case TYPE_FAIRY:    profile = (struct DynamicSynergyProfile){{ MOVE_CHARM, MOVE_SWEET_KISS, MOVE_NONE }, DYNAMIC_SYNERGY_POLICY_UNIFORM}; break;
    }
#endif

    return profile;
}

static bool8 HasCreationSynergyProfile(u8 type)
{
    return GetCreationSynergyProfile(type).moves[0] != MOVE_NONE;
}

#ifdef ROGUE_DEBUG
u16 RogueGift_DebugGetDynamicSynergyProfileId(u16 ability)
{
    return GetDynamicUniqueAbilitySynergyProfileId(ability);
}

u16 RogueGift_DebugGetDynamicSynergyMove(u16 ability, u8 choice)
{
    return GetDynamicUniqueAbilitySynergyMove(ability, choice);
}

u8 RogueGift_DebugGetDynamicSynergyPolicy(u16 ability)
{
    return GetDynamicUniqueAbilitySynergyProfile(ability).policy;
}
#endif

const u16 sTypeTintColors[NUMBER_OF_MON_TYPES] =
{
    [TYPE_NORMAL] = RGB_RANGE_255_TO_31(255, 236, 206),
    [TYPE_FIGHTING] = RGB_RANGE_255_TO_31(179, 39, 27),
    [TYPE_FLYING] = RGB_RANGE_255_TO_31(154, 217, 232),
    [TYPE_POISON] = RGB_RANGE_255_TO_31(254, 20, 255),
    [TYPE_GROUND] = RGB_RANGE_255_TO_31(142, 102, 59),
    [TYPE_ROCK] = RGB_RANGE_255_TO_31(202, 162, 86),
    [TYPE_BUG] = RGB_RANGE_255_TO_31(188, 202, 121),
    [TYPE_GHOST] = RGB_WHITE,
    [TYPE_STEEL] = RGB_RANGE_255_TO_31(142, 142, 142),
    [TYPE_MYSTERY] = RGB_WHITE,
    [TYPE_FIRE] = RGB_RANGE_255_TO_31(255, 170, 71),
    [TYPE_WATER] = RGB_RANGE_255_TO_31(37, 178, 255),
    [TYPE_GRASS] = RGB_RANGE_255_TO_31(33, 255, 32),
    [TYPE_ELECTRIC] = RGB_RANGE_255_TO_31(255, 227, 20),
    [TYPE_PSYCHIC] = RGB_RANGE_255_TO_31(254, 80, 255),
    [TYPE_ICE] = RGB_RANGE_255_TO_31(163, 255, 253),
    [TYPE_DRAGON] = RGB_RANGE_255_TO_31(43, 40, 255),
    [TYPE_DARK] = RGB_RANGE_255_TO_31(91, 91, 91),
#ifdef ROGUE_EXPANSION
    [TYPE_FAIRY] = RGB_RANGE_255_TO_31(255, 192, 234),
    [TYPE_STELLAR] = RGB(10, 18, 27),
#endif
};

#include "data/rogue/custom_mons.h"

enum
{
    COMPRESSED_FORMAT_ORIGINAL = 0,
    COMPRESSED_FORMAT_MON_TYPE,
    COMPRESSED_FORMAT_ORIGINAL_UNIQUE_ABILITY,
    COMPRESSED_FORMAT_MON_TYPE_UNIQUE_ABILITY,
};

struct CompressedDynamicData
{
    u32 data:28;
    u32 format:2;
    u32 reserved:2; // reserved for bitmask OTID_FLAG_CUSTOM_MON etc.
};

struct CompressedDynamicData_Original
{
    u32 moveSelection:14;
    u32 unused:7;
    u32 ability:7; // 127 indices
    u32 format:2;
    u32 reserved:2;
};

struct CompressedDynamicData_MonType
{
    u32 type:5;
    u32 typeSlot:1;
    u32 typeMoveFlip:1;
    u32 moveSelection:14;
    u32 ability:7; // 127 indices
    u32 format:2;
    u32 reserved:2;
};

struct CompressedDynamicData_OriginalUniqueAbility
{
    u32 moveSelection:14;
    u32 uniqueAbility:10;
    u32 abilitySeed:2; // Four candidates are enough to avoid all native slots.
    u32 synergyChoice:2; // Profile slot 0-2, or 3 when no move must be injected.
    u32 format:2;
    u32 reserved:2;
};

struct CompressedDynamicData_MonTypeUniqueAbility
{
    u32 typeMoveSelection:14;
    u32 uniqueAbility:10;
    u32 abilitySeed:2;
    u32 synergyChoice:2;
    u32 format:2;
    u32 reserved:2;
};

struct DynamicMonData
{
    u16 moves[MAX_MON_MOVES];
    u16 movesCount;
    u8 types[2];
    u16 ability;
    u16 uniqueAbility;
};

STATIC_ASSERT(sizeof(struct CompressedDynamicData) == sizeof(struct CompressedDynamicData_Original), SizeOfCompressedDynamicData_Original);
STATIC_ASSERT(sizeof(struct CompressedDynamicData) == sizeof(struct CompressedDynamicData_MonType), SizeOfCompressedDynamicData_MonType);
STATIC_ASSERT(sizeof(struct CompressedDynamicData) == sizeof(struct CompressedDynamicData_OriginalUniqueAbility), SizeOfCompressedDynamicData_OriginalUniqueAbility);
STATIC_ASSERT(sizeof(struct CompressedDynamicData) == sizeof(struct CompressedDynamicData_MonTypeUniqueAbility), SizeOfCompressedDynamicData_MonTypeUniqueAbility);
STATIC_ASSERT(sizeof(struct CompressedDynamicData) == sizeof(u32), SizeOfDynamicCustomMonData);

static u16 SelectTypeBasedExtraMove(u8 type, u8 typeSlot, u8 typeMoveFlip)
{
#ifdef ROGUE_EXPANSION
    if (type < NUMBER_OF_MON_TYPES && sDynamicTypeSynergyMoves[type][0] != MOVE_NONE)
        return sDynamicTypeSynergyMoves[type][(typeSlot << 1) | typeMoveFlip];
#else
    u8 rng = typeMoveFlip;

    (void)typeSlot;

    switch (type)
    {
    case TYPE_NORMAL:
        return rng ? MOVE_QUICK_ATTACK : MOVE_BODY_SLAM;
    case TYPE_FIGHTING:
        return rng ? MOVE_MACH_PUNCH : MOVE_FOCUS_PUNCH;
    case TYPE_FLYING:
        return rng ? MOVE_FLY : MOVE_AEROBLAST;
    case TYPE_POISON:
        return rng ? MOVE_TOXIC : MOVE_SLUDGE_BOMB;
    case TYPE_GROUND:
        return rng ? MOVE_EARTHQUAKE : MOVE_DIG;
    case TYPE_ROCK:
        return rng ? MOVE_ROCK_SLIDE : MOVE_SANDSTORM;
    case TYPE_BUG:
        return rng ? MOVE_SIGNAL_BEAM : MOVE_PIN_MISSILE;
    case TYPE_GHOST:
        return rng ? MOVE_SHADOW_BALL : MOVE_SHADOW_PUNCH;
    case TYPE_STEEL:
        return rng ? MOVE_METEOR_MASH : MOVE_IRON_DEFENSE;
    case TYPE_FIRE:
        return rng ? MOVE_FLAMETHROWER : MOVE_WILL_O_WISP;
    case TYPE_WATER:
        return rng ? MOVE_SURF : MOVE_WATER_PULSE;
    case TYPE_GRASS:
        return rng ? MOVE_GIGA_DRAIN : MOVE_LEAF_BLADE;
    case TYPE_ELECTRIC:
        return rng ? MOVE_THUNDER : MOVE_VOLT_TACKLE;
    case TYPE_PSYCHIC:
        return rng ? MOVE_PSYCHIC : MOVE_CALM_MIND;
    case TYPE_ICE:
        return rng ? MOVE_ICE_BEAM : MOVE_BLIZZARD;
    case TYPE_DRAGON:
        return rng ? MOVE_DRAGON_BREATH : MOVE_DRAGON_CLAW;
    case TYPE_DARK:
        return rng ? MOVE_CRUNCH : MOVE_BITE;
    }
#endif

    return MOVE_RETURN;
}

static u16 EncodeDynamicMoveSelection(u16 move1, u16 move2)
{
    u16 first;
    u16 second;
    u32 pairRank;

    if(move1 == 0)
    {
        AGB_ASSERT(move2 <= ARRAY_COUNT(sDynamicCustomMonMoves));
        return move2;
    }
    if(move2 == 0)
    {
        AGB_ASSERT(move1 <= ARRAY_COUNT(sDynamicCustomMonMoves));
        return move1;
    }

    AGB_ASSERT(move1 <= ARRAY_COUNT(sDynamicCustomMonMoves));
    AGB_ASSERT(move2 <= ARRAY_COUNT(sDynamicCustomMonMoves));
    if(move1 == move2)
    {
        AGB_ASSERT(FALSE);
        return move1;
    }

    first = move1 - 1;
    second = move2 - 1;
    if(first > second)
    {
        u16 temp = first;
        first = second;
        second = temp;
    }

    pairRank = first * (2 * DYNAMIC_MOVE_POOL_CAPACITY - first - 1) / 2;
    pairRank += second - first - 1;
    return DYNAMIC_MOVE_PAIR_CODE_START + pairRank;
}

static void AppendDynamicMoveByIndex(struct DynamicMonData* outData, u16 moveIndex)
{
    if(moveIndex != 0 && moveIndex <= ARRAY_COUNT(sDynamicCustomMonMoves))
    {
        AGB_ASSERT(outData->movesCount < ARRAY_COUNT(outData->moves));
        outData->moves[outData->movesCount++] = sDynamicCustomMonMoves[moveIndex - 1];
    }
    else
    {
        AGB_ASSERT(FALSE);
    }
}

static void DecodeDynamicMoveSelection(u16 moveSelection, struct DynamicMonData* outData)
{
    u16 first;
    u32 pairRank;

    if(moveSelection == 0)
        return;

    if(moveSelection <= DYNAMIC_MOVE_POOL_CAPACITY)
    {
        AppendDynamicMoveByIndex(outData, moveSelection);
        return;
    }

    if(moveSelection < DYNAMIC_MOVE_PAIR_CODE_START)
    {
        AGB_ASSERT(FALSE);
        return;
    }

    pairRank = moveSelection - DYNAMIC_MOVE_PAIR_CODE_START;
    if(pairRank >= DYNAMIC_MOVE_PAIR_COUNT)
    {
        AGB_ASSERT(FALSE);
        return;
    }

    for(first = 0; first < DYNAMIC_MOVE_POOL_CAPACITY - 1; ++first)
    {
        u16 remainingPairs = DYNAMIC_MOVE_POOL_CAPACITY - first - 1;

        if(pairRank < remainingPairs)
        {
            AppendDynamicMoveByIndex(outData, first + 1);
            AppendDynamicMoveByIndex(outData, first + pairRank + 2);
            return;
        }

        pairRank -= remainingPairs;
    }

    AGB_ASSERT(FALSE);
}

static u16 EncodeTypedUniqueMoveSelection(u8 type, u8 typeSlot, u8 typeMoveFlip, u16 moveIndex)
{
    u16 typeSelection = ((type * 2 + typeSlot) * 2 + typeMoveFlip);

    AGB_ASSERT(type < NUMBER_OF_MON_TYPES);
    AGB_ASSERT(typeSlot < 2);
    AGB_ASSERT(typeMoveFlip < 2);
    AGB_ASSERT(moveIndex <= ARRAY_COUNT(sDynamicCustomMonMoves));
    return typeSelection * DYNAMIC_TYPED_MOVE_SELECTION_STRIDE + moveIndex;
}

static void DecodeTypedUniqueMoveSelection(u16 selection, u8* type, u8* typeSlot, u8* typeMoveFlip, u16* moveIndex)
{
    u16 typeSelection = selection / DYNAMIC_TYPED_MOVE_SELECTION_STRIDE;

    *moveIndex = selection % DYNAMIC_TYPED_MOVE_SELECTION_STRIDE;
    *typeMoveFlip = typeSelection % 2;
    typeSelection /= 2;
    *typeSlot = typeSelection % 2;
    *type = typeSelection / 2;

    AGB_ASSERT(*type < NUMBER_OF_MON_TYPES);
    AGB_ASSERT(*moveIndex <= ARRAY_COUNT(sDynamicCustomMonMoves));
}

static u16 DecodeLegendaryStandardAbility(u16 moveSelection, u16 uniqueAbility, u8 format, u8 abilitySeed)
{
    u32 baseIndex = moveSelection * 33u + uniqueAbility * 17u + format * 7u;
    u32 abilityIndex = (baseIndex + abilitySeed) % ARRAY_COUNT(sDynamicCustomMonAbilities);

    return sDynamicCustomMonAbilities[abilityIndex];
}

static void ApplyOriginalUniqueAbilitySynergy(struct DynamicMonData* outData, u8 synergyChoice)
{
    u16 synergyMove = GetDynamicUniqueAbilitySynergyMove(outData->uniqueAbility, synergyChoice);
    u16 i;

    if(synergyMove == MOVE_NONE)
        return;

    for(i = 0; i < outData->movesCount; ++i)
    {
        if(outData->moves[i] == synergyMove)
            return;
    }

    if(outData->movesCount == 0)
        outData->moves[outData->movesCount++] = synergyMove;
    else
        outData->moves[0] = synergyMove;
}

static void ApplyTypedUniqueAbilitySynergy(struct DynamicMonData* outData, u8 synergyChoice)
{
    u16 synergyMove = GetDynamicUniqueAbilitySynergyMove(outData->uniqueAbility, synergyChoice);
    u16 typeMove;

    if(synergyMove == MOVE_NONE || outData->movesCount == 0)
        return;

    typeMove = outData->moves[0];
    if(synergyMove == typeMove)
        return;

    if(outData->movesCount >= 2)
        outData->moves[1] = synergyMove;
    else
        outData->moves[outData->movesCount++] = synergyMove;
}

static void UncompressDynamicMonData(u32 customMonId, struct DynamicMonData* outData)
{
    struct CompressedDynamicData* compressedUntyped = (struct CompressedDynamicData*)&customMonId;

    outData->ability = ABILITY_NONE;
    outData->uniqueAbility = ABILITY_NONE;
    outData->movesCount = 0;
    outData->types[0] = TYPE_NONE;
    outData->types[1] = TYPE_NONE;

    if(compressedUntyped->format == COMPRESSED_FORMAT_ORIGINAL)
    {
        struct CompressedDynamicData_Original* compressedData = (struct CompressedDynamicData_Original*)compressedUntyped;

        outData->ability = ((compressedData->ability - 1) < ARRAY_COUNT(sDynamicCustomMonAbilities)) ? sDynamicCustomMonAbilities[compressedData->ability - 1] : ABILITY_NONE;
        DecodeDynamicMoveSelection(compressedData->moveSelection, outData);
    }
    else if(compressedUntyped->format == COMPRESSED_FORMAT_ORIGINAL_UNIQUE_ABILITY)
    {
        struct CompressedDynamicData_OriginalUniqueAbility* compressedData = (struct CompressedDynamicData_OriginalUniqueAbility*)compressedUntyped;

        outData->ability = DecodeLegendaryStandardAbility(compressedData->moveSelection, compressedData->uniqueAbility, compressedData->format, compressedData->abilitySeed);
        outData->uniqueAbility = RogueGift_IsDynamicUniqueAbilityEligible(compressedData->uniqueAbility) ? compressedData->uniqueAbility : ABILITY_NONE;
        DecodeDynamicMoveSelection(compressedData->moveSelection, outData);
        ApplyOriginalUniqueAbilitySynergy(outData, compressedData->synergyChoice);
    }
    else if(compressedUntyped->format == COMPRESSED_FORMAT_MON_TYPE)
    {
        struct CompressedDynamicData_MonType* compressedData = (struct CompressedDynamicData_MonType*)compressedUntyped;

        outData->ability = ((compressedData->ability - 1) < ARRAY_COUNT(sDynamicCustomMonAbilities)) ? sDynamicCustomMonAbilities[compressedData->ability - 1] : ABILITY_NONE;
        outData->types[compressedData->typeSlot] = compressedData->type;
        outData->moves[outData->movesCount++] = SelectTypeBasedExtraMove(compressedData->type, compressedData->typeSlot, compressedData->typeMoveFlip);
        DecodeDynamicMoveSelection(compressedData->moveSelection, outData);
    }
    else if(compressedUntyped->format == COMPRESSED_FORMAT_MON_TYPE_UNIQUE_ABILITY)
    {
        struct CompressedDynamicData_MonTypeUniqueAbility* compressedData = (struct CompressedDynamicData_MonTypeUniqueAbility*)compressedUntyped;
        u8 type;
        u8 typeSlot;
        u8 typeMoveFlip;
        u16 moveIndex;

        outData->ability = DecodeLegendaryStandardAbility(compressedData->typeMoveSelection, compressedData->uniqueAbility, compressedData->format, compressedData->abilitySeed);
        outData->uniqueAbility = RogueGift_IsDynamicUniqueAbilityEligible(compressedData->uniqueAbility) ? compressedData->uniqueAbility : ABILITY_NONE;
        DecodeTypedUniqueMoveSelection(compressedData->typeMoveSelection, &type, &typeSlot, &typeMoveFlip, &moveIndex);
        outData->types[typeSlot] = type;
        outData->moves[outData->movesCount++] = SelectTypeBasedExtraMove(type, typeSlot, typeMoveFlip);
        if(moveIndex != 0)
            AppendDynamicMoveByIndex(outData, moveIndex);
        ApplyTypedUniqueAbilitySynergy(outData, compressedData->synergyChoice);
    }
    else
    {
        AGB_ASSERT(FALSE);
    }
};

static u32 CompressedDynamicDataToCustomMonId(struct CompressedDynamicData* inData)
{
    u32 id;
    id = *((u32*)inData);
    return id;
}

u32 RogueGift_GetCustomMonId(struct Pokemon* mon)
{
    return RogueGift_GetCustomMonIdBySpecies(GetMonData(mon, MON_DATA_SPECIES), GetMonData(mon, MON_DATA_OT_ID));
}

u32 RogueGift_GetCustomBoxMonId(struct BoxPokemon* mon)
{
    return RogueGift_GetCustomMonIdBySpecies(GetBoxMonData(mon, MON_DATA_SPECIES), GetBoxMonData(mon, MON_DATA_OT_ID));
}

static u16 TransformCheckSpecies(u16 species)
{
#ifdef ROGUE_EXPANSION
    // Special case (probably should get a proper fix for this)
    if(species >= SPECIES_PIKACHU_COSPLAY && species <= SPECIES_PICHU_SPIKY_EARED)
        return species;

    if(!gSpeciesInfo[species].isAlolanForm && !gSpeciesInfo[species].isGalarianForm && !gSpeciesInfo[species].isHisuianForm && !gSpeciesInfo[species].isPaldeanForm)
    {
        // Fix for castform/other form changes
        return GET_BASE_SPECIES_ID(species);
    }
#endif

    return species;
}

u32 RogueGift_GetCustomMonIdBySpecies(u16 species, u32 otId)
{
    u32 i;

#ifdef ROGUE_EXPANSION
    // The mega itself has it's own ability so don't redirect
    if(species == SPECIES_PIKIN_MEGA)
        return CUSTOM_MON_NONE;
#endif

    species = TransformCheckSpecies(species);

    if((otId & OTID_FLAG_CUSTOM_MON) && (otId & OTID_FLAG_DYNAMIC_CUSTOM_MON))
    {
        // otId is the custom mon id, as it encodes the data into it
        return otId;
    }
    if(otId & OTID_FLAG_CUSTOM_MON)
    {
        species = Rogue_GetEggSpecies(species);

        for(i = CUSTOM_MON_NONE + 1; i < CUSTOM_MON_COUNT; ++i)
        {
            struct CustomMonData const* monData = &sCustomPokemon[i];
            
            if(monData->otId == otId && Rogue_GetEggSpecies(monData->species) == species)
                return i;
        }
    }

    return CUSTOM_MON_NONE;
}

u16 RogueGift_GetCustomMonMove(u32 id, u8 i)
{
    if(id & OTID_FLAG_DYNAMIC_CUSTOM_MON)
    {
        struct DynamicMonData dynamicData;
        UncompressDynamicMonData(id, &dynamicData);
        return i < dynamicData.movesCount ? dynamicData.moves[i] : MOVE_NONE;
    }
    else
    {
        AGB_ASSERT(id < CUSTOM_MON_COUNT);

        if(id != CUSTOM_MON_NONE)
        {
            struct CustomMonData const* monData = &sCustomPokemon[id];
            return i < monData->movesCount ? monData->moves[i] : MOVE_NONE;
        }
    }

    return MOVE_NONE;
}

u16 RogueGift_GetCustomMonMoveCount(u32 id)
{
    if(id & OTID_FLAG_DYNAMIC_CUSTOM_MON)
    {
        struct DynamicMonData dynamicData;
        UncompressDynamicMonData(id, &dynamicData);
        return dynamicData.movesCount;
    }
    else
    {
        AGB_ASSERT(id < CUSTOM_MON_COUNT);

        if(id != CUSTOM_MON_NONE)
        {
            struct CustomMonData const* monData = &sCustomPokemon[id];

            if(id == CUSTOM_MON_ABBIE_MAREEP && !FlagGet(FLAG_ROGUE_UNLOCKED_PIKIN_EASTER_EGG))
            {
                // Don't show last move until activated easter egg
                return monData->movesCount - 1;
            }

            return monData->movesCount;
        }
    }

    return 0;
}

u16 RogueGift_GetCustomMonAbility(u32 id, u8 i)
{
    if(id & OTID_FLAG_DYNAMIC_CUSTOM_MON)
    {
        struct DynamicMonData dynamicData;
        UncompressDynamicMonData(id, &dynamicData);
        return i == 0 ? dynamicData.ability : ABILITY_NONE;
    }
    else
    {
        AGB_ASSERT(id < CUSTOM_MON_COUNT);

        if(id != CUSTOM_MON_NONE)
        {
            struct CustomMonData const* monData = &sCustomPokemon[id];
            return (monData->abilities != NULL && i < NUM_ABILITY_SLOTS) ? monData->abilities[i] : ABILITY_NONE;
        }
    }

    return ABILITY_NONE;
}

u16 RogueGift_GetCustomMonAbilityCount(u32 id)
{
    if(id & OTID_FLAG_DYNAMIC_CUSTOM_MON)
    {
        struct DynamicMonData dynamicData;
        UncompressDynamicMonData(id, &dynamicData);
        return dynamicData.ability != ABILITY_NONE ? NUM_ABILITY_SLOTS : 0;
    }
    else
    {
        struct CustomMonData const* monData = &sCustomPokemon[id];
        AGB_ASSERT(id < CUSTOM_MON_COUNT);

        return (monData->abilities != NULL) ? NUM_ABILITY_SLOTS : 0;
    }
}

u16 RogueGift_GetCustomMonUniqueAbility(u32 id)
{
    if(id & OTID_FLAG_DYNAMIC_CUSTOM_MON)
    {
        struct DynamicMonData dynamicData;
        UncompressDynamicMonData(id, &dynamicData);
        return dynamicData.uniqueAbility;
    }

    return ABILITY_NONE;
}

u8 RogueGift_GetCustomMonType(u32 id, u8 i)
{
    if(id & OTID_FLAG_DYNAMIC_CUSTOM_MON)
    {
        struct DynamicMonData dynamicData;
        UncompressDynamicMonData(id, &dynamicData);
        return i < ARRAY_COUNT(dynamicData.types) ? dynamicData.types[i] : TYPE_NONE;
    }

    return TYPE_NONE;
}

bool8 RogueGift_CanRenameCustomMon(u32 id)
{
    if(id & OTID_FLAG_DYNAMIC_CUSTOM_MON)
    {
        return TRUE;
    }
    else
    {
        // We're allowed to rename exotics, as they're technically dynamic custom mons too
        struct CustomMonData const* monData = &sCustomPokemon[id];
        AGB_ASSERT(id < CUSTOM_MON_COUNT);

        return monData->customTrainerId == CUSTOM_TRAINER_EXOTIC;
    }
}

bool8 RogueGift_DisplayCustomMonRarity(u32 id)
{
    if(id & OTID_FLAG_DYNAMIC_CUSTOM_MON)
        return TRUE;
    else
    {
        struct CustomMonData const* monData = &sCustomPokemon[id]; 
        if(monData->customTrainerId == CUSTOM_TRAINER_EXOTIC || monData->customTrainerId == CUSTOM_TRAINER_LEGEND)
            return TRUE;
    }

    return FALSE;
}

u8 RogueGift_GetCustomMonRarity(u32 id)
{
    if(id & OTID_FLAG_DYNAMIC_CUSTOM_MON)
    {
        struct DynamicMonData dynamicData;
        struct CompressedDynamicData* compressedUntyped = (struct CompressedDynamicData*)&id;
        u16 moveCount;
        u16 abilityCount;

        UncompressDynamicMonData(id, &dynamicData);
        if(dynamicData.uniqueAbility != ABILITY_NONE)
            return UNIQUE_RARITY_LEGENDARY;

        moveCount = RogueGift_GetCustomMonMoveCount(id);
        abilityCount = RogueGift_GetCustomMonAbilityCount(id);

        if(compressedUntyped->format == COMPRESSED_FORMAT_MON_TYPE)
        {
            struct CompressedDynamicData_MonType* compressedData = (struct CompressedDynamicData_MonType*)compressedUntyped;

            if(compressedData->ability != 0)
                return UNIQUE_RARITY_EPIC;

            if(compressedData->moveSelection != 0)
                return UNIQUE_RARITY_RARE;

            return UNIQUE_RARITY_COMMON;
        }

        if(abilityCount != 0)
        {
            if(moveCount <= 1)
                return UNIQUE_RARITY_RARE;
            else
                return UNIQUE_RARITY_EPIC;
        }

        return UNIQUE_RARITY_COMMON;
    }
    else
    {
        struct CustomMonData const* monData = &sCustomPokemon[id]; 
        AGB_ASSERT(id < CUSTOM_MON_COUNT);

        switch (monData->customTrainerId)
        {
        case CUSTOM_TRAINER_COMMON:
            return UNIQUE_RARITY_COMMON;
        
        case CUSTOM_TRAINER_RARE:
            return UNIQUE_RARITY_RARE;
        
        case CUSTOM_TRAINER_EPIC:
            return UNIQUE_RARITY_EPIC;
        
        case CUSTOM_TRAINER_EXOTIC:
            return UNIQUE_RARITY_EXOTIC;

        case CUSTOM_TRAINER_LEGEND:
            return UNIQUE_RARITY_LEGENDARY;
        }

        // We expect most/all of these to be classed as exotic
        return UNIQUE_RARITY_EXOTIC;
    }
}

u8 const* RogueGift_GetRarityName(u8 rarity)
{
    switch (rarity)
    {
    case UNIQUE_RARITY_COMMON:
        return sCustomTrainers[CUSTOM_TRAINER_COMMON].name;
    
    case UNIQUE_RARITY_RARE:
        return sCustomTrainers[CUSTOM_TRAINER_RARE].name;
    
    case UNIQUE_RARITY_EPIC:
        return sCustomTrainers[CUSTOM_TRAINER_EPIC].name;
    
    case UNIQUE_RARITY_EXOTIC:
        return sCustomTrainers[CUSTOM_TRAINER_EXOTIC].name;

    case UNIQUE_RARITY_LEGENDARY:
        return sCustomTrainers[CUSTOM_TRAINER_LEGEND].name;
    }

    AGB_ASSERT(FALSE);
    return sCustomTrainers[CUSTOM_TRAINER_QUESTS].name;
}

void RogueGift_CreateMon(u32 customMonId, struct Pokemon* mon, u16 species, u8 level, u8 fixedIV)
{
    struct CustomTrainerData const* trainerData = NULL;
    u32 temp = 0;
    u16 customMoveCount = RogueGift_GetCustomMonMoveCount(customMonId);
    u16 customAbilityCount = RogueGift_GetCustomMonAbilityCount(customMonId);
    
    if(customMonId & OTID_FLAG_DYNAMIC_CUSTOM_MON)
    {
        u8 customTrainerId = sRarityToCustomTrainerIndex[RogueGift_GetCustomMonRarity(customMonId)];
        trainerData = &sCustomTrainers[customTrainerId];

        ZeroMonData(mon);
        CreateMon(mon, species, level, fixedIV, 0, 0, OT_ID_CUSTOM_MON, customMonId);

        // Assign pokeball
        temp = ITEM_ROGUE_BALL;
        SetMonData(mon, MON_DATA_POKEBALL, &temp);
    }
    else
    {
        struct CustomMonData const* monData = &sCustomPokemon[customMonId]; 
        trainerData = &sCustomTrainers[monData->customTrainerId];

        AGB_ASSERT(customMonId < CUSTOM_MON_COUNT);
        AGB_ASSERT(Rogue_GetEggSpecies(species) == Rogue_GetEggSpecies(monData->species));
        AGB_ASSERT(trainerData->trainerId & OTID_FLAG_CUSTOM_MON);
        AGB_ASSERT(!(trainerData->trainerId & OTID_FLAG_DYNAMIC_CUSTOM_MON));

        ZeroMonData(mon);
        CreateMon(mon, species, level, fixedIV, 0, 0, OT_ID_CUSTOM_MON, trainerData->trainerId);

        // Update nickname
        if(monData->nickname != NULL)
        {
            SetMonData(mon, MON_DATA_NICKNAME, monData->nickname);
        }

        // Assign pokeball
        temp = monData->pokeball;
        SetMonData(mon, MON_DATA_POKEBALL, &temp);

        // Set shiny state
        temp = monData->isShiny ? 1 : 0;
        SetMonData(mon, MON_DATA_IS_SHINY, &temp);
    }

    // Met location
    temp = METLOC_FATEFUL_ENCOUNTER;
    SetMonData(mon, MON_DATA_MET_LOCATION, &temp);

    // Update OT name
    SetMonData(mon, MON_DATA_OT_NAME, trainerData->name);

    // Update OT colour
    temp = trainerData->trainerColour;
    SetMonData(mon, MON_DATA_OT_GENDER, &temp);

    // Default moveset is first 4 moves from custom moveset
    if(customMoveCount)
    {
        u8 m, j;
        u16 moves[MAX_MON_MOVES];

        for(m = 0; m < MAX_MON_MOVES && m < customMoveCount; ++m)
        {
            moves[m] = RogueGift_GetCustomMonMove(customMonId, m);
        }

        // Fill the rest of the moves with default moves
        for(j = 0; m < MAX_MON_MOVES; ++m, ++j)
        {
            moves[m] = GetMonData(mon, MON_DATA_MOVE1 + j);
        }

        // Give back moves
        for(m = 0; m < MAX_MON_MOVES; ++m)
        {
            temp = moves[m];
            SetMonData(mon, MON_DATA_MOVE1 + m, &temp);
            SetMonData(mon, MON_DATA_PP1 + m, &gBattleMoves[temp].pp);
        }
    }

    // Default custom ability
    if(customAbilityCount)
    {
        temp = (RogueGift_GetCustomMonAbility(customMonId, 1) != ABILITY_NONE) ? (Random() % 2) : 0;
        SetMonData(mon, MON_DATA_ABILITY_NUM, &temp);
    }
}

static u32 SelectNextMoveIndex(u16 species)
{
    if(RogueMiscQuery_AnyActiveElements())
    {
        u32 i;
        u16 moveId = RogueMiscQuery_SelectRandomElement(Random());
        RogueMiscQuery_EditElement(QUERY_FUNC_EXCLUDE, moveId);

        for (i = 0; i < ARRAY_COUNT(sDynamicCustomMonMoves); i++)
        {
            if(sDynamicCustomMonMoves[i] == moveId)
                return 1 + i;
        }

        // Should never get here
        AGB_ASSERT(FALSE);
        return 1;
    }

    // Can get here if we've ran out of move options, as everything else is already known
    return 0;
}

static u16 GetDynamicMoveIndex(u16 move)
{
    u16 i;

    for(i = 0; i < ARRAY_COUNT(sDynamicCustomMonMoves); ++i)
    {
        if(sDynamicCustomMonMoves[i] == move)
            return i + 1;
    }

    AGB_ASSERT(FALSE);
    return 0;
}

static u16 SelectNextMoveSelection(u16 species, u8 moveCount)
{
    u16 move1 = 0;
    u16 move2 = 0;

    AGB_ASSERT(moveCount <= 2);
    if(moveCount >= 1)
        move1 = SelectNextMoveIndex(species);
    if(moveCount >= 2)
        move2 = SelectNextMoveIndex(species);

    return EncodeDynamicMoveSelection(move1, move2);
}

static u32 SelectNextAbilityIndex(u16 species)
{
    u8 i;

    // Give the mon a new ability for it
    while(TRUE)
    {
        u32 idx = (Random() % ARRAY_COUNT(sDynamicCustomMonAbilities));

        for(i = 0; i < NUM_ABILITY_SLOTS; ++i)
        {
            if(GetAbilityBySpecies(species, i, 0) == sDynamicCustomMonAbilities[idx])
            {
                idx = 10000;
                break;
            }
        }

        if(idx != 10000)
            return 1 + idx;
    }

    return 0;
}

static u16 SelectNextUniqueAbility(u16 species, u8 creationType)
{
    u16 ability;
    u16 nativeUniqueAbility = GetUniqueAbilityBySpecies(species);

    do
    {
        ability = DYNAMIC_UNIQUE_ABILITY_MIN + Random() % (DYNAMIC_UNIQUE_ABILITY_MAX - DYNAMIC_UNIQUE_ABILITY_MIN + 1);
    }
    while (!RogueGift_IsDynamicUniqueAbilityEligible(ability)
        || ability == nativeUniqueAbility
        || (ability == ABILITY_CREATION && !HasCreationSynergyProfile(creationType)));

    return ability;
}

static bool8 IsNativeStandardAbility(u16 species, u16 ability)
{
    u8 i;

    for(i = 0; i < NUM_ABILITY_SLOTS; ++i)
    {
        if(GetAbilityBySpecies(species, i, 0) == ability)
            return TRUE;
    }

    return FALSE;
}

static u8 SelectLegendaryAbilitySeed(u16 species, u16 moveSelection, u16 uniqueAbility, u8 format)
{
    u8 initialSeed = Random() & 0x3;
    u8 offset;

    for(offset = 0; offset < 4; ++offset)
    {
        u8 seed = (initialSeed + offset) & 0x3;
        u16 ability = DecodeLegendaryStandardAbility(moveSelection, uniqueAbility, format, seed);

        if(!IsNativeStandardAbility(species, ability))
            return seed;
    }

    AGB_ASSERT(FALSE);
    return initialSeed;
}

static bool8 SpeciesProfileContainsMove(u16 species, u16 move)
{
    u16 i;

    for(i = 0; gRoguePokemonProfiles[species].levelUpMoves[i].move != MOVE_NONE; ++i)
    {
        if(gRoguePokemonProfiles[species].levelUpMoves[i].move == move)
            return TRUE;
    }

    for(i = 0; gRoguePokemonProfiles[species].tutorMoves[i] != MOVE_NONE; ++i)
    {
        if(gRoguePokemonProfiles[species].tutorMoves[i] == move)
            return TRUE;
    }

    return FALSE;
}

struct SelectedDynamicSynergy
{
    u16 move;
    u8 choice;
};

static struct SelectedDynamicSynergy SelectDynamicSynergyFromProfile(u16 species, struct DynamicSynergyProfile profile, u16 suppliedMove)
{
    struct SelectedDynamicSynergy selection = { MOVE_NONE, DYNAMIC_SYNERGY_CHOICE_NATURAL };
    u8 eligibleChoices[3];
    u8 eligibleCount = 0;
    u8 i;

    for(i = 0; i < ARRAY_COUNT(profile.moves); ++i)
    {
        if(profile.moves[i] != MOVE_NONE)
            RogueMiscQuery_EditElement(QUERY_FUNC_EXCLUDE, profile.moves[i]);
    }

    if(profile.policy == DYNAMIC_SYNERGY_POLICY_OFFENSE)
    {
        if(gSpeciesInfo[species].baseAttack >= gSpeciesInfo[species].baseSpAttack + 20)
        {
            if(profile.moves[0] != MOVE_NONE)
                eligibleChoices[eligibleCount++] = 0;
            if(profile.moves[2] != MOVE_NONE)
                eligibleChoices[eligibleCount++] = 2;
        }
        else if(gSpeciesInfo[species].baseSpAttack >= gSpeciesInfo[species].baseAttack + 20)
        {
            if(profile.moves[1] != MOVE_NONE)
                eligibleChoices[eligibleCount++] = 1;
            if(profile.moves[2] != MOVE_NONE)
                eligibleChoices[eligibleCount++] = 2;
        }
    }

    if(eligibleCount == 0)
    {
        for(i = 0; i < ARRAY_COUNT(profile.moves); ++i)
        {
            if(profile.moves[i] != MOVE_NONE)
                eligibleChoices[eligibleCount++] = i;
        }
    }

    for(i = 0; i < eligibleCount; ++i)
    {
        u16 move = profile.moves[eligibleChoices[i]];

        if(move == suppliedMove || SpeciesProfileContainsMove(species, move))
            return selection;
    }

    if(eligibleCount != 0)
    {
        selection.choice = eligibleChoices[Random() % eligibleCount];
        selection.move = profile.moves[selection.choice];
    }

    return selection;
}

static struct SelectedDynamicSynergy SelectDynamicUniqueAbilitySynergy(u16 species, u16 ability, u16 suppliedMove)
{
    if(ability == ABILITY_CREATION)
        return (struct SelectedDynamicSynergy){ MOVE_NONE, DYNAMIC_SYNERGY_CHOICE_NATURAL };

    return SelectDynamicSynergyFromProfile(species, GetDynamicUniqueAbilitySynergyProfile(ability), suppliedMove);
}

static struct SelectedDynamicSynergy SelectCreationSynergy(u16 species, u8 type, u16 suppliedMove)
{
    return SelectDynamicSynergyFromProfile(species, GetCreationSynergyProfile(type), suppliedMove);
}

#ifdef ROGUE_DEBUG
u8 RogueGift_DebugSelectDynamicSynergyChoice(u16 species, u16 ability, u16 suppliedMove)
{
    struct SelectedDynamicSynergy selection;

    RogueCustomQuery_Begin();
    selection = SelectDynamicUniqueAbilitySynergy(species, ability, suppliedMove);
    RogueCustomQuery_End();
    return selection.choice;
}

u16 RogueGift_DebugSelectCreationSynergyMove(u16 species, u8 type, u16 suppliedMove)
{
    struct SelectedDynamicSynergy selection;

    RogueCustomQuery_Begin();
    selection = SelectCreationSynergy(species, type, suppliedMove);
    RogueCustomQuery_End();
    return selection.move;
}
#endif

static u32 SelectRandomType(u16 species, u8 index)
{
    u8 type;

    do
    {
        type = Random() % NUMBER_OF_MON_TYPES;
    }
    while (!IS_STANDARD_TYPE(type) || GetTypeBySpecies(species, 0, 0) == type || GetTypeBySpecies(species, 1, 0) == type);

    return type;
}

static u32 CreateDynamicMonId(u8 rarity, u16 species, bool8 ignoreTypingUnlockGate)
{
    u16 i;
    u32 temp;
    struct CompressedDynamicData compressedDataUntyped = {0};

    switch (Random() % 2)
    {
    case 0:
        compressedDataUntyped.format = COMPRESSED_FORMAT_ORIGINAL;
        break;

    case 1:
        compressedDataUntyped.format = COMPRESSED_FORMAT_MON_TYPE;
        break;
    }

    if(compressedDataUntyped.format == COMPRESSED_FORMAT_MON_TYPE && !ignoreTypingUnlockGate && !RogueHub_HasUpgrade(HUB_UPGRADE_LAB_UNIQUE_TYPINGS))
        compressedDataUntyped.format = COMPRESSED_FORMAT_ORIGINAL;

    if(rarity == UNIQUE_RARITY_LEGENDARY)
    {
        if(compressedDataUntyped.format == COMPRESSED_FORMAT_MON_TYPE)
            compressedDataUntyped.format = COMPRESSED_FORMAT_MON_TYPE_UNIQUE_ABILITY;
        else
            compressedDataUntyped.format = COMPRESSED_FORMAT_ORIGINAL_UNIQUE_ABILITY;
    }

    // Start query with moves which are valid
    RogueCustomQuery_Begin();

    for (i = 0; i < ARRAY_COUNT(sDynamicCustomMonMoves); i++)
    {
        RogueMiscQuery_EditElement(QUERY_FUNC_INCLUDE, sDynamicCustomMonMoves[i]);
    }

    for (i = 0; gRoguePokemonProfiles[species].levelUpMoves[i].move != MOVE_NONE; i++)
    {
        RogueMiscQuery_EditElement(QUERY_FUNC_EXCLUDE, gRoguePokemonProfiles[species].levelUpMoves[i].move);
    }

    for (i = 0; gRoguePokemonProfiles[species].tutorMoves[i] != MOVE_NONE; i++)
    {
        RogueMiscQuery_EditElement(QUERY_FUNC_EXCLUDE, gRoguePokemonProfiles[species].tutorMoves[i]);
    }

    if(compressedDataUntyped.format == COMPRESSED_FORMAT_ORIGINAL)
    {
        struct CompressedDynamicData_Original* compressedData = (struct CompressedDynamicData_Original*)&compressedDataUntyped;

        switch (rarity)
        {
        case UNIQUE_RARITY_COMMON:
            compressedData->moveSelection = SelectNextMoveSelection(species, 2);
            break;

        case UNIQUE_RARITY_RARE:
            compressedData->moveSelection = SelectNextMoveSelection(species, 1);
            compressedData->ability = SelectNextAbilityIndex(species);
            break;

        case UNIQUE_RARITY_EPIC:
            compressedData->moveSelection = SelectNextMoveSelection(species, 2);
            compressedData->ability = SelectNextAbilityIndex(species);
            break;

        default:
            AGB_ASSERT(FALSE);
            break;
        }
    }
    else if(compressedDataUntyped.format == COMPRESSED_FORMAT_ORIGINAL_UNIQUE_ABILITY)
    {
        struct CompressedDynamicData_OriginalUniqueAbility* compressedData = (struct CompressedDynamicData_OriginalUniqueAbility*)&compressedDataUntyped;

        switch (rarity)
        {
        case UNIQUE_RARITY_LEGENDARY:
        {
            struct SelectedDynamicSynergy synergy;
            u8 creationType = GetTypeBySpecies(species, 0, 0);

            compressedData->uniqueAbility = SelectNextUniqueAbility(species, creationType);
            if(compressedData->uniqueAbility == ABILITY_CREATION)
                synergy = SelectCreationSynergy(species, creationType, MOVE_NONE);
            else
                synergy = SelectDynamicUniqueAbilitySynergy(species, compressedData->uniqueAbility, MOVE_NONE);
            compressedData->synergyChoice = synergy.choice;
            if(compressedData->uniqueAbility == ABILITY_CREATION && synergy.move != MOVE_NONE)
                compressedData->moveSelection = EncodeDynamicMoveSelection(GetDynamicMoveIndex(synergy.move), SelectNextMoveIndex(species));
            else
                compressedData->moveSelection = SelectNextMoveSelection(species, 2);
            compressedData->abilitySeed = SelectLegendaryAbilitySeed(species, compressedData->moveSelection, compressedData->uniqueAbility, compressedData->format);
            break;
        }

        default:
            AGB_ASSERT(FALSE);
            break;
        }
    }
    else if(compressedDataUntyped.format == COMPRESSED_FORMAT_MON_TYPE)
    {
        struct CompressedDynamicData_MonType* compressedData = (struct CompressedDynamicData_MonType*)&compressedDataUntyped;
        compressedData->typeSlot = Random() % 2;
        compressedData->typeMoveFlip = Random() % 2;
        compressedData->type = SelectRandomType(species, compressedData->typeSlot);
        RogueMiscQuery_EditElement(QUERY_FUNC_EXCLUDE, SelectTypeBasedExtraMove(compressedData->type, compressedData->typeSlot, compressedData->typeMoveFlip));

        switch (rarity)
        {
        case UNIQUE_RARITY_COMMON:
            break;

        case UNIQUE_RARITY_RARE:
            compressedData->moveSelection = SelectNextMoveSelection(species, 2);
            break;

        case UNIQUE_RARITY_EPIC:
            compressedData->moveSelection = SelectNextMoveSelection(species, 1);
            compressedData->ability = SelectNextAbilityIndex(species);
            break;

        default:
            AGB_ASSERT(FALSE);
            break;
        }
    }
    else if(compressedDataUntyped.format == COMPRESSED_FORMAT_MON_TYPE_UNIQUE_ABILITY)
    {
        struct CompressedDynamicData_MonTypeUniqueAbility* compressedData = (struct CompressedDynamicData_MonTypeUniqueAbility*)&compressedDataUntyped;
        u8 typeSlot = Random() % 2;
        u8 typeMoveFlip = Random() % 2;
        u8 type = SelectRandomType(species, typeSlot);

        RogueMiscQuery_EditElement(QUERY_FUNC_EXCLUDE, SelectTypeBasedExtraMove(type, typeSlot, typeMoveFlip));

        switch (rarity)
        {
        case UNIQUE_RARITY_LEGENDARY:
        {
            u8 creationType = typeSlot == 0 ? type : GetTypeBySpecies(species, 0, 0);
            u16 typeMove = SelectTypeBasedExtraMove(type, typeSlot, typeMoveFlip);
            struct SelectedDynamicSynergy synergy;
            u16 randomMoveIndex;

            compressedData->uniqueAbility = SelectNextUniqueAbility(species, creationType);
            if(compressedData->uniqueAbility == ABILITY_CREATION)
                synergy = SelectCreationSynergy(species, creationType, typeMove);
            else
                synergy = SelectDynamicUniqueAbilitySynergy(species, compressedData->uniqueAbility, typeMove);
            compressedData->synergyChoice = synergy.choice;
            if(compressedData->uniqueAbility == ABILITY_CREATION && synergy.move != MOVE_NONE)
                randomMoveIndex = GetDynamicMoveIndex(synergy.move);
            else
                randomMoveIndex = SelectNextMoveIndex(species);
            compressedData->typeMoveSelection = EncodeTypedUniqueMoveSelection(type, typeSlot, typeMoveFlip, randomMoveIndex);
            compressedData->abilitySeed = SelectLegendaryAbilitySeed(species, compressedData->typeMoveSelection, compressedData->uniqueAbility, compressedData->format);
            break;
        }

        default:
            AGB_ASSERT(FALSE);
            break;
        }
    }
    else
    {
        AGB_ASSERT(FALSE);
    }

    RogueCustomQuery_End();

    temp = CompressedDynamicDataToCustomMonId(&compressedDataUntyped);
    temp |= (OTID_FLAG_CUSTOM_MON | OTID_FLAG_DYNAMIC_CUSTOM_MON);

#ifdef ROGUE_DEBUG
    // Ensure data (un)compresses correctly
    {
        struct DynamicMonData dynamicData = {0};

        UncompressDynamicMonData(temp, &dynamicData);
    }

#endif
    return temp;
}

u32 RogueGift_CreateDynamicMonId(u8 rarity, u16 species)
{
    return CreateDynamicMonId(rarity, species, FALSE);
}

u32 RogueGift_CreateDynamicMonIdRaw(u8 rarity, u16 species)
{
    return CreateDynamicMonId(rarity, species, TRUE);
}

static bool8 IsDynamicUniqueMonValid(struct UniqueMon* mon)
{
    return !(mon->species == SPECIES_NONE || mon->customMonId == 0 || mon->countDown == 0);
}

static bool8 FilterDynamicUniqueSpecies(u16 species, void* usrData)
{
    (void)usrData;
    return Query_IsSpeciesEnabled(species);
}

static void ApplyDynamicUniqueSpeciesQuery(void)
{
    RogueMonQuery_IsSpeciesActive();
    RogueMonQuery_TransformIntoEggSpecies();
    // Transformations may introduce a species which the initial active-species
    // pass rejected, so validate the transformed pool again.
    RogueMonQuery_CustomFilter(FilterDynamicUniqueSpecies, NULL);
    RogueMonQuery_IsLegendary(QUERY_FUNC_EXCLUDE);
}

#ifdef ROGUE_DEBUG
bool8 RogueGift_DebugIsSpeciesInDynamicUniquePool(u16 species)
{
    bool8 isIncluded;
    u8 dexVariantToRestore = RoguePokedex_GetDexVariant();

    RoguePokedex_SetDexVariant(POKEDEX_VARIANT_DEFAULT);
    RogueMonQuery_Begin();
    ApplyDynamicUniqueSpeciesQuery();
    isIncluded = RogueMiscQuery_CheckState(species);
    RogueMonQuery_End();
    RoguePokedex_SetDexVariant(dexVariantToRestore);

    return isIncluded;
}
#endif

u8 RogueGift_RollDynamicUniqueRarity(bool8 ignoreUnlockGates)
{
    u8 rarity;

    switch (Random() % 8)
    {
    case 0:
        rarity = UNIQUE_RARITY_LEGENDARY;
        break;

    case 1:
    case 2:
    case 3:
        rarity = UNIQUE_RARITY_EPIC;
        break;

    case 4:
    case 5:
        rarity = UNIQUE_RARITY_RARE;
        break;
    
    case 6:
    case 7:
        rarity = UNIQUE_RARITY_COMMON;
        break;

    default:
        AGB_ASSERT(FALSE);
        rarity = UNIQUE_RARITY_COMMON;
        break;
    }

    if(ignoreUnlockGates)
        return rarity;

    if(rarity == UNIQUE_RARITY_LEGENDARY && !RogueHub_HasUpgrade(HUB_UPGRADE_LAB_UNIQUE_MON_RARITY_LEGENDARY))
        rarity = UNIQUE_RARITY_EPIC;

    if(rarity == UNIQUE_RARITY_EPIC && !RogueHub_HasUpgrade(HUB_UPGRADE_LAB_UNIQUE_MON_RARITY_EPIC))
        rarity = UNIQUE_RARITY_RARE;

    if(rarity == UNIQUE_RARITY_RARE && !RogueHub_HasUpgrade(HUB_UPGRADE_LAB_UNIQUE_MON_RARITY_RARE))
        rarity = UNIQUE_RARITY_COMMON;

    return rarity;
}

static bool8 IsSlotUnlocked(u8 slot)
{
    if(RogueHub_HasUpgrade(HUB_UPGRADE_LAB_UNIQUE_MON_LAB))
    {
        // 4 slots unlocked by default
        if(slot < 4)
            return TRUE;

        if(slot < 6)
            return RogueHub_HasUpgrade(HUB_UPGRADE_LAB_UNIQUE_MON_SLOTS0);

        if(slot < 8)
            return RogueHub_HasUpgrade(HUB_UPGRADE_LAB_UNIQUE_MON_SLOTS1);
    }

    return FALSE;
}

void RogueGift_EnsureDynamicCustomMonsAreValid()
{
    u8 i, write;
    bool8 retainExisting[DYNAMIC_UNIQUE_MON_COUNT] = {FALSE};
    u16 newSpecies[DYNAMIC_UNIQUE_MON_COUNT];

    // We use query below, so grab some new unique species now
    {
        // Override dex variant to our max nat dex
        u8 dexVariantToRestore = RoguePokedex_GetDexVariant();
        RoguePokedex_SetDexVariant(POKEDEX_VARIANT_DEFAULT);

        RogueMonQuery_Begin();
        ApplyDynamicUniqueSpeciesQuery();
        
        for(i = 0; i < DYNAMIC_UNIQUE_MON_COUNT; ++i)
        {
            if(IsDynamicUniqueMonValid(&gRogueSaveBlock->dynamicUniquePokemon[i])
             && RogueMiscQuery_CheckState(gRogueSaveBlock->dynamicUniquePokemon[i].species))
            {
                retainExisting[i] = TRUE;
                RogueMiscQuery_EditElement(QUERY_FUNC_EXCLUDE, gRogueSaveBlock->dynamicUniquePokemon[i].species);
            }
        }

        // Remove random entries until we can safely calcualte weights without going over
        while(RogueWeightQuery_IsOverSafeCapacity())
        {
            RogueMiscQuery_FilterByChance(Random(), QUERY_FUNC_INCLUDE, 50, DYNAMIC_UNIQUE_MON_COUNT);
        }

        RogueWeightQuery_Begin();
        RogueWeightQuery_FillWeights(1);

        for(i = 0; i < DYNAMIC_UNIQUE_MON_COUNT; ++i)
        {
            newSpecies[i] = RogueWeightQuery_SelectRandomFromWeightsWithUpdate(Random(), 0);
        }

        RogueWeightQuery_End();

        RogueMonQuery_End();

        RoguePokedex_SetDexVariant(dexVariantToRestore);
    }

    // Shift all the empty slots up 
    write = 0;
    for(i = 0; i < DYNAMIC_UNIQUE_MON_COUNT; ++i)
    {
        if(IsDynamicUniqueMonValid(&gRogueSaveBlock->dynamicUniquePokemon[i]) && retainExisting[i])
        {
            if(write != i)
            {
                memcpy(&gRogueSaveBlock->dynamicUniquePokemon[write], &gRogueSaveBlock->dynamicUniquePokemon[i], sizeof(struct UniqueMon));
                memset(&gRogueSaveBlock->dynamicUniquePokemon[i], 0, sizeof(struct UniqueMon));
            }

            write++;
        }
        else
        {
            memset(&gRogueSaveBlock->dynamicUniquePokemon[i], 0, sizeof(struct UniqueMon));
        }
    }

    // Replace invalid mons
    for(i = 0; i < DYNAMIC_UNIQUE_MON_COUNT; ++i)
    {
        // We don't want to populate slots that aren't active
        if(!IsSlotUnlocked(i))
            continue;

        if(!IsDynamicUniqueMonValid(&gRogueSaveBlock->dynamicUniquePokemon[i]))
        {
            u8 rarity = RogueGift_RollDynamicUniqueRarity(FALSE);

            gRogueSaveBlock->dynamicUniquePokemon[i].countDown = 60 + 30 * i; // Time remaining is based on the slot

            gRogueSaveBlock->dynamicUniquePokemon[i].species = newSpecies[i];
            gRogueSaveBlock->dynamicUniquePokemon[i].customMonId = RogueGift_CreateDynamicMonId(rarity, newSpecies[i]);
        }
    }

}

void RogueGift_ClearDynamicCustomMons()
{
    memset(&gRogueSaveBlock->dynamicUniquePokemon[0], 0, sizeof(struct UniqueMon) * DYNAMIC_UNIQUE_MON_COUNT);
}

struct UniqueMon* RogueGift_GetDynamicUniqueMon(u8 slot)
{
    AGB_ASSERT(slot < DYNAMIC_UNIQUE_MON_COUNT);
    return &gRogueSaveBlock->dynamicUniquePokemon[slot];
}

void RogueGift_CountDownDynamicCustomMons()
{
    u8 i;

    for(i = 0; i < DYNAMIC_UNIQUE_MON_COUNT; ++i)
    {
        if(gRogueSaveBlock->dynamicUniquePokemon[i].countDown != 0)
            --gRogueSaveBlock->dynamicUniquePokemon[i].countDown;
    }
}

void RogueGift_RemoveDynamicCustomMon(u32 customMonId)
{
    u8 i;

    for(i = 0; i < DYNAMIC_UNIQUE_MON_COUNT; ++i)
    {
        if(gRogueSaveBlock->dynamicUniquePokemon[i].customMonId == customMonId)
        {
            memset(&gRogueSaveBlock->dynamicUniquePokemon[i], 0, sizeof(struct UniqueMon));
        }
    }
}

bool8 RogueGift_IsDynamicMonSlotEnabled(u8 slot)
{
    AGB_ASSERT(slot < DYNAMIC_UNIQUE_MON_COUNT);

    if(!IsSlotUnlocked(slot))
        return FALSE;

    return IsDynamicUniqueMonValid(&gRogueSaveBlock->dynamicUniquePokemon[slot]);
}

u32 RogueGift_TryFindEnabledDynamicCustomMonForSpecies(u16 species)
{
    u8 i;

    species = Rogue_GetEggSpecies(species);

    for(i = 0; i < DYNAMIC_UNIQUE_MON_COUNT; ++i)
    {
        if(RogueGift_IsDynamicMonSlotEnabled(i))
        {
            if(gRogueSaveBlock->dynamicUniquePokemon[i].species == species)
                return gRogueSaveBlock->dynamicUniquePokemon[i].customMonId;
        }
    }

    return 0;
}

static u8 ModifyShinyType(u8 type)
{
    if(type == TYPE_NONE)
        return type;

    do
    {
        type = (type + 5) % NUMBER_OF_MON_TYPES;
    } while (!IS_STANDARD_TYPE(type));

    return type;
}

bool8 RogueGift_TryApplyPaletteModify(u32 id, bool8 isShiny, u16 const* inputPal, u16 const* layerRefPal, u16* outputPal)
{
    u8 type1 = RogueGift_GetCustomMonType(id, 0);
    u8 type2 = RogueGift_GetCustomMonType(id, 1);

    if(type1 != TYPE_NONE || type2 != TYPE_NONE)
    {
        u16 layerPal[16];
        u16 layerWhitePoints[PALETTE_MODIFY_LAYER_COUNT];
        u16 colorsToApply[PALETTE_MODIFY_LAYER_COUNT];

        if(isShiny)
        {
            type1 = ModifyShinyType(type1);
            type2 = ModifyShinyType(type2);
        }

        colorsToApply[0] = RGB_ALPHA;
        colorsToApply[1] = RGB_ALPHA;
        colorsToApply[2] = RGB_ALPHA;

        if(type1 != TYPE_NONE)
            colorsToApply[0] = sTypeTintColors[type1];

        if(type2 != TYPE_NONE)
            colorsToApply[1] = sTypeTintColors[type2];

        if(layerRefPal == NULL)
        {
            Rogue_GenerateLayerPaletteByHue(inputPal, inputPal, layerPal);
            Rogue_GenerateWhitePointsPerLayers(inputPal, layerPal, layerWhitePoints, gDefaultPaletteLayerMasks);
        }
        else
        {
            Rogue_GenerateLayerPaletteByHue(layerRefPal, layerRefPal, layerPal);
            Rogue_GenerateWhitePointsPerLayers(layerRefPal, layerPal, layerWhitePoints, gDefaultPaletteLayerMasks);
            Rogue_GenerateLayerPaletteByHue(inputPal, layerRefPal, layerPal);
        }

        Rogue_ModifyPaletteByLayersHueShift(inputPal, layerPal, layerWhitePoints, outputPal, gDefaultPaletteLayerMasks, colorsToApply);
        return TRUE;
    }

    return FALSE;
}
