// Generated by scripts/generate_species_change_report.py.
// Consumed by PokemonQueryBaker to mark stats above the canonical baseline.
// Do not edit by hand.

static u8 GetDivergenceStatBuffFlags(u16 species)
{
    switch (species)
    {
    case SPECIES_ARBOK:
        return (1u << STAT_HP);
    case SPECIES_ARIADOS:
        return (1u << STAT_HP);
    case SPECIES_AROMATISSE:
        return (1u << STAT_DEF);
    case SPECIES_AVALUGG:
        return (1u << STAT_SPDEF);
    case SPECIES_BANETTE:
        return (1u << STAT_HP) | (1u << STAT_ATK) | (1u << STAT_DEF) | (1u << STAT_SPDEF) | (1u << STAT_SPEED);
    case SPECIES_BANETTE_MEGA:
        return (1u << STAT_HP) | (1u << STAT_ATK) | (1u << STAT_DEF) | (1u << STAT_SPDEF) | (1u << STAT_SPEED);
    case SPECIES_BEAUTIFLY:
        return (1u << STAT_SPEED);
    case SPECIES_BEHEEYEM:
        return (1u << STAT_HP);
    case SPECIES_BOLTUND:
        return (1u << STAT_ATK);
    case SPECIES_CACTURNE:
        return (1u << STAT_DEF) | (1u << STAT_SPDEF) | (1u << STAT_SPEED);
    case SPECIES_CARNIVINE:
        return (1u << STAT_HP);
    case SPECIES_CASTFORM_NORMAL:
        return (1u << STAT_HP) | (1u << STAT_SPATK) | (1u << STAT_SPEED);
    case SPECIES_CASTFORM_RAINY:
        return (1u << STAT_HP) | (1u << STAT_SPATK) | (1u << STAT_SPEED);
    case SPECIES_CASTFORM_SNOWY:
        return (1u << STAT_HP) | (1u << STAT_SPATK) | (1u << STAT_SPEED);
    case SPECIES_CASTFORM_SUNNY:
        return (1u << STAT_HP) | (1u << STAT_SPATK) | (1u << STAT_SPEED);
    case SPECIES_CHIMECHO:
        return (1u << STAT_HP) | (1u << STAT_DEF) | (1u << STAT_SPATK) | (1u << STAT_SPDEF) | (1u << STAT_SPEED);
    case SPECIES_CHIMECHO_MEGA:
        return (1u << STAT_HP) | (1u << STAT_DEF) | (1u << STAT_SPATK) | (1u << STAT_SPDEF) | (1u << STAT_SPEED);
    case SPECIES_DEDENNE:
        return (1u << STAT_SPATK);
    case SPECIES_DELCATTY:
        return (1u << STAT_ATK) | (1u << STAT_SPATK);
    case SPECIES_DELIBIRD:
        return (1u << STAT_ATK) | (1u << STAT_SPATK) | (1u << STAT_SPEED);
    case SPECIES_DEWGONG:
        return (1u << STAT_DEF);
    case SPECIES_DUBWOOL:
        return (1u << STAT_HP);
    case SPECIES_DUSTOX:
        return (1u << STAT_HP);
    case SPECIES_ELDEGOSS:
        return (1u << STAT_HP);
    case SPECIES_EMOLGA:
        return (1u << STAT_SPATK);
    case SPECIES_FALINKS:
        return (1u << STAT_HP) | (1u << STAT_ATK) | (1u << STAT_DEF) | (1u << STAT_SPDEF);
    case SPECIES_FROSMOTH:
        return (1u << STAT_SPEED);
    case SPECIES_GRAPPLOCT:
        return (1u << STAT_SPDEF);
    case SPECIES_GRUMPIG:
        return (1u << STAT_HP) | (1u << STAT_DEF) | (1u << STAT_SPATK);
    case SPECIES_GUMSHOOS:
        return (1u << STAT_HP);
    case SPECIES_HEATMOR:
        return (1u << STAT_SPEED);
    case SPECIES_HYPNO:
        return (1u << STAT_SPATK);
    case SPECIES_KECLEON:
        return (1u << STAT_HP) | (1u << STAT_DEF);
    case SPECIES_KLAWF:
        return (1u << STAT_SPDEF);
    case SPECIES_KOMALA:
        return (1u << STAT_DEF);
    case SPECIES_KRICKETUNE:
        return (1u << STAT_ATK) | (1u << STAT_DEF) | (1u << STAT_SPATK) | (1u << STAT_SPDEF);
    case SPECIES_LEDIAN:
        return (1u << STAT_HP) | (1u << STAT_ATK) | (1u << STAT_SPEED);
    case SPECIES_LUMINEON:
        return (1u << STAT_ATK) | (1u << STAT_SPATK);
    case SPECIES_LUVDISC:
        return (1u << STAT_HP) | (1u << STAT_SPATK) | (1u << STAT_SPEED);
    case SPECIES_MAGCARGO:
        return (1u << STAT_HP);
    case SPECIES_MARACTUS:
        return (1u << STAT_HP);
    case SPECIES_MAROWAK:
        return (1u << STAT_HP) | (1u << STAT_ATK);
    case SPECIES_MAROWAK_ALOLAN:
        return (1u << STAT_HP) | (1u << STAT_ATK);
    case SPECIES_MEOWSTIC_FEMALE:
        return (1u << STAT_SPATK);
    case SPECIES_MEOWSTIC_F_MEGA:
        return (1u << STAT_SPATK);
    case SPECIES_MEOWSTIC_MALE:
        return (1u << STAT_HP);
    case SPECIES_MEOWSTIC_M_MEGA:
        return (1u << STAT_HP);
    case SPECIES_MIGHTYENA:
        return (1u << STAT_SPEED);
    case SPECIES_MOTHIM:
        return (1u << STAT_SPEED);
    case SPECIES_OINKOLOGNE_FEMALE:
        return (1u << STAT_DEF);
    case SPECIES_OINKOLOGNE_MALE:
        return (1u << STAT_ATK);
    case SPECIES_ORBEETLE:
        return (1u << STAT_SPATK);
    case SPECIES_ORBEETLE_GIGANTAMAX:
        return (1u << STAT_SPATK);
    case SPECIES_PARASECT:
        return (1u << STAT_HP);
    case SPECIES_SHIINOTIC:
        return (1u << STAT_HP);
    case SPECIES_SPIDOPS:
        return (1u << STAT_HP);
    case SPECIES_SQUAWKABILLY_BLUE_PLUMAGE:
        return (1u << STAT_HP);
    case SPECIES_SQUAWKABILLY_GREEN_PLUMAGE:
        return (1u << STAT_HP);
    case SPECIES_SQUAWKABILLY_WHITE_PLUMAGE:
        return (1u << STAT_HP);
    case SPECIES_SQUAWKABILLY_YELLOW_PLUMAGE:
        return (1u << STAT_HP);
    case SPECIES_STONJOURNER:
        return (1u << STAT_SPDEF);
    case SPECIES_SUNFLORA:
        return (1u << STAT_SPEED);
    case SPECIES_THIEVUL:
        return (1u << STAT_SPATK);
    case SPECIES_TOGEDEMARU:
        return (1u << STAT_HP);
    case SPECIES_TREVENANT:
        return (1u << STAT_HP);
    case SPECIES_TROPIUS:
        return (1u << STAT_SPATK);
    case SPECIES_TURTONATOR:
        return (1u << STAT_HP);
    case SPECIES_UNOWN:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_B:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_C:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_D:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_E:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_EMARK:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_F:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_G:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_H:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_I:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_J:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_K:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_L:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_M:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_N:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_O:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_P:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_Q:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_QMARK:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_R:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_S:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_T:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_U:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_V:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_W:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_X:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_Y:
        return (1u << STAT_SPEED);
    case SPECIES_UNOWN_Z:
        return (1u << STAT_SPEED);
    case SPECIES_WATCHOG:
        return (1u << STAT_ATK);
    case SPECIES_WIGGLYTUFF:
        return (1u << STAT_DEF) | (1u << STAT_SPDEF);
    case SPECIES_WORMADAM_PLANT_CLOAK:
        return (1u << STAT_HP);
    case SPECIES_WORMADAM_SANDY_CLOAK:
        return (1u << STAT_HP);
    case SPECIES_WORMADAM_TRASH_CLOAK:
        return (1u << STAT_HP);
    case SPECIES_WUGTRIO:
        return (1u << STAT_ATK);
    default:
        return 0;
    }
}
